Repository rainbow-me/rainbow, pull requests merged in 2021-11, with the labels that each got.

#2519 nft v2 clean up and android fixes
  src/components/Tag.js
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
  src/components/token-info/TokenInfoHeading.js
  src/hooks/usePersistentAspectRatio.ts
  src/utils/getDominantColorFromImage.js
  src/utils/getLowResUrl.js
Labels: WIP

#2552 Fix simulator version on CI
  package.json
Labels: needs code review

#2567 Fix android build for 0.66
  patches/react-native-mmkv+1.5.2.patch
Labels: needs code review

#2532 [RNBW-1814] Track Most Recent Nonce
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  src/components/settings-menu/DevSection.js
  src/components/toasts/TestnetToast.js
  src/entities/index.ts
  src/entities/nonce.ts
  src/handlers/localstorage/common.js
  src/handlers/localstorage/nonceManager.ts
  src/handlers/web3.js
  src/hooks/index.js
  src/hooks/useCurrentNonce.ts
  src/hooks/useLoadGlobalData.js
  src/raps/common.ts
  src/redux/data.js
  src/redux/explorer.js
  src/redux/gas.js
  src/redux/nonceManager.ts
  src/redux/reducers.js
  src/redux/store.ts
  src/screens/ExchangeModal.js
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
  yarn.lock
Labels: needs QA

#2553 fix send resolution & domain validation
  e2e/sendSheetFlow.spec.js
  src/components/coin-row/TransactionCoinRow.js
  src/components/contacts/ContactRow.js
  src/components/expanded-state/ContactProfileState.js
  src/components/transaction-list/TransactionList.js
  src/handlers/web3.js
  src/helpers/validators.js
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
  src/utils/abbreviations.js
Labels: needs code review

#2560 add purchasing alert for purchases < 50
  src/components/add-cash/AddCashForm.js
Labels: needs code review

#2566 Do not use Svgs on the main screen and hooks
  package.json
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/send/SendAssetFormCollectible.js
  src/components/svg/RemoteSvg.js
  src/components/svg/SvgImage.js
  src/components/unique-token/UniqueTokenImage.js
  src/handlers/imgix.ts
  src/handlers/svgs.js
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
  src/hooks/useSafeImageUri.ts
  src/utils/getDominantColorFromImage.js
  yarn.lock
Labels: needs code review, needs QA

#2579 Improvements to L2 explorers
  src/redux/fallbackExplorer.js
  src/redux/optimismExplorer.js
  src/redux/polygonExplorer.js
  src/references/index.ts
Labels: needs QA

#2430 Safari Extension
  .gitignore
  extension/img/icon-128.png
  extension/img/icon-16.png
  extension/img/icon-48.png
  extension/manifest.json
  extension/src/main.js
  extension/src/provider.js
  extension/webpack.config.js
  ios/Rainbow Bridge/Info.plist
  ios/Rainbow Bridge/Resources/.gitkeep
  ios/Rainbow Bridge/SafariWebExtensionHandler.swift
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: needs code review, needs product review

#2589 lint - optional txTo
  src/entities/transactions/transaction.ts
Labels: needs code review

#2507 bump browserlist
  package.json
  yarn.lock
Labels: QA later

#2590 only add the url to message on android
  src/components/expanded-state/UniqueTokenExpandedState.js
Labels: needs code review, QA later
