Repository rainbow-me/rainbow, pull requests merged in 2021-12, with the labels that each got.

#2592 UI fixes
  ios/Rainbow/Images.xcassets/addCashIcon.imageset/addCashIcon.png
  ios/Rainbow/Images.xcassets/addCashIcon.imageset/addCashIcon@2x.png
  ios/Rainbow/Images.xcassets/addCashIcon.imageset/addCashIcon@3x.png
  ios/Rainbow/Info.plist
  ios/TransactionListViewHeader.xib
  src/assets/addCashIcon.png
  src/components/buttons/MiniButton.js
  src/components/buttons/TokenSelectionButton.js
  src/components/buttons/rainbow-button/RainbowButton.js
  src/components/coin-divider/CoinDividerButtonLabel.js
  src/components/coin-row/CoinRowInfoButton.js
  src/components/discover-sheet/ListsSection.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/fab/ExchangeFab.js
  src/components/fab/FabWrapper.js
  src/components/fab/FloatingActionButton.js
  src/components/fab/SendFab.js
  src/components/qr-code/ShareButton.js
  src/components/savings/APYPill.js
  src/components/savings/SavingsListRowEmptyState.js
  src/components/savings/SavingsPredictionStepper.js
  src/components/savings/SavingsSheetHeader.js
  src/components/sheet/sheet-action-buttons/SheetActionButton.js
  src/screens/SavingsSheet.js
Labels: needs code review

#2613 Consolidate custom base fee and priority fee into a single state object.
  src/components/expanded-state/custom-gas/FeesPanel.js
Labels: QA later, eip1559

#2612 Decrease interval for meteorology gas data
  src/redux/gas.ts
Labels: QA later, eip1559

#2610 Ensure gas readiness to be determined by price being available also
  src/components/gas/GasSpeedButton.js
Labels: QA later, eip1559

#2535 Fix `NativeCurrencyKeys` to follow export pattern.
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/entities/index.ts
  src/handlers/localstorage/globalSettings.js
  src/redux/settings.js
Labels: QA later

#2608 EIP-1559 behavior polish
  e2e/swapSheetFlow.spec.js
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.js
  src/components/gas/GasSpeedButton.js
  src/hooks/useGas.ts
  src/redux/gas.ts
  src/screens/ExchangeModal.js
Labels: QA later, eip1559

#2594 Fix max size of png obtained from svg
  src/handlers/svgs.js
Labels: needs code review, QA later

#2511 Update `src/handlers/web3` and other impacted files to use TypeScript.
  src/entities/tokens.ts
  src/handlers/uniswap.ts
  src/handlers/web3.js
  src/handlers/web3.ts
  src/helpers/validators.js
  src/parsers/transactions.ts
Labels: QA later

#2621 @jin/christian 1559 polish rebase
  e2e/swapSheetFlow.spec.js
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.js
  src/components/expanded-state/custom-gas/GweiInputPill.js
  src/components/gas/GasSpeedButton.js
  src/helpers/gas.ts
  src/utils/gas.ts
Labels: eip1559

#2606 Fix SheetActionButton sizing on Android, remove width props
  src/components/backup/BackupManualStep.js
  src/components/backup/BackupSheetSection.js
  src/components/error-boundary/Fallback.tsx
  src/components/expanded-state/LiquidityPoolExpandedState.js
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/savings/SavingsSheetEmptyState.js
  src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
  src/components/settings-menu/BackupSection/NeedsBackupView.js
  src/components/sheet/sheet-action-buttons/SheetActionButton.js
  src/components/sheet/sheet-action-buttons/SheetActionButtonRow.js
  src/components/showcase/ShowcaseHeader.js
  src/screens/AddTokenSheet.js
  src/screens/ExplainSheet.js
  src/screens/SendSheet.js
  src/screens/SpeedUpAndCancelSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/screens/WalletDiagnosticsSheet.js
Labels: needs code review, QA later

#2626 Fix eth_sign
  e2e/hardhatTransactionFlow.spec.js
  package.json
  src/model/wallet.ts
  yarn.lock
Labels: needs code review, QA later, eip1559

#2600 Sync balances after tx sooner
  src/App.js
Labels: QA later

#2604 check recipient on-chain balances
  e2e/hardhatTransactionFlow.spec.js
  src/references/cryptokitties-abi.json
Labels: QA later

#2588 revert update blocking
  src/components/asset-list/AssetList.js
  src/components/asset-list/RecyclerAssetList/index.tsx
Labels: QA later

#2614 EIP-1559 - clean up crew
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/gas/GasSpeedButton.js
Labels: eip1559

#2629 fix optimism fee
  src/redux/gas.ts
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
Labels: eip1559

#2631 fix estimated fee calculation when max fee is set below of current base fee
  src/parsers/gas.ts
Labels: eip1559

#2636 l2s default speeds and polling times
  src/components/gas/GasSpeedButton.js
  src/handlers/web3.ts
  src/parsers/gas.ts
  src/parsers/index.ts
  src/redux/gas.ts
  src/screens/SpeedUpAndCancelSheet.js
  src/utils/gas.ts
Labels: eip1559

#2622 @esteban/eip1559 trends and animations
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/helpers/gas.ts
  src/screens/ExplainSheet.js
  src/utils/gas.ts
Labels: eip1559

#2641 Remove hardcoded fallback gas prices for L2 networks
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/parsers/gas.ts
  src/parsers/index.ts
  src/redux/gas.ts
  src/references/index.ts
Labels: eip1559

#2640 Fix balance update logic and fallbacks
  src/redux/fallbackExplorer.js
  src/redux/optimismExplorer.js
Labels: QA later

#2639 eip-1559 explainer clean up + bug fixes
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/gas/GasSpeedButton.js
  src/navigation/config.js
  src/screens/ExplainSheet.js
Labels: QA later, eip1559

#2634 add custom gas validations
  e2e/swapSheetFlow.spec.js
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.js
  src/components/gas/GasSpeedButton.js
  src/hooks/index.js
  src/hooks/useFeesPanelInputRefs.ts
Labels: eip1559

#2647 remove borderRadius prop
  src/components/sheet/SlackSheet.js
Labels: QA later

#2648 Scam list exceptions
  e2e/swapSheetFlow.spec.js
  package.json
  src/utils/ethereumUtils.ts
Labels: QA later

#2649 fees panel focus improvement + fix e2e
  e2e/swapSheetFlow.spec.js
  src/components/gas/GasSpeedButton.js
Labels: QA later, eip1559

#2630 Fix gas fees not updating on fees panel
  src/redux/gas.ts
Labels: needs code review, eip1559, needs code changes

#2654 fix optimism gasprices updates
  src/redux/gas.ts
Labels: needs code review, QA later, eip1559

#2651 Remove unnecessary updateTxFee calls in SendSheet
  src/redux/gas.ts
  src/screens/SendSheet.js
Labels: needs code review, QA later, eip1559

#2611 L2 backend part 1 ( Arbitrum + Polygon )
  src/hooks/useResetAccountState.js
  src/redux/arbitrumExplorer.js
  src/redux/explorer.js
  src/redux/polygonExplorer.js
  src/redux/reducers.js
  src/references/chain-assets.json
  src/screens/SendSheet.js
Labels: needs QA

#2656 Fix: do not update balance if onchain fetch fails
  src/hooks/useUpdateAssetOnchainBalance.js
Labels: needs code review, QA later

#2505 Begin converting more Redux reducers to TypeScript
  src/helpers/keyboardTypes.ts
  src/redux/contacts.js
  src/redux/contacts.ts
  src/redux/imageMetadata.js
  src/redux/imageMetadata.ts
  src/redux/keyboardHeight.ts
Labels: needs code review, QA later

#2663 bump fastlane
  ios/Gemfile.lock
Labels: QA later

#2662 rm wallet list autoscroll
  src/components/change-wallet/WalletList.js
Labels: needs code review, QA later

#2665 fix android tx list menu
  src/components/transaction-list/TransactionList.js
Labels: needs code review, QA later

#2666 add `clearTimeout` to gasPricesHandle in redux gas
  src/redux/gas.ts
Labels: needs code review, eip1559

#2661 fix race condition on selected gas
  src/redux/gas.ts
Labels: needs code review, eip1559

#2672 fix poap uid and tweak image size
  src/parsers/poap.js
Labels: needs code review, QA later, release

#2668 add default arbitrum gas limit
  src/redux/gas.ts
  src/references/ethereum-units.json
Labels: eip1559, release

#2671 WC - delay checking native asset balance
  src/screens/TransactionConfirmationScreen.js
Labels: needs code review, QA later, release

#2669 confirm back up explainer
  src/components/backup/BackupCloudStep.js
  src/components/backup/BackupSheetKeyboardLayout.js
  src/hooks/useWalletCloudBackup.js
  src/screens/ExplainSheet.js
Labels: needs code review, QA later

#2675 fee panels input sanitize numbers and fix focus
  src/components/expanded-state/custom-gas/GweiInputPill.js
Labels: needs code review, QA later, eip1559

#2674 gas speed button: load time and price at same time
  src/components/gas/GasSpeedButton.js
Labels: QA later, eip1559

#2676 fees panel remove input rounding
  src/components/expanded-state/custom-gas/FeesPanel.js
Labels: QA later, eip1559

#2678 fees panel context menu improvements
  src/components/gas/GasSpeedButton.js
Labels: QA later, eip1559

#2673 Release polish
  e2e/swapSheetFlow.spec.js
  package.json
  src/assets/dappLogos/twitter.com.jpg
  src/components/exchange/ExchangeDetailsButton.js
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.js
  src/components/expanded-state/custom-gas/GweiInputPill.js
  src/components/gas/GasSpeedButton.js
  src/components/gas/GasSpeedEmoji.js
  src/components/gas/GasSpeedLabelPager.js
  src/components/send/SendAssetForm.js
  src/components/send/SendAssetFormToken.js
  src/helpers/dappNameHandler.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/parsers/gas.ts
  src/screens/ExchangeModal.js
  src/screens/ExplainSheet.js
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/screens/WalletConnectApprovalSheet.js
  src/styles/colors.js
  src/styles/fonts.js
  src/utils/gas.ts
  yarn.lock
Labels: QA later, eip1559

#2650 Keychain
  android/app/src/main/java/me/rainbow/MainApplication.java
  ios/Podfile.lock
  package.json
  patches/react-native-keychain+8.0.0.patch
  src/App.js
  src/helpers/signingWallet.ts
  src/hooks/useImportingWallet.js
  src/hooks/useManageCloudBackups.js
  src/model/backup.ts
  src/model/keychain.ts
  src/model/migrations.ts
  src/model/wallet.ts
  src/utils/keychainConstants.ts
  tsconfig.json
  yarn.lock
Labels: needs QA, android

#2681 Add animated background for "back" and "scanner" buttons just like on iOS
  package.json
  patches/@gorhom+bottom-sheet+4.1.5.patch
  src/components/discover-sheet/DiscoverSheet.android.js
  src/components/discover-sheet/DiscoverSheetHeader.js
  yarn.lock
Labels: android

#2677 Disable coin icons storage on Android
  src/components/coin-icon/CoinIcon.js
  src/components/coin-icon/CoinIconFallback.js
  src/components/token-family/TokenFamilyHeaderIcon.js
  src/utils/CoinIcons/CoinIcon.js
  src/utils/CoinIcons/CoinIcons.android.js
  src/utils/CoinIcons/CoinIcons.js
  src/utils/CoinIcons/FallbackIcon.js
  src/utils/index.ts
Labels: needs code review, QA later, android

#2637 Add initial memoization to colors utils
  src/styles/colors.js
  src/utils/memoFn.ts
Labels: QA later, android

#2664 send sheet keyboard handling and ui clean up
  src/components/send/SendAssetFormToken.js
  src/screens/SendSheet.js
Labels: needs code review, QA later, android

#2692 Chores
  package.json
  patches/react-native+0.66.1.patch
  yarn.lock
Labels: needs code review, QA later

#2596 Use new charts
  .eslintrc.js
  package.json
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.js
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/components/expanded-state/chart/chart-data-labels/useRatio.js
  src/components/value-chart/Chart.js
  src/components/value-chart/ExtremeLabels.js
  src/components/value-chart/TimespanSelector.js
  src/react-native-animated-charts/package.json
  src/react-native-animated-charts/src/charts/linear/ChartDot.js
  src/react-native-animated-charts/src/charts/linear/ChartDot.tsx
  src/react-native-animated-charts/src/charts/linear/ChartLabels.js
  src/react-native-animated-charts/src/charts/linear/ChartLabels.tsx
  src/react-native-animated-charts/src/charts/linear/ChartLines.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPath.js
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPathProvider.js
  src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
  src/react-native-animated-charts/src/helpers/ChartContext.js
  src/react-native-animated-charts/src/helpers/ChartContext.ts
  src/react-native-animated-charts/src/helpers/d3Interpolate.js
  src/react-native-animated-charts/src/helpers/requireOnWorklet.ts
  src/react-native-animated-charts/src/helpers/useChartData.js
  src/react-native-animated-charts/src/helpers/useChartData.ts
  src/react-native-animated-charts/src/helpers/withReanimatedFallback.js
  src/react-native-animated-charts/src/index.ts
  src/react-native-animated-charts/yarn.lock
  yarn.lock
Labels: needs QA, android

#2694 Fix eth icon on android after removing ReactCoinIcon
  src/components/coin-icon/CoinIconFallback.js
  src/components/images/ImageWithCachedMetadata.js
Labels: needs code review, QA later

#2697 @benisgold/memo helpers
  src/helpers/bigNumberFormat.js
  src/helpers/dappNameHandler.js
  src/helpers/emojiHandler.js
  src/helpers/gas.ts
  src/helpers/savings.js
  src/helpers/strings.js
  src/helpers/validators.js
Labels: needs code review, QA later, android

#2689 @benisgold/android UI fixes
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/components/expanded-state/unique-token/saveToCameraRoll.js
Labels: needs code review, QA later, android

#2695 eip1559 ios release fixes
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/GweiInputPill.js
  src/components/gas/GasSpeedButton.js
  src/hooks/useFeesPanelInputRefs.ts
Labels: release

#2679 Delay non trivial data load
  src/hooks/index.js
  src/hooks/useInitializeDiscoverData.js
  src/hooks/useInitializeWallet.js
  src/hooks/useLoadGlobalData.js
  src/hooks/useLoadGlobalEarlyData.js
  src/hooks/useLoadGlobalLateData.js
  src/hooks/useUniswapPools.js
  src/redux/userLists.ts
  src/screens/AddTokenSheet.js
  src/screens/WalletScreen.js
Labels: needs code review, QA later, android

#2700 Fix eth icon on android again
  src/assets/eth-icon.png
  src/components/coin-icon/CoinIconFallback.js
  src/components/images/ImageWithCachedMetadata.js
Labels: needs code review, QA later, android, merge when ready

#2711 Do not persist open small balances
  src/hooks/useInitializeWallet.js
  src/hooks/useOpenSmallBalances.js
Labels: needs code review, QA later, android, merge when ready

#2706 fix insufficient eth label bug
  src/hooks/useCurrentNonce.ts
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
Labels: needs code review, QA later

#2712 Link brief small balances to the brief balances selector
  src/helpers/buildWalletSections.js
  src/hooks/useInitializeAccountData.js
  src/screens/WalletScreen.js
Labels: needs code review, QA later, android

#2716 Remove useUniswapAssetsInWallet check in useAsset hook
  src/hooks/useAsset.js
Labels: QA later, android

#2705 Remove default balance title that was hiding wallet selector
  e2e/importPrivateKeyFlow.spec.js
  e2e/importPrivateKeyFlow0x.spec.js
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
Labels: android

#2718 Memo for BalanceCoinRow
  src/components/coin-row/BalanceCoinRow.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/hooks/charts/useChartData.js
Labels: android

#2710 Hide hidden coins
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
Labels: needs code review, QA later, android, merge when ready

#2704 fix send sheet focus handling
  src/components/fields/BubbleField.js
  src/components/send/SendAssetForm.js
  src/components/send/SendAssetFormField.js
  src/components/send/SendAssetFormToken.js
  src/hooks/index.js
  src/hooks/useSendSheetInputRefs.ts
  src/screens/SendSheet.js
Labels: QA later, android

#2719 smol android fixes
  src/components/coin-icon/CoinIconFallback.js
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/navigation/Routes.android.js
  src/redux/data.js
Labels: needs code review, QA later, android

#2720 Fix patch in @gorhom/bottom-sheet
  patches/@gorhom+bottom-sheet+4.1.5.patch
  src/components/discover-sheet/DiscoverSheet.android.js
Labels: blocker, QA later, android, merge when ready

#2709 Fix sticky headers
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
  src/components/asset-list/RecyclerAssetList2/core/StickyHeaders.tsx
  src/components/asset-list/RecyclerAssetList2/core/getLayoutProvider.tsx
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
  src/components/coin-divider/CoinDivider.js
Labels: needs code review, QA later, android, merge when ready

#2717 Don't initiate a new WalletConnect session using an existing URI
  src/redux/walletconnect.js
Labels: QA later, merge when ready

#2725 Fix pinning mode
  src/hooks/useCoinListEditOptions.ts
Labels: needs code review, blocker, QA later, android, merge when ready

#2724 Hide nfts' header if no nfts
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
Labels: needs code review, QA later, android

#2721 Disable focusing on input on navigating to Currency Selection View from Swap flow
  src/screens/CurrencySelectModal.js
Labels: needs code review, QA later, android, merge when ready

#2733 Fix crash on android release apk
  src/components/Tag.js
Labels: needs code review, blocker, QA later

#2735 Fix linting errors
  src/components/fields/BubbleField.js
  src/hooks/useInitializeWallet.js
  src/screens/CurrencySelectModal.js
  src/screens/SendSheet.js
Labels: needs code review, blocker, QA later

#2726 Rewrite CoinDividerOpenButton to reanimated v2
  src/components/coin-divider/CoinDivider.js
  src/components/coin-divider/CoinDividerOpenButton.js
  src/components/coin-row/CoinName.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/send/SendAssetList.js
Labels: needs code review, android, merge when ready

#2740 Remove red All/Less button background
  src/components/coin-divider/CoinDividerOpenButton.js
Labels: QA later, merge when ready

#2736 @bruno/fix darkmode sticky headers android
  src/components/list/ListHeader.js
Labels: needs code review, QA later, android

#2738 remove 'collectibles' header when wallet does not possess nfts
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
Labels: QA later, android, merge when ready

#2728 Fix nft expanded state blur overlay offset on android
  src/components/expanded-state/UniqueTokenExpandedState.js
Labels: needs code review, QA later, android, merge when ready

#2734 Revert "Disable focusing on input on navigating to Currency Selection…
  src/screens/CurrencySelectModal.js
Labels: needs code review, QA later, needs design review, android

#2714 fix display for network change requests
  src/screens/WalletConnectApprovalSheet.js
  src/utils/ethereumUtils.ts
Labels: needs code review, QA later, release

#2732 [RNBW-1877] move uniswap all tokens to dispersion
  src/apollo/queries.js
  src/components/coin-divider/CoinDividerOpenButton.js
  src/components/discover-sheet/DiscoverSearch.js
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/entities/index.ts
  src/entities/tokenSearch.ts
  src/handlers/dispersion.ts
  src/handlers/tokenSearch.ts
  src/handlers/uniswap.ts
  src/hooks/index.js
  src/hooks/useAdditionalAssetData.ts
  src/hooks/useInitializeWallet.js
  src/hooks/useUniswapAssets.ts
  src/hooks/useUniswapAssetsInWallet.js
  src/hooks/useUniswapCurrencyList.ts
  src/redux/uniswap.js
  src/screens/CurrencySelectModal.js
  src/utils/__tests__/search.test.ts
  src/utils/search.ts
  src/utils/uniswapAssetsCache.ts
Labels: needs code review, new feature, release

#2723 Asset Data Improvements
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/asset-list/RecyclerAssetList2/WrapperBalanceCoinRow.tsx
  src/components/coin-row/BalanceCoinRow.js
  src/components/discover-sheet/DiscoverSearch.js
  src/components/discover-sheet/ListsSection.js
  src/components/discover-sheet/TopMoversSection.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/expanded-state/unique-token/UnderlyingAsset.js
  src/components/investment-cards/UniswapPoolListRow.js
  src/components/send/SendAssetList.js
  src/handlers/localstorage/accountLocal.js
  src/helpers/assetSelectors.js
  src/helpers/assets.js
  src/helpers/buildWalletSections.js
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/hooks/index.js
  src/hooks/useAccountAsset.js
  src/hooks/useAccountAssets.js
  src/hooks/useAsset.js
  src/hooks/useCollectible.js
  src/hooks/useGas.ts
  src/hooks/useGenericAsset.js
  src/hooks/useIsWalletEthZero.js
  src/hooks/useSortedAccountAssets.js
  src/hooks/useSwapCurrencyHandlers.js
  src/hooks/useSwapInputHandlers.ts
  src/hooks/useSwapIsSufficientBalance.ts
  src/hooks/useUniswapAssetsInWallet.js
  src/hooks/useUpdateAssetOnchainBalance.js
  src/hooks/useWalletSectionsData.js
  src/model/migrations.ts
  src/parsers/accounts.js
  src/parsers/index.ts
  src/parsers/requests.js
  src/parsers/uniqueTokens.js
  src/redux/addCash.js
  src/redux/data.js
  src/redux/explorer.js
  src/redux/fallbackExplorer.js
  src/redux/gas.ts
  src/redux/optimismExplorer.js
  src/redux/uniqueTokens.js
  src/screens/ExpandedAssetSheet.js
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/utils/ethereumUtils.ts
Labels: needs code review, QA later, android

#2744 Reduce rerenders on ChartExpandedState + Fix crash
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/sheet/sheet-action-buttons/BuyActionButton.js
  src/components/sheet/sheet-action-buttons/SendActionButton.js
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
  src/hooks/useAsset.js
  src/hooks/useCollectible.js
  src/redux/optimismExplorer.js
  src/references/chain-assets.json
Labels: QA later, android

#2751 Fix crashing when switching wallets for first time
  src/redux/data.js
Labels: needs code review, QA later, android

#2753 Adjust provisioning profiles for widgets
  ios/Rainbow.xcodeproj/project.pbxproj
Labels: needs code review, blocker, merge when ready

#2741 Initial conversion of `src/handlers` to TypeScript.
  .gitignore
  src/handlers/__tests__/web3.test.ts
  src/handlers/aesEncryption.ts
  src/handlers/appEvents.ts
  src/handlers/assets.ts
  src/handlers/authentication.ts
  src/handlers/cloudBackup.ts
  src/handlers/covalent.ts
  src/handlers/deeplinks.ts
  src/handlers/ens.ts
  src/handlers/gasFees.ts
  src/handlers/imgix.ts
  src/handlers/localstorage/accountLocal.ts
  src/handlers/localstorage/common.ts
  src/handlers/localstorage/contacts.ts
  src/handlers/localstorage/globalSettings.ts
  src/handlers/localstorage/migrations.ts
  src/handlers/localstorage/removeWallet.ts
  src/handlers/localstorage/theme.ts
  src/handlers/localstorage/topMovers.ts
  src/handlers/localstorage/uniswap.ts
  src/handlers/localstorage/userLists.ts
  src/handlers/localstorage/walletBalances.ts
  src/handlers/localstorage/walletNames.ts
  src/handlers/localstorage/walletconnectRequests.ts
  src/handlers/localstorage/walletconnectSessions.ts
  src/handlers/opensea-api.ts
  src/handlers/svgs.ts
  src/handlers/transactions.ts
  src/handlers/uniswap.ts
  src/handlers/walletReadyEvents.ts
  src/handlers/wyre.ts
  src/model/migrations.ts
  src/utils/ethereumUtils.ts
Labels: needs code review, QA later

#2750 Rewrite AssetListItemSkeleton to reanimated v2
  src/components/asset-list/AssetListItemSkeleton.js
Labels: needs code review, QA later, android

#2688 Fix network switching issues with WC
  src/App.js
  src/components/walletconnect-list/WalletConnectListItem.js
  src/redux/walletconnect.js
  src/screens/SendSheet.js
Labels: QA later

#2759 update arbitrum gas prices
  src/redux/gas.ts
Labels: QA later

#2761 remove L2 no price filtering
  src/redux/data.js
Labels: QA later
