Repository rainbow-me/rainbow, pull requests merged in 2021-08, with the labels that each got.

#2291 Fix exchange modal gas estimations
  src/screens/ExchangeModal.js
Labels: needs QA

#2285 Fix WC + L2 bugs
  ios/Podfile.lock
  src/components/coin-icon/ChainBadge.js
  src/components/coin-icon/CoinIcon.js
  src/components/transaction-list/TransactionList.js
  src/components/transaction/sections/TransactionConfirmationSection.js
  src/helpers/dappNameHandler.js
  src/parsers/requests.js
  src/redux/requests.js
  src/screens/TransactionConfirmationScreen.js
  src/utils/ethereumUtils.js
Labels: needs QA

#2276 Don't fetch ENS if we have contact
  src/components/send/SendHeader.js
Labels: needs QA

#2296 Arbitrum not Abritrum
  src/redux/gas.js
Labels: blocker

#2271 Connected dapps network context menu
  src/components/walletconnect-list/WalletConnectListItem.js
Labels: needs QA

#2307 ENS autocomplete send sheet
  src/apollo/client.js
  src/apollo/queries.js
  src/components/change-wallet/AddressRow.js
  src/components/contacts/ContactRow.js
  src/components/expanded-state/ContactProfileState.js
  src/components/expanded-state/WalletProfileState.js
  src/components/send/SendContactList.js
  src/components/send/SendHeader.js
  src/components/showcase/ShowcaseHeader.js
  src/helpers/accountInfo.js
  src/model/migrations.js
  src/model/wallet.ts
  src/redux/wallets.js
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
  src/utils/index.js
  src/utils/profileUtils.ts
Labels: needs QA

#2247 Remove LP calls and use existing user positions data
  src/apollo/queries.js
  src/components/expanded-state/LiquidityPoolExpandedState.js
  src/components/sheet/sheet-action-buttons/DepositActionButton.js
  src/components/sheet/sheet-action-buttons/WithdrawActionButton.js
  src/handlers/localstorage/uniswap.js
  src/handlers/uniswapLiquidity.ts
  src/helpers/uniswapLiquidityTokenInfoSelector.js
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/hooks/index.js
  src/hooks/useEffectDebugger.js
  src/hooks/useLoadAccountData.js
  src/hooks/useRefreshAccountData.js
  src/hooks/useTotalFeeEarnedPerAsset.ts
  src/redux/data.js
  src/redux/uniswapLiquidity.js
  src/redux/usersPositions.ts
  src/screens/WalletScreen.js
Labels: needs review

#2308 Re-enable WC E2E
  e2e/config.json
  e2e/ganacheTransactionFlow.spec.js
  e2e/init.js
  package.json
  src/redux/walletconnect.js
  src/screens/TransactionConfirmationScreen.js
  yarn.lock
Labels: needs QA

#2328 Prevent discover search permanent rendering
  src/components/discover-sheet/DiscoverSheetContent.js
Labels: needs QA

#2326 Bump reanimated
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+2.1.0.patch
  patches/react-native-reanimated+2.3.0-alpha.2.patch
  yarn.lock
Labels: needs review, needs QA

#2335 @nico/sync send sheet contact info with wallet
  src/components/contacts/ImageAvatar.js
  src/screens/SendConfirmationSheet.js
Labels: needs QA

#2334 Hide L2 assets with price = 0
  src/redux/data.js
  src/redux/editOptions.js
Labels: needs review

#2343 EIP-681 support + Deeplinks e2e
  android/app/src/main/AndroidManifest.xml
  e2e/deeplinks.spec.js
  e2e/init.js
  ios/Rainbow/Info.plist
  package.json
  src/handlers/deeplinks.js
  src/hooks/useScanner.js
  src/screens/SendSheet.js
  src/screens/ShowcaseSheet.js
  src/utils/ethereumUtils.js
  yarn.lock
Labels: needs review
