Repository rainbow-me/rainbow, pull requests merged in 2022-12, with the labels that each got.

#4217 Fix backup sheet height on android
  src/screens/BackupSheet.js
Labels: android, team1, dev QA, pr-squash-1

#4443 feat: set up initial WC v2 pairing
  src/App.js
  src/config/experimental.ts
  src/handlers/deeplinks.ts
  src/hooks/useScanner.ts
  src/languages/_english.json
  src/languages/_french.json
  src/redux/walletconnect.ts
  src/utils/walletConnect.ts
Labels: dev QA

#4487 Cloud backup restore fix
  src/components/backup/AddFirstWalletStep.tsx
  src/components/backup/RestoreCloudStep.js
  src/screens/RestoreSheet.js
  src/screens/transaction-details/components/TransactionDetailsHashAndActionsSection.tsx
Labels: release
