Repository rainbow-me/rainbow, pull requests merged in 2022-07, with the labels that each got.

#3618 Restore image_thumbnail_url
  src/handlers/ens.ts
  src/parsers/uniqueTokens.js
Labels: needs dev review, QA later, team1

#3624 swaps - explainer updates
  e2e/hardhatTransactionFlow.spec.js
  src/components/exchange/ExchangeAssetList.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/CurrencySelectModal.js
  src/screens/ExchangeModal.js
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2

#3629 swaps: isHighPriceImpact debounce
  e2e/swapSheetFlow.spec.js
  src/components/exchange/ConfirmExchangeButton.js
  src/components/exchange/PriceImpactWarning.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3641 swaps: update output disabled explainer
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2

#3635 Swaps: Analytics
  src/hooks/useSwapDerivedOutputs.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3634 Profiles: Fix text line break in wait one minute ENS registration state
  src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
Labels: profiles, team2

#3640 asset: get asset from discover to swap
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
Labels: swap-aggregator, team2

#3638 swaps: more input flip & max
  src/components/exchange/ExchangeField.js
  src/components/exchange/ExchangeNativeField.js
  src/components/gas/GasSpeedLabelPager.js
  src/hooks/useSwapCurrencyHandlers.js
Labels: swap-aggregator, team2

#3644 swaps: fix matic fees
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
  src/hooks/useRainbowFee.js
Labels: swap-aggregator, team2

#3645 swaps: currency selection updates
  src/hooks/useSwapCurrencyHandlers.js
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator, team2

#3649 Swap fixes
  src/hooks/useSwapAdjustedAmounts.ts
  src/languages/_english.json
  src/references/index.ts
Labels: swap-aggregator, team2

#3654 [TEAM2-238] Pinned tokens in mainnet swap search
  src/hooks/useSwapCurrencyList.ts
Labels: swap-aggregator, team2

#3650 Profiles: fix .eth.eth issue
  src/handlers/ens.ts
Labels: profiles

#3631 swaps- liquidity explainer
  audit-ci.json
  e2e/hardhatTransactionFlow.spec.js
  e2e/swapSheetFlow.spec.js
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
  src/components/buttons/hold-to-authorize/types/HoldToAuthorizeBaseProps.ts
  src/components/exchange/ConfirmExchangeButton.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2

#3648 [TEAM2-230] Token Expanded sheet Swap entry point bugs
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
Labels: swap-aggregator, team2

#3653 Fix swap failures
  package.json
  src/handlers/uniswap.ts
  src/handlers/web3.ts
  src/raps/actions/swap.ts
  src/raps/common.ts
  src/raps/unlockAndSwap.ts
  src/references/ethereum-units.json
  src/screens/ExchangeModal.js
  yarn.lock
Labels: swap-aggregator

#3651 remove set primary name switch leak
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/ConfigurationSection.tsx
Labels: dev QA

#3643 Fix ESLint warnings introduced in EmojiSelector PR
  src/components/avatar-builder/EmojiSelector.tsx
Labels: needs dev review

#3394 Convert remaining Redux reducers to TypeScript.
  package.json
  src/components/backup/RestoreCloudStep.js
  src/entities/index.ts
  src/entities/tokens.ts
  src/handlers/covalent.ts
  src/handlers/localstorage/walletconnectSessions.ts
  src/handlers/walletReadyEvents.ts
  src/helpers/findWalletWithAccount.ts
  src/helpers/walletLoadingStates.ts
  src/hooks/useImportingWallet.js
  src/hooks/useWalletCloudBackup.js
  src/model/migrations.ts
  src/model/wallet.ts
  src/redux/additionalAssetsData.ts
  src/redux/charts.ts
  src/redux/data.ts
  src/redux/editOptions.js
  src/redux/editOptions.ts
  src/redux/explorer.js
  src/redux/explorer.ts
  src/redux/fallbackExplorer.ts
  src/redux/optimismExplorer.ts
  src/redux/reducers.ts
  src/redux/requests.ts
  src/redux/store.ts
  src/redux/topMovers.ts
  src/redux/uniswapLiquidity.ts
  src/redux/walletconnect.ts
  src/redux/wallets.ts
  src/screens/ChangeWalletSheet.js
  yarn.lock
Labels: team1

#3572 Add i18n tags for alerts.
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/settings-menu/DevSection.js
  src/handlers/deeplinks.ts
  src/handlers/fedora.ts
  src/hooks/useImportingWallet.js
  src/hooks/useInitializeWallet.js
  src/hooks/useManageCloudBackups.js
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/languages/_french.json
  src/model/wallet.ts
  src/screens/ENSAssignRecordsSheet.tsx
  src/utils/ethereumUtils.ts
  src/utils/reviewAlert.ts
  src/utils/watchingAlert.ts
Labels: needs dev review, team1, dev QA

#3670 Fix audit
  package.json
  yarn.lock
Labels: merge when ready

#3547 Optimize token family header
  src/components/asset-list/RecyclerAssetList2/WrappedTokenFamilyHeader.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/send/SendAssetList.js
  src/components/token-family/CollectibleTokenFamily.tsx
  src/components/token-family/TokenFamilyHeader.js
  src/components/token-family/TokenFamilyHeader.tsx
  src/components/token-family/TokenFamilyHeaderIcon.js
  src/components/token-family/TokenFamilyHeaderIcon.tsx
  src/components/token-family/TokenFamilyWrap.tsx
  src/hooks/index.js
  src/hooks/useLatestCallback.ts
  src/hooks/useOpenFamilies.ts
  src/screens/SendSheet.js
  src/screens/ShowcaseSheet.js
Labels: android, performance, team1

#3662 swaps: fix switching currency with max input
  src/components/exchange/ExchangeField.js
  src/components/exchange/ExchangeInputField.js
  src/hooks/useSwapSettings.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3489 Remove a few of Lodash's methods from the codebase
  src/components/Divider.js
  src/components/activity-list/LoadingState.js
  src/components/asset-list/EmptyAssetList.js
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/coin-row/TransactionStatusBadge.js
  src/components/discover-sheet/ListsSection.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/swap-details/SwapDetailsUniswapRow.js
  src/components/secret-display/SecretDisplayCard.js
  src/components/token-family/TokenFamilyWrap.tsx
  src/handlers/walletReadyEvents.ts
  src/helpers/assets.ts
  src/helpers/utilities.ts
  src/hooks/useAddCashLimits.js
  src/hooks/useSendableUniqueTokens.js
  src/hooks/useUniswapCalls.ts
  src/parsers/transactions.ts
  src/redux/data.ts
  src/redux/requests.ts
  src/redux/uniswapLiquidity.ts
  src/redux/wallets.ts
  src/utils/signingMethods.ts
Labels: performance, team1

#3676 swaps: fix press disabled confirm
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
Labels: swap-aggregator, team2, dev QA

#3351 Part of lodash replacement. Replace omit
  src/components/context-menu/ContextMenu.android.js
  src/components/context-menu/ContextMenu.ios.js
  src/handlers/localstorage/walletconnectSessions.ts
  src/helpers/time.ts
  src/helpers/utilities.ts
  src/hooks/useENSRegistrationForm.ts
  src/navigation/Routes.ios.js
  src/redux/contacts.ts
  src/redux/ensRegistration.ts
  src/redux/requests.ts
  src/redux/walletconnect.ts
  src/screens/TransactionConfirmationScreen.js
Labels: performance, team1

#3678 Fix NFT token family icon size
  src/components/token-family/TokenFamilyHeaderIcon.tsx
Labels: needs dev review, merge when ready, team1, dev QA

#3666 Profiles: poaps
  src/hooks/useFetchUniqueTokens.ts
Labels: profiles, team2

#3459 Notifications: Settings bottom sheet
  e2e/discoverSheetFlow.spec.js
  e2e/hardhatTransactionFlow.spec.js
  e2e/registerENSFlow.spec.js
  e2e/sendSheetFlow.spec.js
  e2e/swapSheetFlow.spec.js
  src/components/backup/BackupCloudStep.js
  src/components/backup/BackupConfirmPasswordStep.js
  src/components/list/List.js
  src/components/settings-menu/BackupSection/WalletSelectionView.js
  src/components/settings-menu/DevSection.js
  src/components/settings-menu/SettingsSection.js
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/onNavigationStateChange.js
  src/navigation/routesNames.js
  src/screens/BackupSheet.js
  src/screens/ProfileScreen.js
  src/screens/SettingsSheet.js
Labels: notifications, team2, dev QA

#3626 Fix intermittent loading image errors in NFT thumbnails
  patches/react-native-fast-image+8.5.11.patch
  src/components/images/ImgixImage.tsx
  src/components/unique-token/UniqueTokenImage.js
Labels: needs dev review

#3397 Replace FlyInAnimation Reanimated 1 code with Reanimated 2 layout animation and tweak search UX
  src/components/animations/FlyInAnimation.js
  src/components/fields/AddressField.js
  src/components/send/SendContactList.js
  src/components/send/SendEmptyState.js
  src/components/send/SendHeader.js
  src/screens/SendSheet.js
Labels: needs dev review, performance, team1, dev QA

#3679 Update TokenFamilyHeaderIcon.tsx
  src/components/token-family/TokenFamilyHeaderIcon.tsx
Labels: merge when ready, team1, dev QA

#3677 [TEAM2-229] Balances not invalidating after completed swap
  src/App.js
  src/raps/actions/swap.ts
  src/redux/additionalAssetsData.ts
  src/redux/data.ts
  src/references/ethereum-units.json
  src/screens/CurrencySelectModal.js
Labels: needs dev review, swap-aggregator, team2

#3657 Get shadows to display
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
Labels: needs dev review, merge when ready

#3421 FastCurrencySelectionRow
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/exchange/ExchangeAssetList.js
  src/components/exchange/exchangeAssetRowContextMenuProps.ts
  src/hooks/useAccountAsset.js
  src/hooks/useClipboard.js
Labels: performance, team1, dev QA

#3667 fix status bar flashes when closing modals
  src/App.js
  src/screens/WalletScreen.js
Labels: needs dev review, profiles, team2, dev QA

#3684 swaps - available networks balance check
  src/components/expanded-state/asset/ChartExpandedState.js
Labels: swap-aggregator, team2, dev QA

#3694 fix element padding
  src/components/transaction/TransactionMessage.js
Labels: team2

#3685 swaps - truncate long token symbols
  src/components/buttons/TokenSelectionButton.js
  src/components/exchange/ExchangeField.js
Labels: swap-aggregator, team2

#3690 Remove undocumented usage of WC request payload ID as timestamp
  src/parsers/requests.js
Labels: release

#3637 fix: GasSpeedLabelPager update deps to get correct accent color
  src/components/gas/GasSpeedLabelPager.js
Labels: nice for release, dev QA

#3688 Notifications: Feature flag
  src/config/experimental.ts
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/routesNames.js
  src/screens/ProfileScreen.js
  src/screens/SettingsSheetV2.tsx
Labels: notifications, team2, dev QA

#3608 [TEAM2-19] Wallet connect confirmation screen should use metadata service
  src/utils/methodRegistry.ts
Labels: needs dev review, release, team2

#3510 Remove lodash toLower from the codebase
  src/components/add-cash/AddCashStatus.js
  src/components/coin-row/TransactionCoinRow.js
  src/components/discover-sheet/ListsSection.js
  src/components/expanded-state/LiquidityPoolExpandedState.js
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/unique-token/UnderlyingAsset.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/send/SendContactList.js
  src/components/send/SendHeader.js
  src/components/settings-menu/NetworkSection.js
  src/components/transaction-list/TransactionList.js
  src/components/unique-token/UniqueTokenImage.js
  src/handlers/assets.ts
  src/handlers/deeplinks.ts
  src/handlers/localstorage/common.ts
  src/handlers/uniswap.ts
  src/handlers/wyre.ts
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/hooks/useDeleteWallet.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useSavingsAccount.js
  src/hooks/useTotalFeeEarnedPerAsset.ts
  src/hooks/useUniswapCalls.ts
  src/hooks/useUniswapPools.js
  src/hooks/useWallets.js
  src/model/migrations.ts
  src/parsers/transactions.ts
  src/parsers/uniqueTokens.js
  src/raps/actions/unlock.ts
  src/redux/addCash.ts
  src/redux/charts.ts
  src/redux/data.ts
  src/redux/fallbackExplorer.ts
  src/redux/optimismExplorer.ts
  src/redux/showcaseTokens.ts
  src/screens/AddTokenSheet.js
  src/screens/ChangeWalletSheet.js
  src/screens/CurrencySelectModal.js
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
  src/screens/WalletDiagnosticsSheet.js
  src/screens/WalletScreen.js
  src/styles/colors.ts
  src/utils/checkTokenIsScam.ts
  src/utils/ethereumUtils.ts
  src/utils/getTokenMetadata.ts
  src/utils/isETH.ts
  src/utils/isLowerCaseMatch.ts
Labels: performance, team1

#3707 Fix crash on double pressing add button
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/exchange/ExchangeAssetList.js
Labels: needs dev review, release, team1, dev QA

#3633 Fast UniswapPoolRow
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastPoolValue.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastUniswapPoolRow.tsx
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/expanded-state/unique-token/UnderlyingAsset.js
  src/redux/uniswapLiquidity.ts
Labels: needs design review, android, performance, team1

#3705 Changelog update and minor cleanup
  CHANGELOG.md
  src/helpers/validators.ts
  src/redux/explorer.ts
Labels: dev QA

#3700 [TEAM2-239] Sort swap currency list favorites alphabetically
  src/hooks/useSwapCurrencyList.ts
Labels: swap-aggregator, team2, dev QA

#3683 Allow undefined in pickShallow
  src/helpers/utilities.ts
Labels: needs dev review, team1, dev QA

#3661 Item layout in transaction list
  package.json
  src/components/activity-list/ActivityList.js
  src/components/coin-row/TransactionCoinRow.js
  src/helpers/buildTransactionsSectionsSelector.ts
  yarn.lock
Labels: needs dev review, performance, team1, dev QA

#3289 Remove BigNumbers.js
  e2e/config.json
  e2e/init.js
  ios/Podfile.lock
  package.json
  patches/@ethersproject+bignumber+5.6.2.patch
  patches/react-native-bignumber+0.1.5.patch
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/savings/SavingsListRow.js
  src/components/transaction/sections/TransactionConfirmationSection.js
  src/entities/gas.ts
  src/entities/tokens.ts
  src/entities/transactions/transaction.ts
  src/handlers/ens.ts
  src/handlers/web3.ts
  src/helpers/__tests__/utilities.test.ts
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
  src/helpers/ens.ts
  src/helpers/numbers.ts
  src/helpers/savings.ts
  src/helpers/time.ts
  src/helpers/utilities.ts
  src/hooks/useAdditionalAssetData.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/usePriceImpactDetails.ts
  src/hooks/useSavingsAccount.js
  src/hooks/useSwapAdjustedAmounts.ts
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapInputHandlers.ts
  src/parsers/accounts.js
  src/parsers/gas.ts
  src/parsers/newTransaction.ts
  src/parsers/requests.js
  src/parsers/transactions.ts
  src/parsers/uniqueTokens.js
  src/raps/swapAndDepositCompound.ts
  src/raps/unlockAndSwap.ts
  src/redux/data.ts
  src/redux/gas.ts
  src/redux/multicall.ts
  src/screens/SpeedUpAndCancelSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/utils/numbers.ts
  yarn.lock
Labels: performance, team1

#3719 Don't pass source=rainbow to the backend
  src/hooks/useSwapDerivedOutputs.ts
Labels: needs dev review, merge when ready, swap-aggregator, team2, dev QA

#3718 swaps: android currency select modal footer spacing
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator, team2

#3716 Set custom depth of the scroll view in Exchange modal in RNCM
  src/navigation/Routes.ios.js
  src/react-native-cool-modals/NativeStackView.js
  src/react-native-cool-modals/ios/RNCMScreen.h
  src/react-native-cool-modals/ios/RNCMScreen.m
  src/react-native-cool-modals/ios/UIViewController+slack.swift
Labels: needs dev review, merge when ready, swap-aggregator, team2, dev QA

#3611 updating polygon allowlist
  src/references/polygon-allowlist.json
Labels: nice for release, team2, dev QA

#3709 Fix shadow in the expanded state
  src/components/coin-icon/CoinIconFallback.js
Labels: needs dev review, release, team1, dev QA

#3724 fix: use colors from theme for favStar
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
Labels: release

#3723 fix polygon OS images
  src/parsers/uniqueTokens.js
Labels: release, team2

#3722 fix remaining l2 color/icon issues
  src/screens/AddTokenSheet.js
  src/screens/SendConfirmationSheet.js
Labels: release

#3721 swaps: savings flow e2e
  e2e/hardhatTransactionFlow.spec.js
  src/components/savings/SavingsListHeader.js
  src/components/savings/SavingsListRow.js
  src/screens/DepositModal.js
  src/screens/SavingsSheet.js
  src/screens/WithdrawModal.js
Labels: swap-aggregator, team2

#3726 swaps: fix fast currency select row
  audit-ci.json
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/exchange/ExchangeAssetList.js
Labels: swap-aggregator, team2

#3728 Filter dropped txs
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  src/helpers/buildTransactionsSectionsSelector.ts
Labels: merge when ready, swap-aggregator, team2, dev QA

#3655 Fix navigating to the wrong screen while importing on Android
  ios/Podfile.lock
  package.json
  patches/@react-native-community+viewpager+5.0.5.patch
  patches/react-native-pager-view+5.4.24.patch
  src/navigation/ScrollPagerWrapper.js
  src/navigation/ViewPagerAdapter.js
  yarn.lock
Labels: needs dev review, fedora won't work

#3725 fix l2 txs
  src/redux/data.ts
Labels: team2, dev QA

#3738 fix: empty input flipping behavior
  src/hooks/useSwapCurrencyHandlers.js
Labels: swap-aggregator, team2, dev QA

#3741 swaps: exchange icons memos + error reset
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
Labels: swap-aggregator, team2

#3730 swaps: osdnk review
  hardhat.config.js
  src/assets/exchanges/zerox.png
  src/components/expanded-state/SwapDetailsState.js
  src/hooks/useSwapCurrencyHandlers.js
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator, team2

#3745 swaps: fix flashbots tip
  src/redux/gas.ts
  src/utils/gas.ts
Labels: swap-aggregator, team2, dev QA

#3743 Decrement nonce if flashbots txs is dropped
  ios/TransactionListViewCell.swift
  src/entities/transactions/transactionStatus.ts
  src/entities/transactions/transactionType.ts
  src/redux/data.ts
Labels: needs dev review, swap-aggregator

#3736 Failed L2 swaps don't display Failed transaction activity state
  src/redux/data.ts
Labels: critical path, swap-aggregator, team2

#3753 [TEAM2-267] WETH not appearing on search
  src/redux/uniswap.ts
Labels: needs dev review, swap-aggregator, team2, dev QA

#3752 disable swap button after pressed once
  src/components/exchange/ConfirmExchangeButton.js
Labels: swap-aggregator, team2

#3756 swaps: remote slippage by network
  src/model/config.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3755 swaps: fix gas loading state
  src/components/exchange/ConfirmExchangeButton.js
  src/hooks/useGas.ts
Labels: swap-aggregator, team2

#3754 swaps: add loading check to confirm button
  src/components/exchange/ConfirmExchangeButton.js
Labels: swap-aggregator, team2

#3757 fix: bump swap with permit gas
  package.json
  src/handlers/uniswap.ts
  src/references/ethereum-units.json
  yarn.lock
Labels: swap-aggregator, team2

#3759 Swaps: Fix select currency scroll on Android
  src/components/exchange/ExchangeAssetList.js
  src/hooks/index.js
  src/hooks/useAndroidScrollViewGestureHandler.ts
Labels: swap-aggregator, team2

#3762 input fix
  src/components/exchange/ExchangeInput.js
Labels: swap-aggregator, team2

#3766 swaps: fix 0. value in inputs behavior
  src/hooks/useSwapDerivedOutputs.ts
Labels: swap-aggregator, team2

#3768 Fix weird swap sheet clipping on Android
  src/components/exchange/ExchangeNotch.js
  src/screens/ExchangeModal.js
Labels: needs dev review, android, swap-aggregator, dev QA

#3767 swaps: check slippage remote config
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3771 fix: slippage selection color android
  src/components/expanded-state/swap-settings/InputPill.js
Labels: swap-aggregator, team2

#3769 swaps: block flashbots swaps miner tip
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/expanded-state/custom-gas/FeesPanel.js
  src/components/expanded-state/custom-gas/GweiInputPill.js
  src/components/gas/GasSpeedButton.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3773 swaps: fix slippage reset
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3779 swaps: use tradeDetails?.defaultGasLimit as default
  audit-ci.json
  package.json
  src/handlers/uniswap.ts
  yarn.lock
Labels: swap-aggregator

#3784 Optimism and Arbitrum NFT support
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/unique-token/Tag.js
  src/components/unique-token/UniqueTokenAttributes.tsx
  src/entities/uniqueAssets.ts
  src/handlers/ens.ts
  src/handlers/simplehash.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/useUntrustedUrlOpener.ts
  src/parsers/index.ts
  src/parsers/uniqueTokens.js
  src/redux/uniqueTokens.ts
Labels: team2

#3782 Swaps: Submitting button state
  audit-ci.json
  src/components/exchange/ConfirmExchangeButton.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3789 swaps: fix conditional to use fast speed
  audit-ci.json
  src/raps/actions/swap.ts
Labels: swap-aggregator, team2

#3790 [TEAM2-285] Wallet pull to refresh is getting stuck
  src/components/asset-list/RecyclerAssetList2/core/RefreshControl.tsx
Labels: needs dev review, team2, dev QA

#3776 Fix animated authorize button
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
Labels: needs dev review, team1, dev QA

#3498 Remove a bunch of lodash methods
  src/components/coin-row/SendCoinRow.js
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/floating-emojis/FloatingEmojis.js
  src/components/gas/GasSpeedEmoji.js
  src/design-system/components/Box/Box.tsx
  src/handlers/localstorage/removeWallet.ts
  src/handlers/wyre.ts
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/helpers/utilities.ts
  src/hooks/useSavingsAccount.js
  src/model/migrations.ts
  src/parsers/transactions.ts
  src/parsers/uniqueTokens.js
  src/raps/common.ts
  src/raps/registerENS.ts
  src/raps/swapAndDepositCompound.ts
  src/raps/unlockAndSwap.ts
  src/redux/showcaseTokens.ts
  src/redux/uniqueTokens.ts
  src/redux/uniswap.ts
  src/redux/uniswapLiquidity.ts
  src/redux/userLists.ts
  src/utils/signingMethods.ts
Labels: needs dev review, performance, team1

#3770 [TEAM2-18] Polygon custom gas choice in speed up tries to use EIP1559 and crashes
  src/screens/SpeedUpAndCancelSheet.js
Labels: needs dev review, team2, dev QA

#3742 [Code Re-Org] Setting up `prettier` for fun and profit
  .prettierrc.js
  package.json
  src/design-system/docs/.playroom/FrameComponent.js
  src/design-system/docs/.playroom/components.ts
  src/react-native-animated-charts/Example/babel.config.js
  src/react-native-animated-charts/Example/src/GenericExample/index.js
Labels: team1

#3802 Patch ios context menu lib to allow moving context menu to left or right
  ios/Podfile.lock
  patches/react-native-ios-context-menu+1.7.4.patch
  src/components/settings-menu/SettingsSection.tsx
Labels: team2, dev QA

#3787 Fix displaying currency symbols that appear after amount
  src/components/coin-row/SendCoinRow.js
Labels: team1, dev QA

#3777 Fix wrong line breaking in fee estimation
  src/components/gas/GasSpeedButton.js
Labels: android, team1

#3815 Fix swaps e2e again
  src/handlers/uniswap.ts
Labels: needs dev review, merge when ready, swap-aggregator, team2

#3810 swaps: dont round max
  src/hooks/useSwapDerivedOutputs.ts
Labels: release, swap-aggregator, team2

#3811 swaps: inputs PRs
  src/components/exchange/ExchangeField.js
  src/components/exchange/ExchangeInputField.js
  src/components/exchange/ExchangeNativeField.js
  src/components/exchange/ExchangeOutputField.js
  src/components/exchange/PriceImpactWarning.js
  src/handlers/uniswap.ts
  src/hooks/useSwapCurrencyHandlers.js
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapSettings.ts
  src/redux/swap.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3812 Fix swaps for testflight
  package.json
  src/hooks/useSwapDerivedOutputs.ts
  yarn.lock
Labels: merge when ready, swap-aggregator, team2, dev QA

#3814 swaps: use native display value for swap details
  src/components/expanded-state/swap-details/CurrencyTile.js
Labels: swap-aggregator, team2

#3813 [TEAM2-292] Fix Sentry Bugs
  src/hooks/useSwapCurrencyList.ts
  src/redux/data.ts
  src/utils/ethereumUtils.ts
Labels: merge when ready, swap-aggregator, team2, dev QA

#3816 swaps: fix l2 imported assets
  src/hooks/useSwapCurrencyList.ts
Labels: swap-aggregator, team2

#3817 [TEAM2-298] Fix favoriting
  src/components/exchange/ExchangeAssetList.js
Labels: needs dev review, swap-aggregator, team2, dev QA

#3818 swaps: team2-293
  src/components/exchange/ConfirmExchangeButton.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3819 swaps: android fix confirm button submitting state
  src/components/exchange/ConfirmExchangeButton.js
Labels: swap-aggregator, team2

#3785 Fix layout of change sheet when keyboard is dismissed
  src/components/send/SendAssetForm.js
Labels: android, team1

#3824 Move MMKV instances to the global scope
  src/components/settings-menu/AppIconSection.js
  src/featuresToUnlock/optimismNftAppIconCheck.ts
Labels: needs dev review, merge when ready, team1, dev QA

#3822 Update bottom padding on wallet screen
  src/components/asset-list/RecyclerAssetList2/core/ExternalScrollView.tsx
Labels: needs dev review, team1, dev QA

#3823 Scale for `Other amount` and `Copy address` buttons
  src/components/AddFundsInterstitial.js
Labels: needs dev review, team1, dev QA

#3734 add xtra deets to wc analytics
  src/redux/walletconnect.ts
  src/screens/TransactionConfirmationScreen.js
Labels: analytics, team2

#3828 swaps: input clearing + loading state
  e2e/swapSheetFlow.spec.js
  src/components/exchange/ConfirmExchangeButton.js
  src/hooks/useSwapDerivedOutputs.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3832 [TEAM2-303] Fix unguarded string manip again
  src/components/transaction-list/TransactionList.js
Labels: swap-aggregator, team2

#3833 Fix mmkv usage
  src/components/settings-menu/AppIconSection.js
  src/featuresToUnlock/optimismNftAppIconCheck.ts
Labels: merge when ready, swap-aggregator, team2

#3830 [RNBW-4059] swaps: fix arbitrum flipping
  src/hooks/useSwapCurrencyHandlers.js
  src/redux/swap.ts
Labels: swap-aggregator, team2

#3821 Emoji cutting on android
  src/screens/ExplainSheet.js
Labels: needs dev review, team1, dev QA

#3827 Center avatar emoji on Android
  src/components/profile/AvatarCircle.js
Labels: android, team1

#3837 fix: review coin icon
  src/components/expanded-state/swap-details/CurrencyTile.js
Labels: swap-aggregator, team2, dev QA

#3839 swap: bump gas estimation padding
  src/handlers/uniswap.ts
Labels: swap-aggregator, team2, dev QA

#3835 swaps: fix currency row truncating
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
Labels: release, swap-aggregator, team2

#3844 swaps: use flashbots miner tip when speeding up or cancelling
  src/screens/SpeedUpAndCancelSheet.js
Labels: swap-aggregator, team2

#3836 swaps: ignore threshold
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
Labels: swap-aggregator, team2

#3846 swaps: handle flashbot miner tip from review sheet
  src/components/expanded-state/SwapDetailsState.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3857 Fix center avatar emoji
  src/components/profile/AvatarCircle.js
Labels: android, team1

#3854 Restrict app resizing for android
  android/app/src/main/AndroidManifest.xml
Labels: needs dev review, android, team1, dev QA

#3851 [TEAM2-321] Audio Player Color Crash
  src/components/audio/AudioPlayer.js
Labels: team2, dev QA

#3850 swaps: disable source picker on arbis
  src/components/expanded-state/swap-settings/SwapSettingsState.js
Labels: swap-aggregator, team2, dev QA

#3852 [TEAM2-322] Do Not Pass NaN into Segment Analytics
  src/hooks/useSwapDerivedOutputs.ts
  src/performance/tracking/index.ts
  src/screens/ExchangeModal.js
  src/screens/WalletConnectApprovalSheet.js
Labels: team2, dev QA

#3855 Fix unnecessary line break in 'Other amount'
  src/components/AddFundsInterstitial.js
Labels: android, team1, dev QA

#3856 Fix linebreak in 'Owner'
  src/components/expanded-state/ens/InfoRow.tsx
Labels: android, team1

#3786 Make sick haptic feedback on Android
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/java/me/rainbow/NativeModules/Haptics/RNHapticsPackage.java
  android/app/src/main/java/me/rainbow/NativeModules/Haptics/RNHapticsPerformer.java
  android/app/src/main/java/me/rainbow/NativeModules/Haptics/RNRainbowHapticsModule.java
  package.json
  patches/react-native-haptic-feedback+1.11.0.patch
  src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.tsx
  src/components/expanded-state/custom-gas/FeesGweiInput.js
  src/components/value-chart/Chart.js
Labels: needs dev review, android, team1

#3829 Initial work to replace full-screen menus on Android with Popup menu
  package.json
  patches/@react-native-menu+menu+0.5.2.patch
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/exchange/exchangeAssetRowContextMenuProps.ts
  src/components/native-context-menu/contextMenu.android.js
  src/components/native-context-menu/contextMenu.js
  src/navigation/onNavigationStateChange.js
  yarn.lock
Labels: needs dev review, android, team1, dev QA

#3382 Optimize Android transaction coin row
  src/components/activity-list/ActivityList.js
  src/components/activity-list/ActivityListHeader.js
  src/components/activity-list/ActivityListHeader.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/components/coin-row/FastTransactionStatusBadge.tsx
  src/components/coin-row/index.js
  src/helpers/buildTransactionsSectionsSelector.tsx
  src/helpers/isNativeTransactionListAvailable.ts
  src/helpers/transactionPressHandler.ts
  src/hooks/useAccountTransactions.ts
  src/screens/ProfileScreen.js
Labels: android, performance, team1

#3869 Fix audit
  package.json
  yarn.lock
Labels: merge when ready, dev QA

#3868 Increase polling interval to 5 sec
  src/hooks/useSwapDerivedOutputs.ts
Labels: merge when ready, swap-aggregator, team2, dev QA
