Repository rainbow-me/rainbow, pull requests merged in 2022-08, with the labels that each got.

#3831 Avatar menu
  src/components/native-context-menu/contextMenu.android.js
  src/components/profile/AvatarCircle.js
  src/components/profile/ProfileMasthead.js
  src/hooks/useOnAvatarPress.ts
Labels: needs dev review, android, team1, dev QA

#3858 Fix seed import shadow glitch
  src/components/buttons/MiniButton.js
Labels: android, merge when ready, team1

#3807 Add a shadow to Get a new wallet in Onboarding flow
  src/screens/WelcomeScreen.tsx
Labels: needs dev review, android, team1, dev QA

#3842 Context menu on Expanded state
  patches/@react-native-menu+menu+0.5.2.patch
  src/components/context-menu/ContextCircleButton.android.js
  src/components/expanded-state/chart/ChartContextButton.js
Labels: needs dev review, android, merge when ready, team1, dev QA

#3825 Add ellipsis to Defi Pulse
  src/components/discover-sheet/PulseIndexSection.js
Labels: android, merge when ready, team1

#3873 Hide + button in pool expanded state
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
Labels: team1, dev QA

#3876 Fix L2 transaction icons
  src/components/coin-row/FastTransactionCoinRow.tsx
Labels: android, merge when ready, team1, dev QA

#3820 add yarn android-all commands
  package.json
Labels: needs dev review, android, merge when ready, team1, dev QA

#3801 Underlying asset shadow
  src/components/asset-list/AssetListItemSkeleton.js
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/unique-token/UnderlyingAsset.js
Labels: needs dev review, team1, dev QA

#3885 Disable selecting text in SVG NFTs
  src/components/svg/SvgImage.js
Labels: android, merge when ready, team1, dev QA

#3875 Add context menu for android transactions
  ios/Podfile.lock
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/helpers/buildTransactionsSectionsSelector.tsx
  src/helpers/transactionPressHandler.ts
  src/hooks/useAccountTransactions.ts
Labels: android, team1

#3881 Fix line break in get token button
  src/components/sheet/sheet-action-buttons/SheetActionButton.js
Labels: android, team1

#3877 Escape slack msg with "quotes" or other symbols like +
  .github/workflows/macstadium-e2e.yml
Labels: needs dev review, merge when ready, dev QA

#3389 Profiles: ENS Send Flow
  e2e/registerENSFlow.spec.js
  src/components/callout/Callout.tsx
  src/components/coin-row/CollectiblesSendRow.tsx
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/fields/CheckboxField.tsx
  src/components/icons/svg/ENSCircleIcon.tsx
  src/components/send/SendButton.js
  src/design-system/color/palettes.ts
  src/entities/ens.ts
  src/handlers/ens.ts
  src/handlers/web3.ts
  src/helpers/ens.ts
  src/hooks/useENSAddress.ts
  src/hooks/useENSCover.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSRecords.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/languages/_english.json
  src/navigation/config.js
  src/raps/actions/ens.ts
  src/raps/common.ts
  src/raps/registerENS.ts
  src/references/ens/ENSPublicResolver.json
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/ExplainSheet.js
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
Labels: profiles, team2

#3537 Profiles: New discover cards
  e2e/discoverSheetFlow.spec.js
  e2e/registerENSFlow.spec.js
  src/assets/discover-profiles-card.png
  src/assets/discover-profiles-card@2x.png
  src/assets/discover-profiles-card@3x.png
  src/components/asset-list/RecyclerAssetList2/WrappedTokenFamilyHeader.tsx
  src/components/discover-sheet/DPICard.tsx
  src/components/discover-sheet/DiscoverHome.js
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/components/discover-sheet/ENSCreateProfileCard.tsx
  src/components/discover-sheet/ENSSearchCard.tsx
  src/components/discover-sheet/GasCard.tsx
  src/components/discover-sheet/PulseIndexSection.js
  src/components/discover-sheet/RegisterENSSection.tsx
  src/components/discover-sheet/TopMoversSection.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/fab/SearchFab.js
  src/components/fab/index.js
  src/design-system/color/palettes.ts
  src/design-system/layout/shadow.ts
  src/design-system/typography/typeHierarchy.ts
  src/helpers/ens.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/RegisterENSNavigator.tsx
  src/screens/QRScannerScreen.js
  src/styles/colors.ts
Labels: profiles, team2

#3565 Profiles: Checkpoint 2
  src/apollo/queries.ts
  src/components/discover-sheet/ENSCreateProfileCard.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/handlers/ens.ts
  src/handlers/localstorage/ens.ts
  src/helpers/ens.ts
  src/hooks/index.ts
  src/hooks/useAccountENSDomains.ts
  src/hooks/useENSFirstTransactionTimestamp.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useFetchUniqueTokens.ts
  src/hooks/useFirstTransactionTimestamp.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useSelectImageMenu.tsx
  src/hooks/useWalletSectionsData.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSIntroSheet.tsx
  src/screens/ProfileSheet.tsx
  src/screens/SelectENSSheet.tsx
Labels: profiles, checkpoint, team2

#3890 Profiles: dynamic sizing of confirm update sheet
  src/components/ens-registration/ConfirmContent/EditContent.tsx
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles, team2

#3744 Add images to iOS notifications
  ios/ImageNotification/Info.plist
  ios/ImageNotification/NotificationService.h
  ios/ImageNotification/NotificationService.m
  ios/Podfile
  ios/Podfile.lock
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/fastlane/Fastfile
Labels: dev QA

#3894 Profiles: remove videos from nft selection
  src/hooks/useWalletSectionsData.ts
  src/screens/SelectUniqueTokenSheet.tsx
Labels: profiles, team2

#3879 Fix avatar placement in picker
  src/navigation/effects.js
  src/screens/AvatarBuilder.js
Labels: android, team1

#3886 Short Search Ethereum copy
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/languages/_english.json
  src/languages/_french.json
Labels: needs dev review, needs design review, android, merge when ready, team1, dev QA

#3680 Fix issue when after creating a wallet, the app is showing the onboarding screen for a while without any loading indicator
  patches/@react-navigation+routers+5.4.12.patch
  src/hooks/useImportingWallet.ts
  src/model/wallet.ts
  src/navigation/useRemoveFirst.js
Labels: merge when ready, team1, dev QA

#3887 Fix AddFundsInterstitials on narrow phones
  src/components/AddFundsInterstitial.js
  src/utils/deviceUtils.ts
Labels: needs dev review, android, merge when ready, team1, dev QA

#3891 improve approve+swap gas estimation algo
  src/handlers/uniswap.ts
Labels: merge when ready, swap-aggregator, team2, dev QA

#3893 Bump gas estimation padding for swaps
  src/handlers/uniswap.ts
Labels: needs dev review, swap-aggregator, team2

#3905 Profiles: My ENS Names sheet fixes
  src/screens/SelectENSSheet.tsx
Labels: profiles, team2

#3895 Profiles: Unable to swipe down on Profile Sheet on Android
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/hooks/useAndroidScrollViewGestureHandler.ts
Labels: profiles, team2, dev QA

#3907 Reorder search groups to highlight profiles
  src/components/discover-sheet/DiscoverSearch.js
Labels: needs dev review, release, profiles, team2, dev QA

#3900 Profiles: Fix ENS expanded state zoomable cover photo
  src/components/images/ImagePreviewOverlay.tsx
Labels: profiles, team2, dev QA

#3910 profiles: resize + sign cover photo
  src/components/ens-profile/ProfileSheetHeader.tsx
Labels: profiles, team2

#3911 profiles: fix sendable nft preview
  src/components/send/SendAssetForm.js
Labels: profiles, team2

#3913 Profiles: Fix for Android Discover shadows & Max button in send input
  src/components/buttons/MiniButton.js
  src/components/discover-sheet/DPICard.tsx
  src/components/discover-sheet/DiscoverHome.js
  src/components/discover-sheet/ENSCreateProfileCard.tsx
  src/components/discover-sheet/ENSSearchCard.tsx
  src/components/discover-sheet/GasCard.tsx
  src/components/discover-sheet/ListsSection.js
Labels: needs dev review, blocker, android, profiles, team2, dev QA

#3888 Center search icon on android discover
  src/components/discover-sheet/DiscoverSearchInput.js
Labels: android, merge when ready, team1, dev QA

#3878 More menu transitions
  src/components/context-menu/ContextCircleButton.android.js
  src/components/exchange/exchangeAssetRowContextMenuProps.ts
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/gas/GasSpeedButton.js
  src/components/gas/GasSpeedEmoji.js
  src/components/native-context-menu/contextMenu.android.js
  src/components/native-context-menu/contextMenu.js
  src/components/profile/AvatarCircle.js
  src/components/unique-token/Tag.js
  src/utils/gas.ts
Labels: android, merge when ready, team1, dev QA

#3871 Fix Send flow contact issues
  src/components/fields/AddressField.js
  src/components/send/SendHeader.js
  src/helpers/validators.ts
  src/screens/SendSheet.js
Labels: profiles, team2

#3914 Profiles: Fix undefined ENS NFT after registering an ENS
  src/helpers/assets.ts
  src/hooks/useCollectible.ts
  src/hooks/useFetchUniqueTokens.ts
  src/redux/uniqueTokens.ts
Labels: profiles, team2, profiles: needs qa

#3915 Profiles: Fix ENS owner caching issue
  src/apollo/client.ts
Labels: profiles, team2

#3924 Profiles: fix android crash when switching wallets
  src/hooks/useImportingWallet.ts
Labels: profiles, team2

#3904 Profiles: Text records validation fixes
  src/helpers/ens.ts
  src/hooks/useENSRegistrationForm.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: profiles, team2, dev QA

#3925 profiles: turn off search -> renable interactions
  src/components/ens-profile/ActionButtons/MoreButton.tsx
Labels: profiles, team2, dev QA

#3926 Fix keyboard not dismissing when registering ENS
  src/hooks/useENSPendingRegistrations.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: needs dev review, blocker, profiles, team2, dev QA

#3896 Profiles: Fix ENS expanded state edit button
  e2e/registerENSFlow.spec.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/navigation/RegisterENSNavigator.tsx
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles, team2, dev QA

#3922 Revert to emoji shuffle on Android
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: android, team1, dev QA

#3884 Convert menu in switch wallet to the new context menu
  src/components/change-wallet/AddressRow.js
  src/components/change-wallet/WalletList.js
  src/screens/ChangeWalletSheet.js
Labels: android, team1

#3921 Fix send sheet layout
  src/components/send/SendAssetForm.js
Labels: android, team1, dev QA

#3942 Fix context menu post prop rename
  src/components/change-wallet/AddressRow.js
  src/components/coin-row/FastTransactionCoinRow.tsx
Labels: blocker, android, profiles, team1, dev QA

#3898 profiles: speedup registration improvements
  e2e/registerENSFlow.spec.js
  src/components/ens-registration/ConfirmContent/WaitCommitmentConfirmationContent.tsx
  src/entities/transactions/transaction.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationStepHandler.tsx
  src/parsers/newTransaction.ts
  src/raps/actions/ens.ts
  src/redux/ensRegistration.ts
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/SpeedUpAndCancelSheet.js
Labels: profiles, team2

#3659 [TEAM1-47] Hidden NFTs
  e2e/hiddenTokensFlow.spec.js
  src/assets/sf-eye.slash.png
  src/assets/sf-eye.slash@2x.png
  src/assets/sf-eye.slash@3x.png
  src/components/asset-list/RecyclerAssetList2/WrappedTokenFamilyHeader.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/token-family/TokenFamilyHeader.tsx
  src/components/token-family/TokenFamilyHeaderIcon.tsx
  src/components/unique-token/UniqueTokenImage.js
  src/entities/uniqueAssets.ts
  src/handlers/ens.ts
  src/handlers/localstorage/accountLocal.ts
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
  src/hooks/index.ts
  src/hooks/useHiddenTokens.ts
  src/hooks/useLoadAccountData.ts
  src/hooks/useWalletSectionsData.ts
  src/hooks/useWebData.ts
  src/languages/_english.json
  src/languages/_french.json
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/redux/hiddenTokens.ts
  src/redux/reducers.ts
Labels: team1, dev QA

#3933 Fix URL wrapping
  src/hooks/useENSRecordDisplayProperties.tsx
Labels: profiles

#3934 Better menu for ENS records
  src/hooks/useENSRecordDisplayProperties.tsx
Labels: profiles

#3936 Better menu for 'choose NFT'
  src/screens/ENSIntroSheet.tsx
Labels: profiles, team2, dev QA

#3940 Add the most important wallet
  src/references/ens-intro-marquee-names.json
Labels: profiles, team2, dev QA

#3929 Profiles: Make cover NFTs open NFT expanded state
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/hooks/useENSRecordDisplayProperties.tsx
  src/utils/ens.ts
Labels: profiles, team2, dev QA

#3935 'More' button menu for android
  src/components/ens-profile/ActionButtons/MoreButton.tsx
Labels: profiles, team2, dev QA

#3897 Profiles: Profile avatar options
  e2e/walletAvatarOptions.spec.js
  src/hooks/useOnAvatarPress.ts
  src/screens/AvatarBuilder.js
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ProfileSheet.tsx
Labels: profiles, team2

#3946 profiles: fix da colors
  src/navigation/RegisterENSNavigator.tsx
Labels: profiles, team2, dev QA

#3938 Fix marquee list with avatars
  src/components/discover-sheet/TopMoversSection.js
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/components/list/MarqueeList.js
Labels: profiles, team2, dev QA

#3901 Do not use alerts for simple messages
  src/components/alerts/BaseAlert.js
  src/components/backup/RestoreCloudStep.js
  src/components/expanded-state/unique-token/saveToCameraRoll.js
  src/components/inputs/InlineField.tsx
  src/components/settings-menu/DevSection.js
  src/handlers/deeplinks.ts
  src/handlers/fedora.ts
  src/helpers/alert.ts
  src/hooks/useImportingWallet.ts
  src/hooks/useInitializeWallet.ts
  src/hooks/useManageCloudBackups.ts
  src/hooks/useWalletCloudBackup.ts
  src/model/wallet.ts
  src/redux/walletconnect.ts
  src/screens/ExchangeModal.js
  src/screens/PinAuthenticationScreen.js
  src/screens/RestoreSheet.js
  src/screens/SendSheet.js
  src/screens/SpeedUpAndCancelSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/screens/WalletDiagnosticsSheet.js
  src/utils/ethereumUtils.ts
  src/utils/reviewAlert.ts
  src/utils/watchingAlert.ts
Labels: needs dev review, android, merge when ready, team1, dev QA

#3931 Enable back button if the pin is prompted but not during creation
  src/hooks/useBlockBackButton.ts
  src/screens/PinAuthenticationScreen.js
Labels: needs dev review, android, merge when ready, team1, dev QA

#3826 Skeleton shimmering
  src/components/asset-list/AssetListItemSkeleton.js
  src/components/asset-list/EmptyAssetList.js
  src/screens/WalletScreen.js
Labels: needs dev review, team1, dev QA

#3733 chore: updates polygon allowlist
  src/references/polygon-allowlist.json
Labels: nice for release, team1, dev QA

#3882 swaps: adjust gas default logic
  src/screens/ExchangeModal.js
Labels: team2

#3953 Profiles: make hidden nfts work with profiles
  e2e/hiddenTokensFlow.spec.js
  src/helpers/assets.ts
  src/hooks/index.ts
  src/hooks/useExternalWalletSectionsData.ts
  src/hooks/useFetchHiddenTokens.ts
Labels: profiles, team1, team2, dev QA

#3952 Profiles: Fix ENS NFT video filter
  src/hooks/useWalletSectionsData.ts
  src/screens/SelectUniqueTokenSheet.tsx
Labels: profiles, team2, dev QA

#3951 Profiles: Refactor & fix opening ENS NFTs
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/hooks/index.ts
  src/hooks/useENSUniqueToken.ts
  src/hooks/useExternalWalletSectionsData.ts
  src/hooks/useFetchUniqueTokens.ts
  src/hooks/useOpenENSNFTHandler.ts
  src/redux/uniqueTokens.ts
  src/screens/ProfileSheet.tsx
Labels: profiles, team2, dev QA

#3948 Remove the screen under wallet screen after navigating after creating a wallet from seeds
  src/hooks/useImportingWallet.ts
  src/screens/WalletScreen.js
Labels: needs dev review, android, release, merge when ready, team1, dev QA

#3872 Disable font scaling
  patches/react-native+0.68.1.patch
Labels: team1, dev QA

#3932 Profiles: Fixes for the navigation
  package.json
  patches/@gorhom+bottom-sheet+4.1.5.patch
  patches/@gorhom+bottom-sheet+4.4.3.patch
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
  src/components/asset-list/RecyclerAssetList2/index.tsx
  src/navigation/Routes.android.js
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/SelectUniqueTokenSheet.tsx
  yarn.lock
Labels: android, profiles, team2

#3902 Remove choose wallet bottom divider
  src/screens/ChangeWalletSheet.js
Labels: android, merge when ready, dev QA

#3959 Profiles: Tweak android padding
  src/screens/ENSIntroSheet.tsx
Labels: profiles, team2, dev QA

#3957 profiles: rename tx ensRegistrationName to ensCommitRegistrationName
  src/entities/transactions/transaction.ts
  src/parsers/newTransaction.ts
  src/raps/actions/ens.ts
  src/screens/SpeedUpAndCancelSheet.js
Labels: profiles, team2, dev QA

#3960 Profiles: Fix confirmation text
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles, team2, dev QA

#3955 Fix for disappearing bottom sheet
  src/navigation/bottom-sheet/constants.ts
Labels: needs dev review, android, merge when ready, team1, dev QA

#3961 Android: Fix non-centered buttons in ENS reg
  src/components/ens-registration/TextRecordsForm/SelectableButton.tsx
  src/components/inputs/InlineField.tsx
  src/screens/ENSAssignRecordsSheet.tsx
Labels: blocker, android, profiles, team2, dev QA

#3966 Profiles: Truncate long ENS names
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/ENSIntroSheet.tsx
  src/screens/SelectENSSheet.tsx
  src/utils/abbreviations.ts
Labels: profiles, team2, dev QA

#3965 profiles: SelectUniqueTokenSheet android tweaks
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
  src/components/asset-list/RecyclerAssetList2/index.tsx
  src/navigation/Routes.android.js
  src/navigation/effects.js
  src/screens/SelectUniqueTokenSheet.tsx
Labels: profiles, team2, dev QA

#3958 Fix sending status badge position on Android
  src/components/Spinner.tsx
  src/components/coin-row/FastTransactionStatusBadge.tsx
Labels: android, merge when ready, team1, dev QA

#3954 PIN confirmation skipping
  src/screens/PinAuthenticationScreen.js
Labels: needs dev review, android, team1, dev QA

#3967 Fix ENS registration keyboard popping up in sheet
  src/components/ens-registration/SearchInput/SearchInput.tsx
Labels: merge when ready, profiles, team2, dev QA

#3968 profiles: view on web ens name
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Labels: profiles, team2, dev QA

#3963 profiles: cover uploading state
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/hooks/useSelectImageMenu.tsx
  src/languages/_english.json
  src/languages/_french.json
Labels: profiles, team2, dev QA

#3969 Profiles: Image edge cases
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/images/ImagePreviewOverlay.tsx
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/utils/getLowResUrl.ts
Labels: profiles, team2, dev QA

#3972 Fix send button not pre-filling address in ENS profile
  src/components/ens-profile/ActionButtons/SendButton.tsx
Labels: android, merge when ready, profiles, team1, dev QA

#3971 Fix cropped shadow on Android in ENS profiles
  src/components/ens-profile/ActionButtons/ActionButton.tsx
Labels: android, merge when ready, profiles, team1, dev QA

#3974 fix NFT gas button rm touchable + elevation
  src/components/send/SendAssetFormCollectible.js
Labels: release

#3962 Profiles: navigation improvements
  package.json
  patches/@gorhom+bottom-sheet+4.1.5.patch
  patches/@gorhom+bottom-sheet+4.4.3.patch
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
  src/components/expanded-state/ens/ConfigurationSection.tsx
  src/hooks/useENSRegistrationActionHandler.ts
  src/navigation/Routes.android.js
  src/navigation/bottom-sheet/constants.ts
  src/navigation/routesNames.js
  src/screens/ENSAssignRecordsSheet.tsx
  yarn.lock
Labels: needs dev review, release, merge when ready, profiles, team1, team2, dev QA

#3976 profiles: intro screen smog screen sizing
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/screens/ENSIntroSheet.tsx
Labels: profiles

#3983 Profiles: Send sheet - check if address is valid when pasting
  src/screens/SendSheet.js
Labels: release, profiles, team2, dev QA

#3980 profiles: clean up sentry logs
  src/hooks/useENSRegistrationActionHandler.ts
Labels: release, profiles, team2

#3984 profiles: name validations
  src/languages/_english.json
  src/languages/_french.json
  src/utils/__tests__/ens.test.ts
  src/utils/ens.ts
Labels: release, profiles, team2

#3979 Profiles: route qr code to profile sheet
  src/handlers/deeplinks.ts
  src/hooks/useScanner.ts
Labels: release, profiles, team2

#3981 Make hardhat related tests less flaky
  hardhat.config.js
Labels: merge when ready, team2, dev QA

#3987 Fix recycling in ENS profiles
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
Labels: needs dev review, release, merge when ready, team2, dev QA

#3978 Remove unused yet another bottom sheet implementation from the repo
  package.json
  src/react-native-yet-another-bottom-sheet/Context.js
  src/react-native-yet-another-bottom-sheet/Form.js
  src/react-native-yet-another-bottom-sheet/ScrollView.js
  src/react-native-yet-another-bottom-sheet/index.js
  tsconfig.json
Labels: team1, dev QA

#3912 add poap analytics tracking
  src/handlers/poap.ts
  src/redux/uniqueTokens.ts
Labels: release, team2

#3992 profiles: disable image overlay on android
  src/components/expanded-state/ens/InfoRow.tsx
Labels: profiles, team2

#3991 fix: android scan payment link
  src/utils/ethereumUtils.ts
Labels: android, dev QA

#3989 Fix keyboard layout issues in SendSheet on Android
  src/components/send/SendAssetForm.js
  src/screens/SendSheet.js
Labels: android, merge when ready, team1, dev QA

#3993 fix: confirmation screen height
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
Labels: release

#3994 profiles: special characters e2e
  e2e/registerENSFlow.spec.js
  src/utils/ens.ts
Labels: release, dev QA

#3995 Profiles: fix header removal crash
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/hooks/useSelectImageMenu.tsx
Labels: profiles, team2, dev QA

#3996 Profiles: Temporarily disable cover photo zoom on Android
  src/components/expanded-state/UniqueTokenExpandedState.tsx
Labels: profiles

#4002 profiles: improve photo removal
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Labels: profiles, team2, dev QA

#3909 Fix missing active sale price in NFT expanded sheet
  src/entities/uniqueAssets.ts
  src/handlers/opensea-api.ts
  src/parsers/uniqueTokens.js
  src/references/opensea/index.ts
  src/references/opensea/opensea-payment-tokens.json
Labels: needs dev review, team2, dev QA

#3998 Profiles: Fix description overflow
  src/components/expanded-state/ens/InfoRow.tsx
Labels: profiles, dev QA

#3999 profiles: disable profiles cards on testnets
  src/components/discover-sheet/DiscoverHome.js
Labels: profiles, dev QA

#4003 profiles: disable ens token fetching on testnet
  src/redux/uniqueTokens.ts
Labels: release, profiles, team2, dev QA

#4006 Version bump iOS v1.7.1 & android 141
  CHANGELOG.md
  android/app/build.gradle
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#3903 fix L2 WC balances
  src/utils/ethereumUtils.ts
Labels: nice for release, team2, dev QA

#3956 chore: add 2 polygon allowlist
  src/references/polygon-allowlist.json
Labels: release

#4007 fix: profiles typo
  src/hooks/useENSRecordDisplayProperties.tsx
Labels: profiles, team2, dev QA

#4008 profiles: fix unwatch last wallet in app
  src/hooks/useWatchWallet.ts
Labels: profiles, team2

#3973 Update showcased/hidden token handling for watched wallets.
  e2e/hiddenTokensFlow.spec.js
  e2e/watchedWalletCollectionActionsFlow.spec.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
  src/hooks/useWalletSectionsData.ts
  src/redux/hiddenTokens.ts
  src/redux/showcaseTokens.ts
Labels: team1, dev QA

#4010 fix: pull in Trove marketplace URL
  src/components/unique-token/Tag.js
  src/parsers/uniqueTokens.js
Labels: team1, dev QA

#3665 Update text input props
  src/screens/ImportSeedPhraseSheet.js
Labels: dev QA

#4013 Remove unused Animated.Code call
  src/screens/WalletScreen.js
Labels: team1, dev QA

#3867 Reduce `any` usage in `src/hooks`.
  src/components/ens-profile/ActionButtons/MoreButton.tsx
  src/components/settings-menu/DevNotificationsSection.tsx
  src/entities/dispersion.ts
  src/entities/index.ts
  src/helpers/sortList.ts
  src/hooks/useAccountAsset.ts
  src/hooks/useAccountEmptyState.ts
  src/hooks/useAccountSettings.ts
  src/hooks/useAccountTransactions.ts
  src/hooks/useAddCashLimits.ts
  src/hooks/useAppState.ts
  src/hooks/useAppVersion.ts
  src/hooks/useAsset.ts
  src/hooks/useBooleanState.ts
  src/hooks/useClipboard.ts
  src/hooks/useCollectible.ts
  src/hooks/useColorForAsset.ts
  src/hooks/useContacts.ts
  src/hooks/useDeleteWallet.ts
  src/hooks/useENSRecordDisplayProperties.tsx
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useExpandedStateNavigation.ts
  src/hooks/useGenericAsset.ts
  src/hooks/useImageMetadata.ts
  src/hooks/useImportingWallet.ts
  src/hooks/useInitializeDiscoverData.ts
  src/hooks/useKeyboardHeight.ts
  src/hooks/useLoadGlobalLateData.ts
  src/hooks/useMagicAutofocus.ts
  src/hooks/useManageCloudBackups.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePoolDetails.ts
  src/hooks/usePortfolios.ts
  src/hooks/usePurchaseTransactionStatus.ts
  src/hooks/useRequests.ts
  src/hooks/useRouteExistsInNavigationState.ts
  src/hooks/useSavingsAccount.ts
  src/hooks/useScanner.ts
  src/hooks/useSelectImageMenu.tsx
  src/hooks/useSendFeedback.ts
  src/hooks/useSendableUniqueTokens.ts
  src/hooks/useShowcaseTokens.ts
  src/hooks/useTrackENSProfile.ts
  src/hooks/useUniswapAssetsInWallet.ts
  src/hooks/useUniswapPools.ts
  src/hooks/useUpdateEmoji.ts
  src/hooks/useUserLists.ts
  src/hooks/useWalletBalances.ts
  src/hooks/useWalletCloudBackup.ts
  src/hooks/useWalletConnectConnections.ts
  src/hooks/useWallets.ts
  src/hooks/useWalletsWithBalancesAndNames.ts
  src/hooks/useWatchWallet.ts
  src/hooks/useWebData.ts
  src/redux/uniswapLiquidity.ts
  src/screens/SendConfirmationSheet.tsx
  src/screens/SettingsSheetV2.tsx
Labels: needs dev review, team1

#3964 [TEAM2-328] Use Unique Id Pattern to Grab No Mainnet Addy Prices
  src/raps/actions/swap.ts
  src/redux/additionalAssetsData.ts
  src/redux/explorer.ts
Labels: swap-aggregator, team2, dev QA

#4009 Revert Unsupported Testnets To Mainnet
  src/screens/WalletScreen.js
Labels: merge when ready, team2, the-merge

#3986 [TEAM2-377] EIP-4339 Detect Merge With Flag
  src/handlers/web3.ts
  src/model/mmkv.ts
  src/redux/explorer.ts
Labels: merge when ready, team2, dev QA, the-merge

#4001 [TEAM2-374] Remove Deprecated Testnets
  .env.example
  src/featuresToUnlock/optimismNftAppIconCheck.ts
  src/handlers/assets.ts
  src/handlers/web3.ts
  src/helpers/networkInfo.ts
  src/helpers/networkTypes.ts
  src/hooks/useRefreshAccountData.ts
  src/model/config.ts
  src/redux/uniqueTokens.ts
  src/redux/walletconnect.ts
  src/references/chain-assets.json
  src/references/chains.json
  src/references/compound/saving-assets.json
  src/references/index.ts
  src/references/uniswap/uniswap-pairs-testnet.json
  src/screens/ProfileScreen.js
  src/screens/WalletScreen.js
  src/styles/colors.ts
Labels: merge when ready, team2, dev QA, the-merge

#3923 Add check that ENS suffix is not empty string
  src/helpers/validators.ts
Labels: critical path

#3720 Settings Redesign
  e2e/hardhatTransactionFlow.spec.js
  ios/Podfile.lock
  patches/react-native-ios-context-menu+1.7.4.patch
  src/assets/chevronUpDown.png
  src/assets/chevronUpDown@2x.png
  src/assets/chevronUpDown@3x.png
  src/assets/settingsNotifications.png
  src/assets/settingsNotifications@2x.png
  src/assets/settingsNotifications@3x.png
  src/assets/settingsNotificationsDark.png
  src/assets/settingsNotificationsDark@2x.png
  src/assets/settingsNotificationsDark@3x.png
  src/components/AppVersionStamp.js
  src/components/backup/BackupManualStep.js
  src/components/radio-list/RadioList.js
  src/components/radio-list/RadioListItem.js
  src/components/radio-list/index.js
  src/components/secret-display/SecretDisplayCard.tsx
  src/components/secret-display/SecretDisplaySection.js
  src/components/secret-display/SecretDisplaySection.tsx
  src/components/secret-display/index.ts
  src/components/settings-menu/AppIconSection.tsx
  src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx
  src/components/settings-menu/BackupSection/BackupSection.tsx
  src/components/settings-menu/BackupSection/NeedsBackupView.tsx
  src/components/settings-menu/BackupSection/SettingsBackupView.tsx
  src/components/settings-menu/BackupSection/ShowSecretView.tsx
  src/components/settings-menu/BackupSection/WalletSelectionView.js
  src/components/settings-menu/CurrencySection.js
  src/components/settings-menu/CurrencySection.tsx
  src/components/settings-menu/DevSection.js
  src/components/settings-menu/DevSection.tsx
  src/components/settings-menu/LanguageSection.tsx
  src/components/settings-menu/NetworkSection.tsx
  src/components/settings-menu/NotificationsSection.tsx
  src/components/settings-menu/PrivacySection.js
  src/components/settings-menu/PrivacySection.tsx
  src/components/settings-menu/SettingsSection.js
  src/components/settings-menu/SettingsSection.tsx
  src/components/settings-menu/UserDevSection.js
  src/components/settings-menu/WalletNotificationsSettings.tsx
  src/components/settings-menu/components/Menu.tsx
  src/components/settings-menu/components/MenuContainer.tsx
  src/components/settings-menu/components/MenuItem.tsx
  src/components/settings-menu/index.ts
  src/components/text/Emoji.js
  src/design-system/color/palettes.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/routesNames.js
  src/screens/ProfileScreen.js
  src/screens/SettingsSheet.js
  src/screens/SettingsSheet.tsx
  src/styles/colors.ts
Labels: needs dev review, notifications, team2, dev QA

#4032 chore: e2e -> hide gwei label for testing
  src/components/expanded-state/custom-gas/GweiInputPill.js
Labels: blocker

#4037 Profiles: Fix issue where a user could not see their NFTs
  src/apollo/queries.ts
  src/handlers/ens.ts
  src/hooks/useAccountENSDomains.ts
Labels: release, dev QA

#4026 swaps: settings e2e
  e2e/swapSheetFlow.spec.js
  src/components/context-menu/ContextMenuButton.js
  src/components/exchange/NetworkSwitcher.js
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/expanded-state/swap-settings/StepButtonInput.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/screens/CurrencySelectModal.js
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2

#4022 Add hiddenTokens to initWebData
  src/hooks/useWebData.ts
Labels: team1, dev QA

#3997 Fix spacing issues on transaction review sheet
  src/screens/SendConfirmationSheet.tsx
Labels: android, merge when ready, team1

#4024 Fix line height in send form bubble input
  src/components/fields/BubbleField.js
Labels: android, team1

#4029 Profiles: Fix "Selling" NFTs alignment
  src/components/token-family/TokenFamilyHeaderIcon.tsx
  src/helpers/assets.ts
Labels: release

#4047 Profiles: fix telegram link
  src/hooks/useENSRecordDisplayProperties.tsx
Labels: profiles, team2

#4000 Improve ‘more details’ tap target area for swaps
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
Labels: android, swap-aggregator, team2, dev QA

#4050 Note about ProfileMasthead being used by Android
  src/components/profile/ProfileMasthead.js
Labels: team2

#4027 Add wallet statuses `new` `imported` and `old` to wallet initialize time tracking
  src/hooks/useInitializeWallet.ts
Labels: performance, analytics, team1, dev QA

#4035 swaps: add review sheet to e2e
  e2e/swapSheetFlow.spec.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
Labels: merge when ready, swap-aggregator, team2, dev QA

#4063 Version bump iOS v1.7.3 & android 143
  CHANGELOG.md
  android/app/build.gradle
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#4064 Bump slack api github action
  .github/workflows/macstadium-e2e.yml
Labels: merge when ready, dev QA

#4054 Profiles: Add more E2E test coverage for view/edit profile
  e2e/registerENSFlow.spec.js
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/inputs/InlineField.tsx
  src/helpers/ens.ts
  src/screens/ENSAdditionalRecordsSheet.tsx
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles, team2, dev QA

#4058 Profiles: Add E2E for discover search ordering
  e2e/discoverSheetFlow.spec.js
  src/components/discover-sheet/DiscoverSearch.js
  src/components/exchange/ExchangeAssetList.js
  src/hooks/useSwapCurrencyList.ts
Labels: profiles, team2

#4055 Fix hiding create/edit wallet modal
  src/components/expanded-state/WalletProfileState.js
  src/helpers/isKeyboardOpen.ts
  src/navigation/bottom-sheet/views/BottomSheetRoute.tsx
  src/navigation/onNavigationStateChange.js
  src/screens/PinAuthenticationScreen.js
Labels: android, team1, dev QA

#4030 Bump segment SDK to the latest version and remove ObjC++ build flags
  ios/Podfile.lock
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/Rainbow/AppDelegate.mm
  package.json
  src/react-native-cool-modals/ios/RNCMScreen.h
  src/react-native-cool-modals/ios/RNCMScreenStack.h
  yarn.lock
Labels: analytics, team2, dev QA

#4019 Fix iOS change wallet sheet animations regression
  src/components/change-wallet/WalletList.js
Labels: needs design review, dev QA

#4044 Add yarn nuke script
  package.json
  scripts/nuke.sh
Labels: needs dev review, merge when ready, dev QA

#4059 Custom app icon for SMOL/Treasure
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-anydpi-v26/smol.xml
  android/app/src/main/res/mipmap-anydpi-v26/smol_round.xml
  android/app/src/main/res/mipmap-hdpi/smol.png
  android/app/src/main/res/mipmap-hdpi/smol_background.png
  android/app/src/main/res/mipmap-hdpi/smol_foreground.png
  android/app/src/main/res/mipmap-hdpi/smol_round.png
  android/app/src/main/res/mipmap-ldpi/smol.png
  android/app/src/main/res/mipmap-ldpi/smol_background.png
  android/app/src/main/res/mipmap-ldpi/smol_foreground.png
  android/app/src/main/res/mipmap-ldpi/smol_round.png
  android/app/src/main/res/mipmap-mdpi/smol.png
  android/app/src/main/res/mipmap-mdpi/smol_background.png
  android/app/src/main/res/mipmap-mdpi/smol_foreground.png
  android/app/src/main/res/mipmap-mdpi/smol_round.png
  android/app/src/main/res/mipmap-xhdpi/smol.png
  android/app/src/main/res/mipmap-xhdpi/smol_background.png
  android/app/src/main/res/mipmap-xhdpi/smol_foreground.png
  android/app/src/main/res/mipmap-xhdpi/smol_round.png
  android/app/src/main/res/mipmap-xxhdpi/smol.png
  android/app/src/main/res/mipmap-xxhdpi/smol_background.png
  android/app/src/main/res/mipmap-xxhdpi/smol_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/smol_round.png
  android/app/src/main/res/mipmap-xxxhdpi/smol.png
  android/app/src/main/res/mipmap-xxxhdpi/smol_background.png
  android/app/src/main/res/mipmap-xxxhdpi/smol_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/smol_round.png
  ios/AppIcons/smol@2x.png
  ios/AppIcons/smol@3x.png
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/Rainbow/Info.plist
  src/assets/appIconSmol.png
  src/assets/appIconSmol@2x.png
  src/assets/appIconSmol@3x.png
  src/components/settings-menu/AppIconSection.tsx
  src/featuresToUnlock/featureUnlockChecks.ts
  src/featuresToUnlock/index.ts
  src/featuresToUnlock/optimismNftAppIconCheck.ts
  src/featuresToUnlock/unlockableAppIconCheck.ts
  src/featuresToUnlock/unlockableAppIcons.ts
  src/handlers/walletReadyEvents.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
  src/styles/colors.ts
Labels: dev QA, rc-v1.7.3

#4075 Fix bad custom icon filepaths on android
  android/app/src/main/res/mipmap-anydpi-v26/smol.xml
  android/app/src/main/res/mipmap-anydpi-v26/smol_round.xml
Labels: merge when ready, dev QA

#4017 Profiles: Fix issue where a user could not select ENS names they control
  src/apollo/queries.ts
  src/handlers/ens.ts
  src/hooks/useAccountENSDomains.ts
  src/hooks/useTrackENSProfile.ts
  src/screens/ENSIntroSheet.tsx
  src/screens/SelectENSSheet.tsx
Labels: release, profiles, team2

#4053 Fix password field focus
  src/components/fields/PasswordField.js
Labels: android, team1, dev QA

#4076 [TEAM2-443] Disable Flashbots Post Merge (temporarily)
  package.json
  src/model/config.ts
  src/screens/ExchangeModal.js
  src/screens/TransactionConfirmationScreen.js
  yarn.lock
Labels: team2, dev QA, the-merge

#4042 swaps: fix android swap details focus
  src/components/expanded-state/SwapDetailsState.js
Labels: needs dev review, swap-aggregator, team2

#4077 feat: campaigns & swaps promo
  src/App.js
  src/assets/swapsPromoBackground.png
  src/assets/swapsPromoBackground@2x.png
  src/assets/swapsPromoBackground@3x.png
  src/assets/swapsPromoHeader.png
  src/assets/swapsPromoHeader@2x.png
  src/assets/swapsPromoHeader@3x.png
  src/campaigns/campaignChecks.ts
  src/campaigns/swapsPromoCampaign.ts
  src/components/promos/InfoRow.tsx
  src/components/promos/PromoSheet.tsx
  src/components/promos/index.ts
  src/handlers/walletReadyEvents.ts
  src/helpers/networkInfo.ts
  src/languages/_english.json
  src/languages/_french.json
  src/model/mmkv.ts
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/onNavigationStateChange.js
  src/navigation/routesNames.js
  src/screens/ChangeWalletSheet.js
  src/screens/SwapsPromoSheet.tsx
  src/screens/WalletScreen.js
  src/styles/colors.ts
Labels: release, team2, dev QA, rc-v1.7.3
