Repository rainbow-me/rainbow, pull requests merged in 2022-01, with the labels that each got.

#2758 Get rid of the reanimated button in edit mode
  src/components/animations/RoundButtonSizeToggler.js
  src/components/coin-row/BalanceCoinRow.js
  src/components/coin-row/CoinCheckButton.js
Labels: needs code review, QA later, android

#2767 Fix scrubbing
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
  src/react-native-animated-charts/src/helpers/ChartContext.ts
Labels: needs code review, blocker, QA later, android, merge when ready

#2772 Default 1D % change in charts
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
Labels: QA later, android, merge when ready

#2775 add skeletons to loading state
  src/helpers/buildWalletSections.js
Labels: QA later

#2788 Include generic assets and placeholder ETH fallback logic in useAccountAsset
  src/components/expanded-state/asset/ChartExpandedState.js
  src/hooks/useAccountAsset.js
  src/hooks/useAsset.js
Labels: blocker, merge when ready

#2783 Skip unnecessary generic assets fallback
  src/redux/data.js
  src/redux/explorer.js
Labels: QA later

#2784 relink gas icons
  ios/Images.xcassets/gasEmojis/Contents.json
  ios/Images.xcassets/gasEmojis/gear.imageset/Contents.json
  ios/Images.xcassets/gasEmojis/gear.imageset/gear.png
  ios/Images.xcassets/gasEmojis/gear.imageset/gear@2x.png
  ios/Images.xcassets/gasEmojis/gear.imageset/gear@3x.png
  ios/Images.xcassets/gasEmojis/policeCarLight.imageset/Contents.json
  ios/Images.xcassets/gasEmojis/policeCarLight.imageset/policeCarLight.png
  ios/Images.xcassets/gasEmojis/policeCarLight.imageset/policeCarLight@2x.png
  ios/Images.xcassets/gasEmojis/policeCarLight.imageset/policeCarLight@3x.png
  ios/Images.xcassets/gasEmojis/rocket.imageset/Contents.json
  ios/Images.xcassets/gasEmojis/rocket.imageset/rocket.png
  ios/Images.xcassets/gasEmojis/rocket.imageset/rocket@2x.png
  ios/Images.xcassets/gasEmojis/rocket.imageset/rocket@3x.png
  ios/Images.xcassets/gasEmojis/stopwatch.imageset/Contents.json
  ios/Images.xcassets/gasEmojis/stopwatch.imageset/stopwatch.png
  ios/Images.xcassets/gasEmojis/stopwatch.imageset/stopwatch@2x.png
  ios/Images.xcassets/gasEmojis/stopwatch.imageset/stopwatch@3x.png
Labels: QA later

#2699 Refactor QR scanner
  ios/Podfile.lock
  package.json
  src/components/layout/Flex.js
  src/components/qrcode-scanner/QRCodeScanner.js
  src/components/qrcode-scanner/QRCodeScannerNeedsAuthorization.js
  src/hooks/index.js
  src/hooks/useAsyncEffect.ts
  src/hooks/useHardwareBack.ts
  src/hooks/useScanner.js
  src/screens/QRScannerScreen.js
  yarn.lock
Labels: blocker, android

#2760 Refactor useSavingsAccount
  src/hooks/useGenericAsset.js
  src/hooks/useSavingsAccount.js
  src/hooks/useWalletSectionsData.js
  src/redux/explorer.js
Labels: QA later, android, merge when ready

#2770 Convert more Redux reducers to TypeScript.
  src/components/add-cash/AddCashStatus.js
  src/entities/index.ts
  src/entities/tokens.ts
  src/entities/uniqueAssets.ts
  src/helpers/chartTypes.ts
  src/helpers/wyreStatusTypes.js
  src/helpers/wyreStatusTypes.ts
  src/hooks/useUniswapCurrencyList.ts
  src/redux/addCash.ts
  src/redux/appState.js
  src/redux/appState.ts
  src/redux/charts.js
  src/redux/charts.ts
  src/redux/data.js
  src/redux/explorer.js
  src/redux/fallbackExplorer.js
  src/redux/optimismExplorer.js
  src/redux/requests.js
  src/redux/requests.ts
  src/redux/showcaseTokens.js
  src/redux/showcaseTokens.ts
  src/redux/uniqueTokens.ts
  src/redux/uniswap.js
  src/redux/uniswap.ts
  src/redux/uniswapLiquidity.js
  src/redux/uniswapLiquidity.ts
  src/references/index.ts
Labels: QA later

#2774 Fix iPhone 7 swap gas button
  src/screens/ExchangeModal.js
Labels: needs code review, QA later, merge when ready

#2797 Fix crash in animated numbers
  ios/RainbowText.m
  src/components/savings/SavingsListRow.js
Labels: blocker, android, merge when ready

#2798 Enable signTypedData_v4
  e2e/hardhatTransactionFlow.spec.js
  src/components/transaction/TransactionMessage.js
  src/parsers/requests.js
  src/screens/TransactionConfirmationScreen.js
  src/utils/signingMethods.ts
Labels: merge when ready

#2801 Fix Add Cash crash
  src/handlers/localstorage/accountLocal.ts
  src/redux/data.js
Labels: blocker, QA later, merge when ready

#2811 add optional chaining
  src/components/expanded-state/asset/ChartExpandedState.js
Labels: needs code review, QA later

#2790 [RNBW-2039] Fix empty state bugs
  src/components/asset-list/AssetList.js
  src/components/asset-list/EmptyAssetList.js
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/asset-list/RecyclerAssetList2/core/RefreshControl.tsx
  src/helpers/buildWalletSections.js
  src/hooks/useAccountEmptyState.js
  src/hooks/useInternetStatus.js
  src/hooks/useRefreshAccountData.js
  src/screens/SendSheet.js
  src/screens/WalletScreen.js
Labels: QA later

#2780 [RNBW-2086] Fix wallet name not updating
  src/helpers/utilities.ts
  src/screens/ChangeWalletSheet.js
Labels: QA later

#2812 Fix key for cloud backup description.
  src/screens/BackupSheet.js
Labels: QA later

#2814 Fix some i18n duplicate issues.
  src/components/expanded-state/ContactProfileState.js
  src/components/expanded-state/WalletProfileState.js
  src/components/profile/ProfileMasthead.js
  src/components/send/SendHeader.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/SettingsModal.js
  src/screens/WelcomeScreen.js
Labels: needs code review, QA later

#2817 auditdotme - markdown-it & follow-redirects
  package.json
  yarn.lock
Labels: needs dev review, QA later, merge when ready

#2810 useCallback and useMemo in useUniswapAssetsInWallet
  src/hooks/useUniswapAssetsInWallet.js
Labels: QA later

#2799 Make Chart Labels faster to render
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.js
  src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/components/value-chart/Chart.js
  src/react-native-animated-charts/src/charts/linear/ChartLabels.tsx
Labels: needs dev review, QA later

#2806 pass hidden & pinned from balance row
  src/components/coin-row/BalanceCoinRow.js
  src/components/coin-row/CoinRow.js
  src/components/send/SendAssetList.js
  src/screens/CurrencySelectModal.js
Labels: blocker, QA later, merge when ready

#2820 fix gas button network in txConfirmationScreen
  src/screens/TransactionConfirmationScreen.js
Labels: QA later

#2808 Disable font scaling on gas inputs
  src/components/expanded-state/custom-gas/GweiInputPill.js
Labels: needs dev review, QA later, merge when ready

#2792 showcase sheet behavior fixes
  src/components/discover-sheet/DiscoverSearch.js
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/components/showcase/ShowcaseHeader.js
  src/screens/ShowcaseSheet.js
Labels: needs dev review, QA later

#2826 Fix keyboard handling on dark mode on android
  src/navigation/onNavigationStateChange.js
Labels: needs dev review, android, merge when ready

#2830 [RNBW-2220] v2 tokens array -> map and token search versioning
  src/handlers/dispersion.ts
  src/handlers/tokenSearch.ts
  src/hooks/useAdditionalAssetData.ts
  src/hooks/useUniswapAssetsInWallet.js
  src/hooks/useUniswapCurrencyList.ts
  src/utils/uniswapAssetsCache.ts
Labels: needs dev review, blocker, merge when ready

#2836 update learn links
  src/components/settings-menu/SettingsSection.js
  src/screens/ExplainSheet.js
Labels: needs dev review

#2833 Update traits type on UniqueAsset to be an array of trait objects
  src/entities/uniqueAssets.ts
Labels: needs dev review

#2832 Design system updates
  src/design-system/README.md
  src/design-system/color/palettes.docs.tsx
  src/design-system/color/palettes.ts
  src/design-system/components/BackgroundProvider/BackgroundProvider.tsx
  src/design-system/components/Bleed/Bleed.docs.tsx
  src/design-system/components/Bleed/Bleed.examples.tsx
  src/design-system/components/Bleed/Bleed.tsx
  src/design-system/components/Box/Box.tsx
  src/design-system/components/Columns/Columns.tsx
  src/design-system/components/DebugLayout/DebugLayout.docs.tsx
  src/design-system/components/DebugLayout/DebugLayout.examples.tsx
  src/design-system/components/DebugLayout/DebugLayout.meta.ts
  src/design-system/components/DebugLayout/DebugLayout.playground.tsx
  src/design-system/components/DebugLayout/DebugLayout.tsx
  src/design-system/components/Divider/Divider.docs.tsx
  src/design-system/components/Divider/Divider.examples.tsx
  src/design-system/components/Divider/Divider.meta.ts
  src/design-system/components/Divider/Divider.playground.tsx
  src/design-system/components/Divider/Divider.tsx
  src/design-system/components/Inline/Inline.tsx
  src/design-system/components/Inset/Inset.docs.tsx
  src/design-system/components/Inset/Inset.examples.tsx
  src/design-system/components/Inset/Inset.tsx
  src/design-system/components/MarkdownText/MarkdownText.playground.tsx
  src/design-system/components/MarkdownText/MarkdownText.tsx
  src/design-system/components/Row/Row.tsx
  src/design-system/components/Stack/Stack.tsx
  src/design-system/components/Text/Text.examples.tsx
  src/design-system/components/TextLink/TextLink.tsx
  src/design-system/docs/docs.ts
  src/design-system/index.ts
  src/design-system/layout/space.ts
  src/design-system/playground/Playground.tsx
  src/design-system/typography/typeHierarchy.docs.tsx
  src/design-system/typography/typeHierarchy.ts
Labels: needs dev review

#2831 fix reseting ENS results
  src/handlers/ens.ts
Labels: needs dev review

#2834 Fix checklist formatting in PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: needs dev review

#2842 Align Prettier config with eslint-config-rainbow rules
  .eslintrc.js
  .prettierrc.js
  src/design-system/components/Box/Box.tsx
  src/design-system/docs/system/tokens.css.ts
Labels: needs dev review

#2839 Fix design system docs by upgrading vanilla-extract plugin
  src/design-system/docs/next-env.d.ts
  src/design-system/docs/package.json
  src/design-system/docs/yarn.lock
Labels: needs dev review

#2843 Fix AddFundsInterstitial
  src/components/asset-list/EmptyAssetList.js
Labels: needs dev review, QA later, android, merge when ready

#2845 Fix margins in PulseIndexSection
  src/components/discover-sheet/PulseIndexSection.js
Labels: needs dev review, QA later, android, merge when ready, nice for release

#2844 Fix flashing of dot in charts
  src/react-native-animated-charts/src/charts/linear/ChartDot.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
Labels: nice for release

#2841 last search tweaks
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/components/exchange/CurrencySelectionList.js
  src/handlers/ens.ts
  src/hooks/useUniswapCurrencyList.ts
  src/screens/CurrencySelectModal.js
Labels: nice for release

#2861 Fix backup explainer platform name.
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
  src/utils/platform.ts
Labels: needs dev review, QA later

#2846 add default edit button
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
  src/components/asset-list/RecyclerViewTypes.js
  src/components/coin-divider/CoinDivider.js
  src/helpers/assets.js
Labels: needs dev review, needs design review

#2863 Fix add cash flow on android within BuyActionButton
  src/components/sheet/sheet-action-buttons/BuyActionButton.js
Labels: blocker, QA later, android, merge when ready

#2847 use set next emoji picker on android
  src/components/profile/ProfileMasthead.js
  src/components/showcase/ShowcaseHeader.js
  src/components/transaction-list/TransactionList.js
  src/config/experimental.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useUpdateEmoji.ts
  src/screens/AvatarBuilder.js
  src/utils/profileUtils.ts
Labels: needs dev review, needs QA, android, merge when ready, nice for release

#2867 fix android tx menu - default behavior
  src/components/coin-row/TransactionCoinRow.js
Labels: needs dev review, blocker, android

#2857 send smol balances optional chaining
  src/components/send/SendAssetList.js
Labels: needs dev review

#2864 fix wc crash
  src/hooks/useCurrentNonce.ts
  src/screens/TransactionConfirmationScreen.js
Labels: needs dev review

#2866 fast af
  ios/Gemfile.lock
Labels: needs dev review, merge when ready

#2871 Fix vulnerabilities
  package.json
  src/App.js
  yarn.lock
Labels: needs dev review, QA later

#2862 Design System: Add `Cover` component, `height` to `Box` & text/heading hooks
  src/design-system/components/Box/Box.docs.tsx
  src/design-system/components/Box/Box.examples.tsx
  src/design-system/components/Box/Box.playground.tsx
  src/design-system/components/Box/Box.tsx
  src/design-system/components/Columns/Columns.tsx
  src/design-system/components/Cover/Cover.docs.tsx
  src/design-system/components/Cover/Cover.examples.tsx
  src/design-system/components/Cover/Cover.meta.tsx
  src/design-system/components/Cover/Cover.playground.tsx
  src/design-system/components/Cover/Cover.tsx
  src/design-system/components/Heading/Heading.tsx
  src/design-system/components/Heading/useHeadingStyle.ts
  src/design-system/components/Inline/Inline.tsx
  src/design-system/components/Inset/Inset.tsx
  src/design-system/components/Row/Row.tsx
  src/design-system/components/Text/Text.tsx
  src/design-system/components/Text/useTextStyle.ts
  src/design-system/docs/components/CodePreview/index.tsx
  src/design-system/docs/docs.ts
  src/design-system/index.ts
  src/design-system/layout/alignment.ts
  src/design-system/layout/size.ts
  src/design-system/layout/space.ts
  src/design-system/playground/Placeholder.tsx
  src/design-system/playground/Playground.tsx
Labels: needs dev review, QA later

#2865 Refactor Native Android Button
  android/app/src/main/java/com/swmansion/gesturehandler/react/RNZoomableButtonManager.java
  ios/Button.swift
  ios/ButtonManager.m
  src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
  src/components/expanded-state/custom-gas/FeesGweiInput.js
Labels: needs dev review, blocker, android

#2879 Make icons work again!
  ios/TransactionListViewCell.swift
Labels: QA later

#2853 handle empty deeplinks
  src/handlers/deeplinks.ts
Labels: needs dev review

#2870 Include traits max value if possible
  src/components/Tag.js
  src/components/unique-token/UniqueTokenAttributes.js
Labels: needs dev review, QA later

#2877 Fix custom gas sheet
  src/components/expanded-state/CustomGasState.js
  src/components/gas/GasSpeedButton.js
  src/navigation/Routes.android.js
  src/navigation/onNavigationStateChange.js
Labels: needs dev review, blocker, needs QA, android

#2882 Ultimately fix Profile Modal keyboard handling
  src/components/expanded-state/profile/ProfileModal.js
  src/components/layout/KeyboardFixedOpenLayout.js
  src/navigation/onNavigationStateChange.js
Labels: android, merge when ready

#2885 new NFT keys + fix ts warnings
  src/handlers/opensea-api.ts
Labels: needs dev review

#2884 Abstract out PIN_AUTHENTICATION_SCREEN to a different stack
  src/navigation/Routes.android.js
Labels: blocker, android, merge when ready

#2818 Design System: Add `shadow` to `Box`
  globalVariables.js
  ios/Images.xcassets/transactions/icons/contractInteraction.imageset/Contents.json
  package.json
  src/context/ThemeContext.js
  src/design-system/color/ColorMode.tsx
  src/design-system/color/palettes.docs.tsx
  src/design-system/color/palettes.ts
  src/design-system/color/useForegroundColor.ts
  src/design-system/components/BackgroundProvider/BackgroundProvider.examples.tsx
  src/design-system/components/BackgroundProvider/BackgroundProvider.tsx
  src/design-system/components/Box/Box.docs.tsx
  src/design-system/components/Box/Box.examples.tsx
  src/design-system/components/Box/Box.playground.tsx
  src/design-system/components/Box/Box.tsx
  src/design-system/components/Columns/Columns.tsx
  src/design-system/components/private/ApplyShadow/AndroidShadow.tsx
  src/design-system/components/private/ApplyShadow/AndroidShadow.v2.tsx
  src/design-system/components/private/ApplyShadow/ApplyShadow.tsx
  src/design-system/components/private/ApplyShadow/IOSShadow.tsx
  src/design-system/context/DesignSystemContext.tsx
  src/design-system/context/ExperimentalFlagsContext.tsx
  src/design-system/docs/.gitignore
  src/design-system/docs/.playroom/FrameComponent.js
  src/design-system/docs/components/DocsAccordion/index.tsx
  src/design-system/docs/next.config.js
  src/design-system/docs/package.json
  src/design-system/docs/pages/_app.tsx
  src/design-system/docs/playroom.config.js
  src/design-system/docs/react-native-drop-shadow.tsx
  src/design-system/docs/shims.js
  src/design-system/docs/tsconfig.json
  src/design-system/docs/types.ts
  src/design-system/index.ts
  src/design-system/layout/shadow.ts
  src/design-system/playground/Playground.tsx
  tsconfig.json
  yarn.lock
Labels: needs dev review, QA later

#2893 polygon nfts
  package.json
  src/components/L2Disclaimer.js
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
  src/handlers/opensea-api.ts
  src/hooks/useOnAvatarPress.ts
  src/parsers/index.ts
  src/parsers/uniqueTokens.js
  src/redux/uniqueTokens.ts
  src/references/index.ts
  src/references/polygon-allowlist.json
  src/utils/ethereumUtils.ts
  yarn.lock
Labels: needs dev review, needs QA

#2895 Fix shadows in Discover button and Avatar Circle
  src/components/header/DiscoverHeaderButton.js
  src/components/profile/AvatarCircle.js
  src/components/profile/ProfileMasthead.js
Labels: needs dev review, QA later, android, merge when ready

#2902 nft fetching error check
  src/redux/uniqueTokens.ts
Labels: needs dev review, blocker

#2849 Fix welcome screen getting cutoff on smaller phones
  src/components/AddFundsInterstitial.js
Labels: merge when ready

#2889 Fix comparing uuids of elements recycler list
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
Labels: needs dev review, QA later, android, merge when ready

#2891 Design System: Consolidate `Row` & `Inline`
  src/design-system/components/Divider/Divider.examples.tsx
  src/design-system/components/Inline/Inline.docs.tsx
  src/design-system/components/Inline/Inline.examples.tsx
  src/design-system/components/Inline/Inline.playground.tsx
  src/design-system/components/Inline/Inline.tsx
  src/design-system/components/Row/Row.docs.tsx
  src/design-system/components/Row/Row.examples.tsx
  src/design-system/components/Row/Row.meta.ts
  src/design-system/components/Row/Row.playground.tsx
  src/design-system/components/Row/Row.tsx
  src/design-system/docs/docs.ts
  src/design-system/index.ts
  src/design-system/playground/Playground.tsx
Labels: needs dev review, QA later, design system

#2900 Fix recovery phrase authentication button alignment
  src/components/secret-display/SecretDisplaySection.js
Labels: needs dev review, QA later

#2904 Fix `bottom` styling type issue for AddFundsInterstitial & Row compatibility
  src/components/AddFundsInterstitial.js
  src/components/Tag.js
Labels: needs dev review, QA later
