Repository rainbow-me/rainbow, pull requests merged in 2022-10, with the labels that each got.

#4237 Add worm.eth to ENS marquee
  src/references/ens-intro-marquee-names.json
Labels: merge when ready, profiles

#4220 Fix BackButton crash on long press
  src/components/header/BackButton.js
Labels: swap-aggregator, team2, dev QA

#4211 Add Flashbots Protect row to swaps details
  src/components/Pill.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/languages/_english.json
  src/languages/_french.json
Labels: swap-aggregator, team2, dev QA

#4240 fix: initializing stuck state
  src/hooks/useAccountProfile.ts
  src/notifications/NotificationsHandler.tsx
  src/redux/wallets.ts
Labels: release

#4242 android: bump target sdk
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
Labels: release

#4243 Fix: Notifications not unsubscribing when clearing storage + crashing
  src/components/settings-menu/DevSection.tsx
  src/components/settings-menu/NotificationsSection.tsx
Labels: needs dev review, new feature, release, notifications, team2

#4192 [TEAM2-499] Currency Select Modal Crosschain Search
  src/handlers/tokenSearch.ts
  src/hooks/useSwapCurrencyList.ts
Labels: swap-aggregator, team2, dev QA

#4221 [TEAM2-500] Filter User Assets By Socket Support In Currency Select Modal
  src/handlers/tokenSearch.ts
  src/hooks/index.ts
  src/hooks/useSwapCurrencyList.ts
  src/hooks/useSwappableUserAssets.ts
  src/screens/CurrencySelectModal.tsx
Labels: swap-aggregator, team2, dev QA

#4025 Remove a thread blocking behavior in `react-native-keychain`
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/java/me/rainbow/NativeModules/RNStartTime/RNStartTimePackage.java
  config/test/jest-setup.js
  metro.transform.js
  package.json
  patches/react-native-keychain+8.0.0.patch
  src/model/backup.ts
  src/model/keychain.ts
  src/model/wallet.ts
  yarn.lock
Labels: android, team1

#4253 Revert Make iPhone 14 layouts happy
  ios/Podfile.lock
  package.json
  patches/react-native-safe-area-view+0.11.0.patch
  src/components/expanded-state/CustomGasState.js
  src/components/header/Header.js
  src/navigation/effects.js
  src/screens/AddCashSheet.js
  src/screens/ProfileSheet.tsx
  src/screens/SendSheet.js
  src/utils/safeAreaInsetValues.ts
  yarn.lock
Labels: release

#4261 Analytics Tapped Push Notification event
  src/notifications/NotificationsHandler.tsx
  src/notifications/analytics.ts
Labels: team2, dev QA

#4262 fix: transaction press while sending ens
  src/handlers/transactions.ts
Labels: release

#4260 Feat: Track changed settings for Notifications
  src/notifications/analytics.ts
  src/notifications/settings.ts
Labels: merge when ready, analytics, notifications

#4189 crosschain swaps: watch pending swaps & bridging
  e2e/hardhatTransactionFlowSwaps.spec.js
  e2e/swapSheetFlow2.spec.js
  ios/Images.xcassets/transactions/icons/bridged.imageset/Contents.json
  ios/Images.xcassets/transactions/icons/bridged.imageset/bridged.png
  ios/Images.xcassets/transactions/icons/bridged.imageset/bridged@2x.png
  ios/Images.xcassets/transactions/icons/bridged.imageset/bridged@3x.png
  ios/Transaction.swift
  ios/TransactionListViewCell.swift
  package.json
  patches/@rainbow-me+swaps+0.1.15.patch
  src/components/AddFundsInterstitial.js
  src/components/coin-row/FastTransactionStatusBadge.tsx
  src/components/icons/Icon.js
  src/components/icons/svg/BridgeIcon.js
  src/components/settings-menu/SettingsSection.tsx
  src/entities/protocolTypes.ts
  src/entities/transactions/transaction.ts
  src/entities/transactions/transactionStatus.ts
  src/handlers/swap.ts
  src/handlers/transactions.ts
  src/parsers/newTransaction.ts
  src/raps/actions/crosschainSwap.ts
  src/raps/actions/swap.ts
  src/raps/unlockAndCrosschainSwap.ts
  src/redux/additionalAssetsData.ts
  src/redux/data.ts
  src/screens/ExchangeModal.tsx
  yarn.lock
Labels: swap-aggregator, team2, dev QA

#4255 swaps: new swapping via
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/languages/_english.json
  src/languages/_french.json
  src/references/swap/bridges.ts
Labels: swap-aggregator, dev QA

#4278 move all the pkgs under rainbow-me org
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/hooks/useClipboard.ts
  types/clipboard.d.ts
  yarn.lock
Labels: merge when ready

#4247 Details sheet animation
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/useSwapDetailsButtonPosition.ts
Labels: needs dev review, merge when ready, swap-aggregator, dev QA

#4249 crosschain swaps: handle transaction confirmation status
  src/parsers/transactions.ts
  src/redux/data.ts
Labels: swap-aggregator

#4274 [TEAM2-476][TEAM2-472] Display Crosschain Exact Matches and Add Bridge Asset Section
  src/helpers/tokenSectionTypes.ts
  src/hooks/useSwapCurrencyList.ts
  src/screens/CurrencySelectModal.tsx
Labels: needs dev review, swap-aggregator, team2, dev QA

#4280 Implement identify call with notifications permission status
  src/notifications/NotificationsHandler.tsx
  src/notifications/analytics.ts
  src/notifications/permissions.ts
  src/notifications/settings.ts
Labels: team2, dev QA

#4281 [TEAM2-520] Allow Crosschain Token Selection in Get $ASSET Expanded State Flow
  src/screens/ExchangeModal.tsx
Labels: needs dev review, swap-aggregator, team2, dev QA

#4205 Add refuel option sheet
  src/components/coin-icon/DashedWrapper.tsx
  src/components/coin-icon/index.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsRefuelRow.js
  src/handlers/ens.ts
  src/helpers/networkInfo.ts
  src/hooks/useSwapDerivedOutputs.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.tsx
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2, dev QA

#4248 Handle refuel sheet when not enough source token
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsRefuelRow.js
  src/hooks/index.ts
  src/hooks/useMinRefuelAmount.ts
  src/hooks/useSwapCurrencyHandlers.ts
  src/hooks/useSwapRefuel.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.tsx
  src/screens/ExplainSheet.js
Labels: needs dev review, swap-aggregator, dev QA

#4290 swaps: output disabled explainers
  e2e/swapSheetFlow2.spec.js
  src/components/exchange/ConfirmExchangeButton.js
  src/components/exchange/NetworkSwitcherv2.tsx
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.tsx
  src/screens/ExplainSheet.js
Labels: swap-aggregator, dev QA

#4285 fix audio nfts: import stylesheet
  src/components/audio/AudioPlayer.js
Labels: release

#4276 add tracking new event Tapped Transaction Details Menu Item
  src/components/coin-row/TransactionCoinRow.js
  src/handlers/transactions.ts
  src/helpers/transactionActions.ts
  src/helpers/transactionPressHandler.ts
Labels: team2, dev QA

#4282 Implement tracking number of wallets with notifications enabled
  src/components/settings-menu/NotificationsSection.tsx
  src/notifications/NotificationsHandler.tsx
  src/notifications/analytics.ts
  src/notifications/settings.ts
Labels: team2, dev QA

#4291 [TEAM2-504] Spec swaps: Update CurrencySelectModal assets list UI when selecting input token
  e2e/swapSheetFlow2.spec.js
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/helpers/tokenSectionTypes.ts
  src/hooks/useSwapCurrencyList.ts
  src/screens/CurrencySelectModal.tsx
Labels: needs dev review, swap-aggregator, team2, dev QA

#4298 fix: restore add cash interstitial colors
  src/components/AddFundsInterstitial.js
Labels: release, dev QA

#4295 fix: adjust background gradient in ExchangeAssetList headers
  src/components/exchange/ExchangeAssetList.tsx
Labels: swap-aggregator, dev QA

#4256 swaps: swap long waits
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/gas/GasSpeedButton.js
  src/handlers/swap.ts
  src/languages/_english.json
  src/languages/_french.json
  src/redux/swap.ts
  src/screens/ExchangeModal.tsx
  src/screens/ExplainSheet.js
  src/utils/crossChainTimeEstimates.ts
Labels: swap-aggregator

#4294 swaps: currency selection new design
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/discover-sheet/DiscoverSearchInput.js
  src/components/exchange/CurrencySelectionList.tsx
  src/components/exchange/ExchangeAssetList.tsx
  src/components/exchange/ExchangeSearch.tsx
  src/components/exchange/ExchangeTokenRow.tsx
  src/components/exchange/NetworkSwitcherv2.tsx
  src/helpers/tokenSectionTypes.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/CurrencySelectModal.tsx
Labels: swap-aggregator, dev QA

#4214 feat: retry swap
  src/components/activity-list/ActivityList.js
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/entities/transactions/transaction.ts
  src/handlers/transactions.ts
  src/helpers/buildTransactionsSectionsSelector.tsx
  src/helpers/transactionActions.ts
  src/helpers/transactionPressHandler.ts
  src/hooks/useMagicAutofocus.ts
  src/hooks/useParamsForExchangeModal.ts
  src/model/mmkv.ts
  src/raps/actions/crosschainSwap.ts
  src/raps/actions/swap.ts
  src/raps/common.ts
  src/raps/unlockAndCrosschainSwap.ts
  src/raps/unlockAndSwap.ts
  src/screens/ExchangeModal.tsx
  src/screens/ProfileScreen.js
Labels: swap-aggregator

#4302 Revert "Remove a thread blocking behavior in `react-native-keychain` …
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/java/me/rainbow/NativeModules/RNStartTime/RNStartTimePackage.java
  config/test/jest-setup.js
  metro.transform.js
  package.json
  patches/react-native-keychain+8.0.0.patch
  src/model/backup.ts
  src/model/keychain.ts
  src/model/wallet.ts
  yarn.lock
Labels: release

#4305 Two fixes for release
  src/components/discover-sheet/DiscoverSearch.js
  src/components/exchange/ExchangeAssetList.tsx
  src/components/list/NoResults.tsx
Labels: release, swap-aggregator

#4309 hide flashbots protect detail row when swapping L2s
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/languages/_english.json
  src/languages/_french.json
Labels: release, swap-aggregator, dev QA

#4258 Add new shadow hierarchy to design system
  src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
  src/components/asset-list/RecyclerAssetList2/profile-header/ProfileAvatarRow.tsx
  src/components/discover-sheet/DPICard.tsx
  src/components/discover-sheet/ENSCreateProfileCard.tsx
  src/components/discover-sheet/ENSSearchCard.tsx
  src/components/discover-sheet/GasCard.tsx
  src/components/ens-profile/ActionButtons/ActionButton.tsx
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/expanded-state/swap-details/SwapDetailsMasthead.js
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/secret-display/SecretDisplayCard.tsx
  src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx
  src/components/settings-menu/components/Menu.tsx
  src/design-system/color/palettes.ts
  src/design-system/color/useForegroundColor.ts
  src/design-system/components/Box/Box.docs.tsx
  src/design-system/components/Box/Box.examples.tsx
  src/design-system/components/Box/Box.playground.tsx
  src/design-system/components/Box/Box.tsx
  src/design-system/index.ts
  src/design-system/layout/shadow.ts
  src/design-system/playground/Playground.tsx
  src/navigation/onNavigationStateChange.js
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/SendConfirmationSheet.tsx
Labels: design system, dev QA

#4325 audit minimatch
  package.json
  yarn.lock
Labels: release

#4338 fix e2e: add existence check
  src/screens/ExplainSheet.js
Labels: release

#4317 token deeplinks + eggs
  src/assets/partnerships/dogSunglasses.png
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/floating-emojis/DOGConfetti.js
  src/components/value-chart/Chart.js
  src/handlers/deeplinks.ts
  src/utils/ethereumUtils.ts
Labels: release

#4336 Fix `Error: unknown format:` error in ExplainSheet
  src/screens/ExplainSheet.js
Labels: release

#4334 fix: tweak scanner logic
  src/components/qrcode-scanner/QRCodeScanner.tsx
  src/hooks/useScanner.ts
Labels: release

#4332 add icon analytics
  src/components/settings-menu/AppIconSection.tsx
  src/featuresToUnlock/unlockableAppIconCheck.ts
  src/featuresToUnlock/unlockableAppIcons.ts
  src/screens/ExplainSheet.js
  src/screens/WalletScreen.js
Labels: release

#4343 @skylar/app icon followup
  src/components/settings-menu/AppIconSection.tsx
  src/featuresToUnlock/unlockableAppIconCheck.ts
Labels: release

#4344 fix: re-add dog nft to reference
  src/references/index.ts
Labels: release

#4299 swaps: i18n token sections
  src/helpers/tokenSectionTypes.ts
  src/hooks/useSwapCurrencyList.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/CurrencySelectModal.tsx
Labels: needs dev review
