Repository rainbow-me/rainbow, pull requests merged in 2022-06, with the labels that each got.

#3414 Profiles: fix loading placeholder
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
Labels: profiles

#3426 profiles: release bugz
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSResolveName.ts
  src/hooks/useImportingWallet.js
  src/hooks/useOnAvatarPress.ts
  src/raps/actions/ens.ts
  src/raps/common.ts
  src/redux/showcaseTokens.ts
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles

#3437 Rework StepIndicator to stop crashing on Android
  src/components/step-indicator/StepIndicator.tsx
Labels: needs dev review, profiles

#3442 Profiles: add spellcheck to some record inputs
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/helpers/ens.ts
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles

#3423 Profiles: improve intro screen load performance
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/handlers/localstorage/ens.ts
  src/hooks/index.js
  src/hooks/useAccountENSDomains.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileImages.ts
  src/hooks/useENSResolveName.ts
  src/hooks/useInitializeENSIntroData.ts
  src/screens/ProfileSheet.tsx
  src/screens/WalletScreen.js
Labels: profiles

#3192 fix: discover search lag
  src/components/discover-sheet/DiscoverSearch.js
  src/components/exchange/CurrencySelectionList.js
Labels: QA later

#3209 Fix: handle profile emojis
  src/components/expanded-state/WalletProfileState.js
  src/components/profile/AvatarCircle.js
  src/helpers/walletProfileHandler.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useUpdateEmoji.ts
  src/hooks/useWebData.js
  src/model/preferences.ts
  src/model/wallet.ts
  src/redux/wallets.js
  src/screens/AvatarBuilder.js
Labels: QA later

#3445 Profiles: Fix SVG NFT avatars & filter out non-image NFTs
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
  src/components/asset-list/RecyclerAssetList2/index.tsx
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/handlers/opensea-api.ts
  src/helpers/assets.js
  src/helpers/buildWalletSections.js
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useExternalWalletSectionsData.ts
  src/hooks/useWalletSectionsData.js
  src/screens/SelectUniqueTokenSheet.tsx
  src/utils/index.ts
  src/utils/uniqueTokens.ts
Labels: profiles

#3448 kill session only if we are the ones disconnecting
  src/redux/walletconnect.js
Labels: blocker, merge when ready

#3454 Profiles: Fix avatar/cover resolution issues
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/handlers/ens.ts
  src/hooks/useENSModifiedRegistration.ts
Labels: profiles

#3453 Profiles: Fix issue where expanding an NFT would sometimes produce a duplicate
  src/handlers/ens.ts
  src/parsers/uniqueTokens.js
Labels: profiles

#3450 Profiles: Fix stale text record values
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles

#3434 Welcome screen adjustments
  src/languages/_english.json
  src/languages/_french.json
  src/screens/WelcomeScreen.js
Labels: needs dev review, merge when ready

#3413 Profiles: send ens flow gas
  src/handlers/ens.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/raps/registerENS.ts
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
Labels: profiles

#3458 Profiles: Prefetch ENS records for Edit Profile screen
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/hooks/index.js
  src/hooks/useENSProfileRecords.ts
  src/hooks/useOnAvatarPress.ts
  src/screens/ENSIntroSheet.tsx
  src/screens/SelectENSSheet.tsx
Labels: profiles

#3469 Another audit ci exception
  audit-ci.json
Labels: QA later, merge when ready

#3456 Profiles: new testflight version
  patches/@ethersproject+providers+5.6.8.patch
  src/screens/WalletScreen.js
Labels: profiles

#3468 Disable animations and gradients on ListSections for e2e
  src/components/discover-sheet/ListsSection.js
Labels: QA later, merge when ready

#3465 Swaps: Navigator entrypoints
  e2e/hardhatTransactionFlow.spec.js
  e2e/swapSheetFlow.spec.js
  src/components/AvailableNetworks.js
  src/components/exchange/CurrencySelectModalHeader.tsx
  src/components/fab/ExchangeFab.js
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
  src/helpers/ScrollPager.js
  src/hooks/useSwapCurrencyHandlers.js
  src/languages/_english.json
  src/navigation/ExchangeModalNavigator.js
  src/screens/CurrencySelectModal.js
  src/screens/ExchangeModal.js
  src/screens/ExplainSheet.js
  src/screens/SwapModal.js
Labels: swap-aggregator

#3467 ENS send flow e2e
  e2e/registerENSFlow.spec.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/fields/CheckboxField.tsx
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSModifiedRegistration.ts
  src/raps/registerENS.ts
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
  src/screens/WalletScreen.js
Labels: profiles

#3477 swap - bugz pass #1
  src/components/buttons/TokenSelectionButton.js
  src/components/exchange/ExchangeField.js
  src/components/exchange/ExchangeInputField.js
  src/components/exchange/ExchangeMaxButton.js
  src/components/exchange/ExchangeOutputField.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/hooks/useColorForAsset.js
  src/hooks/useSwapAdjustedAmounts.ts
  src/screens/ExchangeModal.js
Labels: merge when ready, swap-aggregator

#3482 swaps: android go to review fix
  src/components/exchange/ConfirmExchangeButton.js
  src/hooks/useSwapCurrencyHandlers.js
  src/languages/_english.json
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3479 Profiles: Fix ENS fallback when not available in subgraph yet
  src/handlers/ens.ts
  src/handlers/localstorage/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#3493 swaps - fix swap details crash
  src/components/expanded-state/swap-details/SwapDetailsContractRow.js
Labels: swap-aggregator

#3476 Show wallet ENS for watched wallets in dev menu
  src/components/settings-menu/DevNotificationsSection.tsx
Labels: QA later, notifications

#3492 Profiles: Remove ENS Expanded State Advanced Section
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/AdvancedSection.tsx
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
Labels: profiles

#3496 Profiles: Fix ENS Registration Intro screen blank section
  src/navigation/RegisterENSNavigator.tsx
Labels: needs dev review, QA later, profiles

#3502 Remove containsEmoji from dev menu for notifs
  src/components/settings-menu/DevNotificationsSection.tsx
Labels: QA later, notifications

#3491 [TEAM2-53] @rainbow-swaps / use route name to continue showing currency list
  src/screens/CurrencySelectModal.js
Labels: needs dev review

#3497 Disable Profiles sheet bounce
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
Labels: needs dev review, QA later, profiles

#3501 Profiles: Fix edit mode default state race condition
  src/hooks/useENSRegistrationForm.ts
Labels: profiles

#3500 Fix empty txn history regression
  src/redux/data.ts
Labels: needs dev review, blocker, QA later, release

#3481 Fix wrong tracked identifier in Performance metrics
  index.js
Labels: performance

#3511 Fix e2e
  e2e/deeplinks.spec.js
  e2e/sendSheetFlow.spec.js
  e2e/swapSheetFlow.spec.js
  src/components/settings-menu/DevSection.js
Labels: QA later, merge when ready

#3474 Profiles: Polish set primary name flows
  src/components/ens-registration/ConfirmContent/EditContent.tsx
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/ens-registration/index.tsx
  src/handlers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/raps/registerENS.ts
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles

#3506 Swaps: update `react-native-pager-view`
  ios/Podfile.lock
  package.json
  patches/@react-native-community+viewpager+5.0.5.patch
  patches/react-native-pager-view+5.4.24.patch
  src/navigation/ViewPagerAdapter.js
  yarn.lock
Labels: swap-aggregator

#3515 Profiles: Update explainers
  src/screens/ExplainSheet.js
Labels: profiles

#3471 swap - route picker
  ios/Images.xcassets/exchanges/0x.imageset/0x.png
  ios/Images.xcassets/exchanges/0x.imageset/Contents.json
  ios/Images.xcassets/exchanges/1inch.imageset/1inch.png
  ios/Images.xcassets/exchanges/1inch.imageset/Contents.json
  ios/Images.xcassets/exchanges/Both.imageset/Both.png
  ios/Images.xcassets/exchanges/Both.imageset/Contents.json
  ios/Images.xcassets/exchanges/Contents.json
  src/assets/exchanges/both.png
  src/assets/exchanges/oneinch.png
  src/assets/exchanges/zerox.png
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/hooks/index.js
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapSettings.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/ExchangeModalNavigator.js
  src/navigation/effects.js
  src/redux/swap.ts
Labels: merge when ready, swap-aggregator

#3514 Profiles: Use ens avatars in backup sheet
  src/components/contacts/ImageAvatar.js
  src/components/settings-menu/BackupSection/WalletSelectionView.js
Labels: profiles

#3460 Include pngs
  package.json
  src/utils/CoinIcons/CoinIcon.js
  src/utils/CoinIcons/CoinIcons.android.js
  src/utils/CoinIcons/CoinIcons.js
  yarn.lock
Labels: performance

#3522 swaps - add coin icon to output title
  src/components/exchange/CurrencySelectModalHeader.tsx
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator

#3513 swaps - setting currencies via route params
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/sheet/sheet-action-buttons/SwapActionButton.js
  src/hooks/useSwapCurrencyHandlers.js
  src/languages/_english.json
  src/redux/swap.ts
  src/screens/CurrencySelectModal.js
  src/screens/DepositModal.js
  src/screens/ExchangeModal.js
  src/screens/SavingsSheet.js
  src/screens/SwapModal.js
  src/screens/WithdrawModal.js
Labels: swap-aggregator

#3307 Fix: tx confirmation gas validations
  src/components/gas/GasSpeedButton.js
  src/hooks/useGas.ts
  src/redux/gas.ts
  src/screens/TransactionConfirmationScreen.js
Labels: needs dev review

#3517 Profiles: Fix issue where sending L2 asset on intro screen profile causes white screen
  src/hooks/useENSRegistrationCosts.ts
Labels: profiles

#3518 Profiles: Prevent temp image paths from being included in ens registration
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Labels: profiles

#3512 Adds high + medium slippage warning in swap settings
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/components/icons/svg/WarningIcon.js
  src/hooks/usePriceImpactDetails.ts
  src/languages/_english.json
Labels: swap-aggregator

#3504 M1 support on MacStadium
  .github/workflows/macstadium-e2e.yml
  e2e/discoverSheetFlow.spec.js
  e2e/hardhatTransactionFlow.spec.js
  e2e/newWalletFlow.spec.js
  e2e/registerENSFlow.spec.js
  e2e/sendSheetFlow.spec.js
  e2e/swapSheetFlow.spec.js
  ios/Podfile.lock
  package.json
  scripts/check-lockfile.sh
  scripts/postinstall.sh
  scripts/setup-ci.sh
  src/model/keychain.ts
  yarn.lock
Labels: merge when ready

#3520 Profiles: update avatars after registration
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#3535 [TEAM2-95] Swap review sheet -> more details: exchange row formatting
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
Labels: needs dev review, swap-aggregator

#3530 swaps: flashbots + confirmation button UI
  src/components/exchange/ConfirmExchangeButton.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3528 fix loading calc
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3532 Swaps: Polish more details animation
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/languages/_english.json
  src/languages/_french.json
Labels: swap-aggregator

#3536 Swaps: Fix android layout shift on the swap screen
  src/components/layout/KeyboardFixedOpenLayout.js
  src/helpers/keyboardTypes.ts
  src/hooks/useKeyboardHeight.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3519 Profiles: update react-native-pager-view
  ios/Podfile.lock
  package.json
  patches/@react-native-community+viewpager+5.0.5.patch
  patches/react-native-pager-view+5.4.24.patch
  src/navigation/ViewPagerAdapter.js
  yarn.lock
Labels: profiles

#3524 Fix Keyboard dismiss and Expanded Asset Sheet hiding
  src/components/expanded-state/UniqueTokenExpandedState.tsx
Labels: needs dev review, merge when ready, profiles

#3527 Profiles: Don't prefetch profile for non-ens NFTs
  src/components/expanded-state/UniqueTokenExpandedState.tsx
Labels: profiles

#3526 Profiles: Limit opensea api requests
  package.json
  src/handlers/opensea-api.ts
  src/rainbow-fetch/index.ts
  yarn.lock
Labels: profiles

#3313 Refactor BalanceCoinRow into FastBalanceCoinRow and FastCoinIcon
  patches/react-native-fast-image+8.5.11.patch
  src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
  src/components/asset-list/AssetList.js
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinBadge.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/asset-list/RecyclerAssetList2/WrapperBalanceCoinRow.tsx
  src/components/asset-list/RecyclerAssetList2/core/Contexts.ts
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
  src/components/asset-list/RecyclerAssetList2/index.tsx
  src/components/coin-divider/CoinDivider.js
  src/components/coin-icon/ChainBadge.js
  src/components/coin-icon/CoinIconIndicator.js
  src/components/coin-row/BalanceCoinRow.js
  src/debugging/useDependencyDebugger.ts
  src/helpers/assets.js
  src/hooks/useAccountAsset.js
  src/hooks/useAccountEmptyState.js
  src/hooks/useCoinListEditOptions.ts
  src/hooks/useCollectible.js
  src/hooks/useOpenSmallBalances.js
  src/hooks/useSavingsAccount.js
  src/hooks/useWalletSectionsData.js
  src/model/migrations.ts
  src/redux/data.ts
  src/redux/editOptions.js
  src/screens/CurrencySelectModal.js
  src/screens/ProfileSheet.tsx
  src/screens/SelectUniqueTokenSheet.tsx
  src/screens/SendSheet.js
  src/screens/WalletScreen.js
  src/utils/CoinIcons/FallbackIcon.js
  src/utils/getUrlForTrustIconFallback.ts
  src/utils/pseudoRandomArrayItemFromString.ts
Labels: needs dev review, android, performance

#3542 swaps: token network fixes
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/components/layout/KeyboardFixedOpenLayout.js
  src/hooks/useSwapCurrencyHandlers.js
  src/screens/CurrencySelectModal.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3540 Swap aggregator styling + copy updates
  src/components/exchange/ExchangeSearch.js
  src/languages/_english.json
Labels: swap-aggregator

#3539 [TEAM2-113] Swap token list sheet: no tokens on [network] explainer sheet is missing
  src/languages/_english.json
  src/screens/CurrencySelectModal.js
  src/screens/ExplainSheet.js
Labels: needs dev review, swap-aggregator

#3544 swaps - arbis warning cleanup
  src/hooks/useSwapCurrencyHandlers.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3326 Persist Imgix cache to MMKV
  src/handlers/imgix.ts
  src/model/mmkv.ts
Labels: performance

#3483 Fix Android chart label
  src/components/value-chart/ExtremeLabels.js
Labels: android

#3461 Remove Reanimated 1 from MarqueeList
  src/components/list/MarqueeList.js
Labels: needs dev review, performance

#3424 Remove easing prop from ButtonAnimation component usage
  src/components/avatar-builder/ColorCircle.js
Labels: needs dev review, performance

#3409 Migrate GestureBlocker to Reanimated 2
  src/components/GestureBlocker.js
Labels: needs dev review, performance

#3462 Migrate JellySelector to Reanimated 2
  src/components/jelly-selector/JellySelector.js
  src/components/jelly-selector/jelly-selector-indicator/JellySelectorColorIndicator.js
  src/components/jelly-selector/jelly-selector-indicator/JellySelectorShadowIndicator.js
Labels: needs dev review, performance

#3399 Replace Reanimated 1 with Reanimated 2 in SpinAnimation
  src/components/Spinner.tsx
  src/components/animations/SpinAnimation.js
  src/components/animations/SpinAnimation.tsx
  src/components/animations/index.js
Labels: needs dev review, performance

#3398 Remove old Reanimated 1 procs and helpers
  src/components/animations/ScaleInAnimation.js
  src/components/animations/index.js
  src/components/animations/procs/contains.js
  src/components/animations/procs/index.js
  src/components/animations/procs/math.js
  src/components/animations/procs/timing.js
  src/components/animations/procs/transformOrigin.js
  src/components/animations/procs/updateState.js
  src/navigation/SpringConfig.js
Labels: needs dev review, performance

#3554 Fix crash while searching on the list
  src/hooks/useUniswapCurrencyList.ts
Labels: needs dev review, QA later, merge when ready

#3494 swaps - e2e tweak
  audit-ci.json
  e2e/swapSheetFlow.spec.js
  src/components/exchange/ExchangeInput.js
  src/components/exchange/ExchangeNativeField.js
  src/components/exchange/ExchangeNotch.js
  src/screens/ExchangeModal.js
Labels: merge when ready, swap-aggregator

#3560 fix: avatar image picker
  src/hooks/useOnAvatarPress.ts
Labels: profiles

#3566 Fix e2e trigger
  .github/workflows/macstadium-e2e.yml
  package.json
  yarn.lock
Labels: QA later, merge when ready

#3410 Remove useTransformOrigin
  src/hooks/index.js
  src/hooks/useTransformOrigin.js
Labels: performance

#3550 swaps: output value fixed decimals
  src/helpers/utilities.ts
  src/hooks/useSwapDerivedOutputs.ts
Labels: swap-aggregator

#3561 [TEAM2-138] Switching to [network] sheet: sometimes the network is undefined
  src/hooks/useSwapCurrencyHandlers.js
Labels: needs dev review, swap-aggregator

#3427 Convert `src/helpers` to TypeScript with TS Migrate.
  src/helpers/RainbowContext.tsx
  src/helpers/ScrollPager.tsx
  src/helpers/__tests__/utilities.test.ts
  src/helpers/accountInfo.ts
  src/helpers/assetInputTypes.ts
  src/helpers/assetSelectors.ts
  src/helpers/assets.ts
  src/helpers/biometryTypes.ts
  src/helpers/buildTransactionsSectionsSelector.ts
  src/helpers/buildWalletSections.tsx
  src/helpers/currencySelectionTypes.ts
  src/helpers/currencyTypes.ts
  src/helpers/dappNameHandler.ts
  src/helpers/emojiHandler.ts
  src/helpers/exchangeModalTypes.ts
  src/helpers/findWalletWithAccount.ts
  src/helpers/isKeyboardOpen.ts
  src/helpers/isNativeStackAvailable.ts
  src/helpers/isNativeTransactionListAvailable.ts
  src/helpers/isRainbowTextAvailable.ts
  src/helpers/isReanimatedAvailable.ts
  src/helpers/networkInfo.ts
  src/helpers/samsung.ts
  src/helpers/savings.ts
  src/helpers/signingWallet.ts
  src/helpers/sortList.ts
  src/helpers/strings.ts
  src/helpers/support.ts
  src/helpers/time.ts
  src/helpers/toLocaleStringPolyfill.ts
  src/helpers/tokenSectionTypes.ts
  src/helpers/transactionActions.ts
  src/helpers/transactions.ts
  src/helpers/transformOriginAnimated.ts
  src/helpers/validators.ts
  src/helpers/walletBackupStepTypes.ts
  src/helpers/walletBackupTypes.ts
  src/helpers/walletConnectNetworks.ts
Labels: QA later

#3521 swaps - main swap sheet spec
  src/components/buttons/BiometricButtonContent.js
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
  src/components/discover-sheet/DiscoverSearch.js
  src/components/exchange/ConfirmExchangeButton.js
  src/components/exchange/ExchangeFloatingPanels.js
  src/components/exchange/ExchangeInputField.js
  src/components/exchange/ExchangeNotch.js
  src/components/exchange/ExchangeOutputField.js
  src/components/gas/GasSpeedButton.js
  src/components/layout/KeyboardFixedOpenLayout.js
  src/hooks/useDimensions.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.js
  yarn.lock
Labels: swap-aggregator

#3562 swaps - fix l2 fallback colors
  src/components/buttons/TokenSelectionButton.js
  src/components/exchange/ExchangeField.js
  src/hooks/useColorForAsset.js
Labels: swap-aggregator

#3339 Fix issue where auto adjust was crashing for low eth accounts
  src/hooks/useSwapInputHandlers.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: needs dev review, release

#3579 Fix not loading icons fro cloudinary on some phones
  src/handlers/cloudinary.ts
Labels: QA later, merge when ready

#3455 Migrate WelcomeScreen to TS and Reanimated 2
  src/components/animations/ButtonPressAnimation/types.ts
  src/components/icons/svg/RainbowText.js
  src/components/rainbows-background/RainbowsBackground.tsx
  src/components/rainbows-background/SingleRainbow.tsx
  src/components/rainbows-background/types.ts
  src/screens/WelcomeScreen.js
  src/screens/WelcomeScreen.tsx
Labels: needs dev review, performance

#3576 [TEAM2-154][RNBW-3894] Tokens list goes to loading state when going from token list to swap screen
  src/screens/CurrencySelectModal.js
Labels: needs dev review, swap-aggregator

#3574 Fix exchange rate in swap review modal
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
  src/components/expanded-state/swap-details/SwapDetailsPriceRow.js
  src/languages/_english.json
  src/screens/ExplainSheet.js
Labels: swap-aggregator

#3577 swaps: update flip behavior
  src/components/exchange/ExchangeDetailsRow.js
  src/hooks/useSwapCurrencyHandlers.js
  src/redux/swap.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3555 Swaps: Fix some keyboard issues
  src/components/expanded-state/swap-settings/InputPill.js
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/StepButtonInput.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/components/fab/ExchangeFab.js
  src/hooks/useMagicAutofocus.js
  src/navigation/ExchangeModalNavigator.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator

#3551 Profiles: ENS Search Sheet improvements
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/helpers/ens.ts
  src/hooks/useENSSearch.ts
Labels: profiles

#3586 swaps - revert discover input
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/components/discover-sheet/DiscoverSearchInput.js
Labels: swap-aggregator

#3585 swaps - fix input filtering
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator

#3525 Profiles: Support emoji avatars for ens owners w/o ens avatar
  src/components/discover-sheet/RegisterENSSection.tsx
  src/hooks/useAccountENSDomains.ts
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ENSIntroSheet.tsx
  src/screens/SelectENSSheet.tsx
Labels: profiles

#3556 Fix L2; Render ReactCoinIcon pngs in FastCoinIcon on Android too
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
  src/utils/CoinIcons/FallbackIcon.js
Labels: android, performance

#3591 fix: use getNetworkFromType in switch network explainer
  src/hooks/useSwapCurrencyHandlers.js
Labels: swap-aggregator

#3588 swaps: round max input
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapInputHandlers.ts
  src/redux/swap.ts
Labels: swap-aggregator

#3581 Fix missing params passing to send sheet on Android
  src/navigation/Routes.android.js
Labels: needs dev review, blocker, android

#3582 [TEAM2-159] Disable L2 favorites in token expanded state
  src/components/expanded-state/chart/ChartAddToListButton.js
  src/screens/AddTokenSheet.js
Labels: needs dev review, swap-aggregator

#3568 Swap review sheet UI updates
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/swap-details/CurrencyTile.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsContractRow.js
  src/components/expanded-state/swap-details/SwapDetailsMasthead.js
  src/components/expanded-state/swap-details/SwapDetailsRow.js
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/languages/_english.json
  src/screens/ExplainSheet.js
Labels: needs dev review, swap-aggregator

#3597 fix: rounding input on max to decimalPlaces
  src/helpers/utilities.ts
Labels: swap-aggregator

#3599 [TEAM2-3] Update Swap explain sheets copy
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/languages/_english.json
  src/screens/ExplainSheet.js
Labels: needs dev review, swap-aggregator

#3587 Fix image cache after introduction of images from Cloudinary
  src/handlers/imgix.ts
Labels: blocker

#3600 Swaps: Android layout fixes
  src/components/exchange/ExchangeNotch.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/components/expanded-state/swap-settings/SourcePicker.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
Labels: needs dev review, android, swap-aggregator

#3569 Profiles: Fix duplicate registrations
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/hooks/index.js
  src/hooks/useENSLocalTransactions.ts
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useENSSearch.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ENSSearchSheet.tsx
Labels: profiles

#3592 Profiles: Split up `useENSProfile` into separate hooks
  src/components/contacts/ContactRow.js
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/components/expanded-state/ContactProfileState.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/handlers/ens.ts
  src/handlers/localstorage/ens.ts
  src/hooks/index.js
  src/hooks/useAccountENSDomains.ts
  src/hooks/useENSAddress.ts
  src/hooks/useENSAvatar.ts
  src/hooks/useENSCover.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSOwner.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileImages.ts
  src/hooks/useENSProfileRecords.ts
  src/hooks/useENSRecords.ts
  src/hooks/useENSRegistrant.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useENSResolveName.ts
  src/hooks/useENSResolver.ts
  src/hooks/useImportingWallet.js
  src/hooks/useInitializeENSIntroData.ts
  src/hooks/useLoadAccountLateData.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useTrackENSProfile.ts
  src/redux/wallets.js
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSIntroSheet.tsx
  src/screens/ProfileSheet.tsx
  src/screens/SelectENSSheet.tsx
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
  src/screens/WalletScreen.js
Labels: profiles

#3541 Profiles: Fix nft upload flash when editing profile
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Labels: profiles

#3575 Profiles: Remove NFT avatar/cover option if no NFTs
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/hooks/useSelectImageMenu.tsx
  src/hooks/useWalletSectionsData.js
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles

#3420 Remove Reanimated 1 Transitions API usages
  src/components/add-cash/AddCashForm.tsx
  src/components/add-cash/AddCashStatus.js
  src/components/buttons/AddContactButton.js
  src/components/buttons/index.js
  src/components/change-wallet/WalletList.js
  src/components/exchange/CurrencySelectionList.js
  src/components/inputs/ClearInputDecorator.js
  src/components/layout/KeyboardFixedOpenLayout.js
  src/components/send/SendEmptyState.js
  src/components/sheet/SheetSubtitleCycler.tsx
  src/components/token-family/TokenFamilyWrap.js
  src/screens/AddCashSheet.js
Labels: needs dev review, performance

#3583 Profiles: Misc. fixes
  src/apollo/queries.ts
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/handlers/ens.ts
Labels: profiles

#3603 swaps - input price fallback
  src/hooks/useSwapDerivedOutputs.ts
Labels: swap-aggregator

#3604 swaps: fixes
  src/hooks/useSwapCurrencyHandlers.js
  src/hooks/useSwapDerivedOutputs.ts
  src/navigation/ExchangeModalNavigator.js
  src/redux/swap.ts
Labels: swap-aggregator

#3578 Delay closing sheet until we're done with keychain on android
  src/components/expanded-state/WalletProfileState.js
  src/model/wallet.ts
Labels: needs dev review

#3261 Use optional chaining instead of get from lodash
  src/App.js
  src/components/AddFundsInterstitial.js
  src/components/activity-list/RecyclerActivityList.js
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/asset-list/RecyclerViewTypes.js
  src/components/change-wallet/WalletList.js
  src/components/coin-row/BalanceCoinRow.js
  src/components/coin-row/ListCoinRow.js
  src/components/coin-row/TransactionCoinRow.js
  src/components/exchange/CurrencySelectionList.js
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/components/jelly-selector/JellySelector.js
  src/components/send/SendHeader.js
  src/components/settings-menu/LanguageSection.js
  src/components/value-chart/ExtremeLabels.js
  src/handlers/assets.ts
  src/handlers/uniswap.ts
  src/handlers/wyre.ts
  src/helpers/accountInfo.ts
  src/helpers/assetSelectors.ts
  src/helpers/assets.ts
  src/helpers/bigNumberFormat.ts
  src/helpers/buildTransactionsSectionsSelector.ts
  src/helpers/buildWalletSections.tsx
  src/helpers/transactions.ts
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/helpers/utilities.ts
  src/hooks/useWalletBalances.js
  src/model/firebase.js
  src/model/wallet.ts
  src/navigation/Navigation.js
  src/navigation/onNavigationStateChange.js
  src/parsers/gas.ts
  src/parsers/newTransaction.ts
  src/parsers/poap.js
  src/parsers/requests.js
  src/parsers/transactions.ts
  src/parsers/uniqueTokens.js
  src/redux/charts.ts
  src/redux/data.ts
  src/redux/fallbackExplorer.js
  src/redux/gas.ts
  src/redux/multicall.ts
  src/redux/requests.ts
  src/redux/settings.ts
  src/redux/walletconnect.js
  src/redux/wallets.js
  src/references/wyre/index.js
  src/screens/ChangeWalletSheet.js
  src/screens/SendConfirmationSheet.js
  src/screens/WalletScreen.js
  src/styles/buildTextStyles.js
  src/utils/ethereumUtils.ts
  src/utils/index.ts
  src/utils/isNewValueForPath.ts
Labels: performance

#3609 swaps: flipping behavior changes
  src/hooks/index.js
  src/hooks/useSwapCurrencyHandlers.js
  src/hooks/useSwapDerivedValues.ts
  src/redux/swap.ts
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3559 Fix issue where sending NFT would show error
  src/handlers/web3.ts
  src/utils/ethereumUtils.ts
Labels: needs dev review, blocker, critical path, team2

#3613 fix swap/savings rap types
  src/raps/common.ts
  src/raps/index.ts
  src/screens/ExchangeModal.js
Labels: release, team2

#3605 Profiles: Improve fetch of ens first tx timestamp
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/handlers/ens.ts
  src/handlers/localstorage/ens.ts
  src/hooks/index.js
  src/hooks/useENSFirstTransactionTimestamp.ts
  src/hooks/useFirstTransactionTimestamp.ts
  src/screens/ProfileSheet.tsx
Labels: profiles, team2

#3390 Remove lodash forEach from the codebase
  src/components/backup/RestoreSheetFirstStep.js
  src/helpers/assets.ts
  src/hooks/useWalletBalances.js
  src/model/backup.ts
  src/model/keychain.ts
  src/model/wallet.ts
  src/redux/multicall.ts
  src/redux/walletconnect.js
  src/screens/RestoreSheet.js
Labels: performance, team1

#3384 Remove lodash map from the codebase
  src/components/coin-divider/CoinDivider.js
  src/handlers/localstorage/removeWallet.ts
  src/helpers/buildTransactionsSectionsSelector.ts
  src/helpers/buildWalletSections.tsx
  src/helpers/uniswapLiquidityTokenInfoSelector.ts
  src/hooks/useMulticall.ts
  src/hooks/useSavingsAccount.js
  src/hooks/useSendSavingsAccount.js
  src/hooks/useUniswapCalls.ts
  src/hooks/useWalletsWithBalancesAndNames.js
  src/model/backup.ts
  src/parsers/gas.ts
  src/parsers/transactions.ts
  src/parsers/uniqueTokens.js
  src/raps/common.ts
  src/redux/addCash.ts
  src/redux/data.ts
  src/redux/fallbackExplorer.js
  src/redux/multicall.ts
  src/redux/optimismExplorer.js
  src/redux/topMovers.ts
  src/redux/uniswap.ts
  src/redux/uniswapLiquidity.ts
  src/redux/wallets.js
  src/screens/WalletScreen.js
Labels: performance, team1

#3607 swaps - extra height android explainers
  src/screens/ExplainSheet.js
Labels: swap-aggregator, team2

#3590 Fix issue where expanding an NFT would sometimes produce a duplicate
  src/handlers/ens.ts
  src/parsers/uniqueTokens.js
Labels: release, team2

#3621 Swap: Fix mainnet accent color
  src/styles/colors.ts
Labels: swap-aggregator, team2

#3614 [TEAM2-173] balances not updating after L2 swap
  src/App.js
Labels: swap-aggregator, team2

#3612 resolved explainer sheet capitalization typos
  src/languages/_english.json
Labels: swap-aggregator, team2

#3617 swaps: handle price impact warnings
  src/components/exchange/ExchangeDetailsRow.js
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3623 Swaps: Fix insufficient gas label
  src/components/exchange/ConfirmExchangeButton.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3615 Swaps: Align swap layout to spec
  src/components/exchange/AnimatedExchangeFloatingPanels.js
  src/components/exchange/ExchangeFloatingPanels.js
  src/screens/ExchangeModal.js
Labels: swap-aggregator, team2

#3625 swaps - auto adjust max for native assets
  e2e/swapSheetFlow.spec.js
  src/hooks/useSwapInputHandlers.ts
Labels: swap-aggregator, team2

#3463 Remove lodash pick and pickBy from the codebase
  src/components/context-menu/ContextMenu.ios.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/send/SendHeader.js
  src/components/settings-menu/LanguageSection.js
  src/components/token-family/CollectibleTokenFamily.js
  src/components/transaction-list/TransactionList.js
  src/components/unique-token/UniqueTokenRow.js
  src/design-system/typography/typography.ts
  src/handlers/localstorage/walletconnectRequests.ts
  src/handlers/localstorage/walletconnectSessions.ts
  src/helpers/time.ts
  src/helpers/utilities.ts
  src/hooks/useUniswapPools.js
  src/parsers/uniqueTokens.js
  src/redux/data.ts
  src/redux/optimismExplorer.js
  src/redux/walletconnect.js
  src/utils/index.ts
  src/utils/isNewValueForObjectPaths.ts
  src/utils/magicMemo.ts
Labels: performance, team1

#3628 swaps: fix NaN rainbow fee
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
Labels: swap-aggregator, team2

#3620 Fix swapping via exchanges alignment
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/helpers/utilities.ts
Labels: swap-aggregator, team2

#3610 Swap: Fix input debounce
  src/components/exchange/ExchangeField.js
  src/components/exchange/ExchangeNativeField.js
  src/hooks/useSwapCurrencyHandlers.js
Labels: swap-aggregator, team2
