Repository rainbow-me/rainbow, pull requests merged in 2022-02, with the labels that each got.

#2909 Fix transaction confirmation sheet
  src/screens/TransactionConfirmationScreen.js
Labels: needs dev review, QA later, android, merge when ready

#2813 improve gas time estimations
  src/components/gas/GasSpeedButton.js
  src/entities/gas.ts
  src/entities/index.ts
  src/parsers/gas.ts
  src/redux/gas.ts
Labels: needs dev review, needs QA

#2892 Profiles: ENS Registration Action Buttons
  ios/Podfile.lock
  ios/Rainbow.xcodeproj/project.pbxproj
  src/assets/dice.png
  src/assets/dice@2x.png
  src/assets/dice@3x.png
  src/components/buttons/TintButton.tsx
  src/design-system/typography/typeHierarchy.ts
  src/screens/RegisterEnsSheet.js
Labels: needs dev review, QA later, profiles

#2898 Design System: Add `Rows` layout component
  src/design-system/components/Rows/Rows.docs.tsx
  src/design-system/components/Rows/Rows.examples.tsx
  src/design-system/components/Rows/Rows.meta.ts
  src/design-system/components/Rows/Rows.playground.tsx
  src/design-system/components/Rows/Rows.tsx
  src/design-system/docs/components/CodePreview/index.tsx
  src/design-system/docs/components/DocsAccordion/index.tsx
  src/design-system/docs/docs.ts
  src/design-system/docs/types.ts
  src/design-system/index.ts
  src/design-system/layout/size.ts
  src/design-system/playground/Playground.tsx
Labels: needs dev review, QA later, design system

#2910 bump fast image + pods
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: needs dev review

#2907 bump branch
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: needs dev review

#2916 bump iOS
  CHANGELOG.md
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#2881 Adjust L2 tx wait time
  src/entities/gas.ts
  src/handlers/gasFees.ts
  src/parsers/gas.ts
  src/redux/gas.ts
Labels: QA later

#2906 bump sentry - add basic performance
  ios/Podfile.lock
  package.json
  src/App.js
  yarn.lock
Labels: needs dev review

#2789 [RNBW-1800] Move trending list and DPI to a backend package: dispersion
  src/components/discover-sheet/ListsSection.js
  src/entities/dispersion.ts
  src/entities/index.ts
  src/handlers/dispersion.ts
  src/hooks/useDPI.ts
  src/hooks/useUniswapAssetsInWallet.js
  src/hooks/useUniswapCurrencyList.ts
  src/hooks/useUniswapPools.js
  src/references/defisdk/adapterRegistryABI.json
  src/references/defisdk/index.ts
  src/references/index.ts
Labels: needs dev review, QA later

#2860 disable output currency focus
  src/components/exchange/ExchangeInputField.js
  src/components/exchange/ExchangeOutputField.js
  src/screens/ExchangeModal.js
Labels: needs dev review, QA later

#2876 ens registration search result indicators
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/components/ens-registration/index.tsx
  src/screens/RegisterEnsSheet.js
  src/styles/colors.js
Labels: needs dev review, QA later, profiles

#2911 @esteban/ens utils
  package.json
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSRegistration.ts
  src/references/ens/ENS.json
  src/references/ens/ENSBaseRegistrarImplementation.json
  src/references/ens/ENSRegistry.json
  src/references/ens/ENSRegistryWithFallback.json
  src/references/ens/ETHRegistrarController.json
  src/references/ens/ReverseRegistrar.json
  src/references/ens/index.ts
  src/references/index.ts
  src/screens/RegisterEnsSheet.js
  yarn.lock
Labels: profiles

#2593 Add more i18n tags (2/n).
  src/components/avatar-builder/Categories.android.js
  src/components/avatar-builder/Categories.js
  src/components/avatar-builder/EmojiSelector.js
  src/components/backup/BackupCloudStep.js
  src/components/backup/BackupConfirmPasswordStep.js
  src/components/backup/RestoreCloudStep.js
  src/components/backup/RestoreSheetFirstStep.js
  src/components/buttons/PasteAddressButton.js
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
  src/components/change-wallet/AddressRow.js
  src/components/coin-row/CoinRowInfoButton.js
  src/components/coin-row/ContractInteractionCoinRow.js
  src/components/coin-row/RequestCoinRow.js
  src/components/coin-row/TopMoverCoinRow.js
  src/components/coin-row/TransactionCoinRow.js
  src/components/discover-sheet/DiscoverSearch.js
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/components/discover-sheet/DiscoverSheetContent.js
  src/components/discover-sheet/ListsSection.js
  src/components/discover-sheet/PulseIndexSection.js
  src/components/discover-sheet/StrategiesSection.js
  src/components/discover-sheet/TopMoversSection.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/error-boundary/Fallback.tsx
  src/components/exchange/DepositInfo.js
  src/components/exchange/ExchangeAssetList.js
  src/components/exchange/ExchangeDetailsRow.js
  src/components/exchange/ExchangeMaxButton.js
  src/components/exchange/PriceImpactWarning.js
  src/components/expanded-state/LiquidityPoolExpandedState.js
  src/components/expanded-state/SupportedCountriesExpandedState.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/TokenIndexExpandedState.js
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/expanded-state/asset/SocialLinks.js
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
  src/components/expanded-state/swap-details/SwapDetailsContractRow.js
  src/components/expanded-state/swap-details/SwapDetailsPriceRow.js
  src/components/expanded-state/swap-details/SwapDetailsSlippageMessage.js
  src/components/expanded-state/swap-details/SwapDetailsUniswapRow.js
  src/components/fields/AddressField.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ImportSeedPhraseSheet.js
  src/screens/SettingsModal.js
Labels: needs dev review, QA later, merge when ready

#2872 [RNBW-2325] Move Uniswap Favorite Token Data to Account Loader
  src/entities/index.ts
  src/entities/uniswap.ts
  src/handlers/localstorage/uniswap.ts
  src/hooks/useUniswapCurrencyList.ts
  src/redux/uniswap.ts
  src/references/index.ts
Labels: needs dev review, QA later

#2875 Create `codegen-translations` script and update related files.
  .gitignore
  package.json
  scripts/codegen-translations.js
Labels: needs dev review, QA later

#2923 @benisgold/fix polygonscan error
  src/components/ContactRowInfoButton.js
  src/components/coin-row/CoinRowInfoButton.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/utils/ethereumUtils.ts
Labels: needs dev review, needs QA, merge when ready

#2905 Fix issue where scrolling down on switch wallet sheet wouldn't dismiss the sheet
  src/components/asset-list/EmptyAssetList.js
Labels: needs dev review, QA later

#2922 Make sure QR code scanner is always enabled
  src/components/qrcode-scanner/EmulatorPasteUriButton.js
  src/hooks/useScanner.js
Labels: needs dev review, QA later

#2793 Move `useAdditionalAssets` info to Dispersion
  src/apollo/queries.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/handlers/dispersion.ts
  src/helpers/bigNumberFormat.js
  src/helpers/bigNumberFormat.ts
  src/hooks/useAdditionalAssetData.ts
  src/redux/additionalAssetsData.ts
  src/redux/data.js
Labels: needs dev review, QA later, merge when ready

#2794 reenable price widgets w/ fixes
  ios/Podfile
  ios/Podfile.lock
  ios/PriceWidget/Base.lproj/SelectTokenIntent.intentdefinition
  ios/PriceWidget/Models/PriceData.swift
  ios/PriceWidget/PriceWidget.swift
  ios/PriceWidget/PriceWidgetView.swift
  ios/PriceWidget/Providers/CurrencyProvider.swift
  ios/PriceWidget/Utils/Constants.swift
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/SelectTokenIntent/IntentHandler.swift
  package.json
  src/components/settings-menu/CurrencySection.js
  yarn.lock
Labels: dependencies, QA later

#2855 Add back tabular-nums to chart price label
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
Labels: QA later

#2851 Hide search on hardware back button/gesture event
  src/components/discover-sheet/DiscoverSearch.js
  src/components/discover-sheet/DiscoverSearchContainer.js
  src/hooks/index.js
  src/hooks/useHardwareBack.ts
Labels: QA later, android, merge when ready

#2920 Fix wrong initial chart ratio of the chart percentage label
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
Labels: QA later, merge when ready

#2918 Profiles: Add inline validation for ENS search
  package.json
  src/components/buttons/TintButton.tsx
  src/design-system/typography/typeHierarchy.ts
  src/hooks/useENSRegistration.ts
  src/screens/RegisterEnsSheet.js
  src/utils/__tests__/validateENS.test.ts
  src/utils/index.ts
  src/utils/normalizeENS.ts
  src/utils/validateENS.ts
  yarn.lock
Labels: profiles

#2642 Migrate NFT expanded state to design system components
  src/components/L2Disclaimer.js
  src/components/Link.js
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/expanded-state/UniqueTokenExpandedState.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/sheet/sheet-action-buttons/SheetActionButton.js
  src/components/unique-token/UniqueTokenAttributes.js
  src/components/unique-token/UniqueTokenAttributes.tsx
  src/entities/assetTypes.ts
  src/entities/uniqueAssets.ts
  src/helpers/index.ts
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/index.ts
  src/navigation/routesNames.js
  src/navigation/useUntrustedUrlOpener.ts
  src/screens/ExternalLinkWarningSheet.tsx
  src/utils/formatURLForDisplay.ts
  src/utils/index.ts
  src/utils/magicMemo.ts
Labels: merge when ready

#2913 Profiles: Register ENS navigation foundation
  src/components/fab/RegisterEnsFab.js
  src/design-system/typography/typeHierarchy.ts
  src/navigation/RegisterENSNavigator.js
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/routesNames.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: needs dev review, profiles

#2921 Get rid of the white background while opening the app on android
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/me/rainbow/MainActivity.java
  android/app/src/main/res/drawable-hdpi/launch_screen.png
  android/app/src/main/res/drawable-mdpi/launch_screen.png
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxxhdpi/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  ios/Podfile.lock
  package.json
  src/hooks/useHideSplashScreen.js
  yarn.lock
Labels: needs dev review, QA later, android

#2930 fix styled-components ts alias
  tsconfig.json
Labels: needs dev review, merge when ready

#2932 new adaptive icons for android
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
Labels: QA later, android, merge when ready

#2934 Throw an error when css strings is used with styled components
  src/styled-thing/index.js
Labels: QA later, merge when ready

#2917 @benisgold/additional indicators
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/design-system/layout/space.ts
  src/helpers/utilities.ts
  src/hooks/useENSRegistration.ts
  src/screens/RegisterEnsSheet.js
Labels: needs dev review, QA later, profiles

#2935 @esteban/ens state manager
  src/helpers/ens.ts
  src/redux/ensRegistration.ts
Labels: needs dev review, profiles

#2937 @benisgold/profile screen nav buttons
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/helpers/ens.ts
  src/hooks/useENSRegistration.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSSearchSheet.js
Labels: needs dev review, merge when ready, profiles

#2815 [RNBW-2181] Make empty wallet UX even better
  src/components/asset-list/AssetList.js
  src/components/asset-list/EmptyAssetList.js
  src/handlers/localstorage/accountLocal.ts
  src/helpers/buildWalletSections.js
  src/hooks/useAccountEmptyState.js
  src/model/wallet.ts
  src/screens/WalletScreen.js
Labels: needs dev review, critical path

#2924 @esteban/network fee estimations
  package.json
  src/components/buttons/TintButton.tsx
  src/eth-ens-namehash.d.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/redux/gas.ts
  src/references/ens/ENS.json
  src/references/ens/ENSETHRegistrarController.json
  src/references/ens/ENSPublicResolver.json
  src/references/ens/ENSRegistry.json
  src/references/ens/ENSReverseRegistrar.json
  src/references/ens/index.ts
  src/references/ethereum-units.json
  src/references/index.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSSearchSheet.js
  yarn.lock
Labels: needs dev review, profiles

#2938 Profiles: Create ENS profile form
  src/components/buttons/MiniButton.js
  src/components/ens-registration/TextRecordsForm/SelectableButton.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/ens-registration/index.tsx
  src/components/inputs/InlineField.tsx
  src/design-system/layout/size.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSProfileForm.ts
  src/hooks/useENSRegistration.ts
  src/navigation/RegisterENSNavigator.js
  src/redux/ensRegistration.ts
  src/redux/reducers.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSSearchSheet.js
Labels: needs dev review, profiles

#2947 Profiles: ENS Registration – Review Costs UI
  package.json
  src/assets/brain.png
  src/assets/brain@2x.png
  src/assets/brain@3x.png
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/ens-registration/index.tsx
  src/components/inputs/InlineField.tsx
  src/helpers/__tests__/utilities.test.js
  src/helpers/ens.ts
  src/helpers/utilities.ts
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  src/screens/RegisterEnsSheet.js
  yarn.lock
Labels: needs dev review, profiles

#2952 Profiles: Fix issue where keyboard toggle wasn't showing on android
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#2944 Truncate wallet name in WC approval
  src/screens/WalletConnectApprovalSheet.js
Labels: needs dev review

#2936 Handle specific branch.io deeplinks
  package.json
  src/App.js
  src/utils/branch.ts
  yarn.lock
Labels: dependencies, needs dev review

#2949 Fix truncated wallet name on tx request screen
  src/screens/TransactionConfirmationScreen.js
Labels: needs dev review

#2933 Fix jumping profile header
  patches/recyclerlistview+3.0.5.patch
  src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
Labels: android, merge when ready

#2946 blur inputs for android cloud back up
  src/components/backup/BackupCloudStep.js
Labels: needs dev review, android

#2945 @benisgold/ens header
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/components/ens-registration/TextRecordsForm/SelectableButton.tsx
  src/hooks/useENSProfileForm.ts
  src/hooks/useENSRegistration.ts
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: needs dev review, merge when ready, profiles

#2940 [RNBW-2464] Favorites Fixes
  src/components/discover-sheet/ListsSection.js
  src/handlers/localstorage/uniswap.ts
  src/hooks/useUniswapCurrencyList.ts
  src/redux/uniswap.ts
  src/references/index.ts
Labels: needs dev review, blocker

#2948 Chore: Update React Query to v3
  package.json
  src/App.js
  src/hooks/useDPI.ts
  src/hooks/useLoadGlobalLateData.js
  src/hooks/useUniswapPools.js
  src/hooks/useWalletBalances.js
  src/react-query/queryClient.ts
  tsconfig.json
  yarn.lock
Labels: QA later

#2959 Audit: bump `url-parse`
  package.json
  yarn.lock
Labels: dependencies, needs dev review

#2956 @benisgold/confirm screen header
  src/design-system/components/private/ApplyShadow/AndroidShadow.tsx
  src/design-system/components/private/ApplyShadow/ApplyShadow.tsx
  src/design-system/components/private/ApplyShadow/IOSShadow.tsx
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: needs dev review, merge when ready, profiles

#2953 @esteban/txs raps
  src/entities/ensRegistration.ts
  src/entities/index.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileForm.ts
  src/hooks/useENSRegistrationCosts.ts
  src/raps/actions/ens.ts
  src/raps/actions/index.ts
  src/raps/common.ts
  src/raps/index.ts
  src/raps/registerENS.ts
  src/redux/ensRegistration.ts
  src/references/ethereum-units.json
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  src/screens/ExchangeModal.js
Labels: profiles

#2961 @benisgold/add image placeholders
  src/design-system/components/private/ApplyShadow/ApplyShadow.tsx
  src/screens/ENSAssignRecordsSheet.js
Labels: needs dev review, merge when ready, profiles

#2958 Profiles: Polish avatar/cover & add loading skeletons
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/skeleton/Skeleton.tsx
  src/design-system/layout/size.ts
  src/design-system/layout/space.ts
  src/hooks/useENSRegistrationCosts.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#2962 Convert ExternalLinkWarningSheet styles to object syntax
  src/screens/ExternalLinkWarningSheet.tsx
Labels: needs QA

#2965 bump ios
  CHANGELOG.md
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#2960 Fix reading env variables in android app
  android/app/build.gradle
Labels: needs dev review, QA later

#2967 ENS Registration: Upload Avatar/Cover
  ios/Podfile.lock
  package.json
  patches/react-native-image-crop-picker+0.37.3.patch
  patches/react-native-ios-context-menu+1.3.0.patch
  patches/react-native-ios-context-menu+1.7.4.patch
  src/components/Spinner.tsx
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/Avatar/Avatar.tsx
  src/components/ens-registration/Cover/Cover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/ens-registration/index.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/sheet/sheet-action-buttons/SheetActionButton.js
  src/components/svg/AvatarCoverPhotoMaskSvg.tsx
  src/handlers/pinata.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileForm.ts
  src/hooks/usePersistentDominantColorFromImage.ts
  src/hooks/useSelectImageMenu.tsx
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/utils/getDominantColorFromImage.ts
  yarn.lock
Labels: needs dev review, profiles

#2975 @esteban/more comments review
  package.json
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/raps/actions/ens.ts
  src/references/time-units.json
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#2980 Register ENS: Remove `useDebounceString` usage
  src/hooks/index.js
  src/hooks/useDebounceString.ts
  src/screens/ENSSearchSheet.js
Labels: profiles

#2969 ENS Registration: Choose NFT Avatar
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/asset-list/RecyclerAssetList2/core/Contexts.ts
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
  src/components/asset-list/RecyclerAssetList2/index.tsx
  src/components/ens-registration/Avatar/Avatar.tsx
  src/components/ens-registration/Cover/Cover.tsx
  src/config/experimental.ts
  src/hooks/useENSProfile.ts
  src/hooks/useSelectImageMenu.tsx
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/routesNames.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/SelectUniqueTokenSheet.tsx
  src/utils/index.ts
  src/utils/isENSNFTAvatar.ts
  src/utils/parseENSNFTAvatar.ts
  src/utils/stringifyENSNFTAvatar.ts
Labels: needs dev review, profiles

#2981 Convert src/styled-thing to typescript
  src/styled-thing/index.tsx
Labels: needs dev review, QA later, merge when ready
