Repository rainbow-me/rainbow, pull requests merged in 2022-03, with the labels that each got.

#2983 @benisgold/ens i18n
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/helpers/ens.ts
  src/hooks/useSelectImageMenu.tsx
  src/languages/_english.json
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: needs dev review, QA later, merge when ready, profiles

#2971 fix scanning QRs and adding wallets issue
  src/components/showcase/ShowcaseHeader.js
Labels: needs dev review, QA later, merge when ready

#2989 @benisgold/apply accent color
  src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
  src/components/gas/GasSpeedButton.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: needs dev review, QA later, merge when ready, profiles

#2978 @esteban/registration watcher
  src/entities/ensRegistration.ts
  src/entities/index.ts
  src/handlers/ens.ts
  src/handlers/localstorage/accountLocal.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileForm.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useLoadAccountData.js
  src/languages/_english.json
  src/raps/actions/depositCompound.ts
  src/raps/actions/ens.ts
  src/raps/actions/swap.ts
  src/raps/actions/unlock.ts
  src/raps/actions/withdrawCompound.ts
  src/raps/common.ts
  src/raps/index.ts
  src/raps/registerENS.ts
  src/redux/ensRegistration.ts
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ExchangeModal.js
  src/screens/ProfileScreen.js
Labels: needs dev review, profiles

#2994 @jxom/ens-form-onchange
  src/hooks/useENSProfileForm.ts
Labels: profiles

#2984 Profiles: Edit ENS Profile (part 1)
  package.json
  src/apollo/queries.js
  src/components/ens-registration/Avatar/Avatar.tsx
  src/components/ens-registration/Cover/Cover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/ens-avatar/README.md
  src/ens-avatar/src/index.ts
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/ens-avatar/src/specs/uri.ts
  src/ens-avatar/src/utils.ts
  src/entities/ensRegistration.ts
  src/handlers/ens.ts
  src/handlers/opensea-api.ts
  src/helpers/ens.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileForm.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/languages/_english.json
  src/navigation/RegisterENSNavigator.js
  src/navigation/config.js
  src/redux/ensRegistration.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  tsconfig.json
  yarn.lock
Labels: WIP, profiles

#2993 Fix NFT double tap to zoom no longer zooms to tapped coordinates
  src/components/expanded-state/unique-token/ZoomableWrapper.js
Labels: needs dev review, QA later, merge when ready

#3001 Bump url-parse
  package.json
  yarn.lock
Labels: dependencies, QA later, merge when ready

#2931 Upgrade reanimated to 2.4.1
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+2.2.3.patch
  patches/react-native-reanimated+2.4.1.patch
  src/components/exchange/ExchangeSearch.js
  src/components/value-chart/Chart.js
  src/helpers/ScrollPager.js
  src/hooks/useAnimatedPageScrollHandler.ts
  src/navigation/ViewPagerAdapter.js
  src/react-native-animated-charts/src/charts/linear/ChartDot.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  yarn.lock
Labels: dependencies, needs dev review

#2972 only disable touch events for video NFTs
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
Labels: needs dev review, QA later

#3000 Ultimately get rid of old icon designs on Android
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: needs dev review, QA later, android, merge when ready

#2992 @benisgold/restrict watching wallets
  src/components/fab/RegisterEnsFab.js
Labels: needs dev review, QA later, merge when ready, profiles

#2955 Add scale animations buttons patch
  patches/react-native-gesture-handler+1.10.3.patch
Labels: android

#3002 Profiles: Use `changedRecords` for commit phase
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#2998 Fix Top Movers Error Message
  src/redux/topMovers.ts
Labels: QA later

#2995 @benisgold/fix bio android
  src/components/inputs/InlineField.tsx
  src/languages/_english.json
Labels: profiles

#2976 Android NFT preview
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
Labels: needs dev review, android

#3005 Fix Synthetix on Optimism
  src/redux/optimismExplorer.js
  src/references/chain-assets.json
Labels: needs dev review, QA later

#3006 Profiles: Fix Edit ENS for ENS' with no records
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/hooks/useENSProfileForm.ts
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3007 Fix downloaded NFTs from Google User Content being low res
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/utils/getFullResUrl.ts
  src/utils/getLowResUrl.ts
Labels: QA later

#3014 re add allowlisted vulns
  audit-ci.json
Labels: blocker, merge when ready

#3015 audit again 🙃
  audit-ci.json
Labels: merge when ready

#3012 fix visibility for dev settings
  src/components/settings-menu/SettingsSection.js
Labels: needs dev review, blocker, merge when ready

#3009 update env example
  .env.example
Labels: needs dev review, merge when ready

#2997 Profiles: ENS Expanded State
  package.json
  shim.js
  src/apollo/queries.ts
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/Avatar/Avatar.tsx
  src/components/ens-registration/Cover/Cover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/AdvancedSection.tsx
  src/components/expanded-state/ens/ConfigurationSection.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
  src/components/icons/Icon.js
  src/components/icons/svg/DiscordIcon.js
  src/components/icons/svg/GitHubIcon.js
  src/components/icons/svg/InstagramIcon.js
  src/components/icons/svg/SnapchatIcon.js
  src/components/icons/svg/TwitterIcon.js
  src/components/inputs/InlineField.tsx
  src/components/text/Emoji.js
  src/entities/ensRegistration.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/index.js
  src/hooks/useENSProfile.ts
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useENSSearch.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/RegisterENSNavigator.js
  src/react-query/types.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  src/screens/ExplainSheet.js
  src/screens/ExternalLinkWarningSheet.tsx
  src/utils/index.ts
  src/utils/labelhash.ts
  yarn.lock
Labels: profiles

#3004 @esteban/edit profiles to transactions
  src/handlers/ens.ts
  src/handlers/web3.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/raps/common.ts
  src/raps/index.ts
  src/raps/registerENS.ts
  src/redux/ensRegistration.ts
  src/screens/ENSConfirmRegisterSheet.js
Labels: needs dev review, profiles

#3025 Profiles: Dark mode fixes for ENS registration
  src/components/ens-registration/Cover/Cover.tsx
  src/styles/colors.js
Labels: profiles

#3010 allow ENS edition only for controller
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/handlers/ens.ts
Labels: profiles

#3018 Fix BackupSheet shadow & fix Discover btn padding
  src/components/backup/BackupSheetSection.js
  src/components/header/DiscoverHeaderButton.js
Labels: needs dev review, QA later, android

#3031 @benisgold/reverse record check
  src/handlers/ens.ts
Labels: profiles

#3019 Profiles: ENS Registration – Add field validation
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/helpers/ens.ts
  src/hooks/useENSRegistrationForm.ts
  src/languages/_english.json
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3017 bump fastlane
  ios/Gemfile.lock
Labels: merge when ready

#3013 smol ens typo
  src/hooks/useENSRegistration.ts
Labels: needs dev review, merge when ready

#3033 profiles: two step flow screens & reverse records
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/languages/_english.json
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: profiles

#3035 profiles: handle resolver when editing profile
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/raps/actions/ens.ts
  src/raps/common.ts
Labels: profiles

#3036 use accent color for gas speed button and custom gas
  src/components/gas/GasSpeedButton.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3041 Fix mp3 nft
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
Labels: needs dev review, blocker, QA later, android

#2990 Update 4bytes API usage
  src/apollo/client.js
  src/apollo/client.ts
  src/apollo/queries.js
  src/handlers/transactions.ts
Labels: needs dev review, QA later

#3023 Track unrecognized URLs
  src/handlers/deeplinks.ts
Labels: needs dev review, QA later

#3026 Profiles: Profile Sheet (without asset list)
  src/components/discover-sheet/DiscoverSearch.js
  src/components/ens-profile/ActionButtons/ActionButtons.tsx
  src/components/ens-profile/ActionButtons/MoreButton.tsx
  src/components/ens-profile/ActionButtons/SendButton.tsx
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/components/ens-profile/GradientOutlineButton/GradientOutlineButton.tsx
  src/components/ens-profile/MoreButton/MoreButton.tsx
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/index.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/handlers/ens.ts
  src/hooks/index.js
  src/hooks/useDeleteWallet.ts
  src/hooks/useENSRecordDisplayProperties.tsx
  src/hooks/useWatchWallet.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/routesNames.js
  src/screens/ChangeWalletSheet.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ProfileSheet.tsx
  src/styles/colors.js
  src/utils/doesWalletsContainAddress.ts
  src/utils/ethereumUtils.ts
  src/utils/index.ts
Labels: profiles

#3046 Profiles: ENS call-to-action banner placeholder
  src/components/discover-sheet/DiscoverHome.js
  src/components/discover-sheet/RegisterENSSection.tsx
  src/components/fab/RegisterEnsFab.js
  src/components/fab/index.js
  src/components/icons/svg/ENSIcon.js
  src/languages/_english.json
  src/screens/WalletScreen.js
  src/styles/colors.js
Labels: profiles

#3042 @esteban/speed up commit
  src/entities/index.ts
  src/hooks/index.js
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useTransactions.ts
  src/redux/ensRegistration.ts
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/SpeedUpAndCancelSheet.js
Labels: profiles

#3047 Profiles: Defer image upload
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useSelectImageMenu.tsx
Labels: profiles

#3043 Sort connected dapps by most recent handshake
  src/components/walletconnect-list/WalletConnectListItem.js
  src/hooks/useWalletConnectConnections.js
  src/screens/ConnectedDappsSheet.js
Labels: needs dev review, needs QA

#3050 @benisgold/fix multiline spillage
  src/components/inputs/InlineField.tsx
Labels: profiles

#3056 Fix zoomable wrappers issues
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/utils/getLowResUrl.ts
Labels: QA later, merge when ready

#3053 Organize MMKV storage IDs
  src/components/settings-menu/DevSection.js
  src/handlers/localstorage/accountLocal.ts
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
  src/model/mmkv.ts
Labels: needs dev review, QA later, merge when ready

#3059 Remove `rainbow-token-list` as a dependency
  package.json
  yarn.lock
Labels: needs dev review, QA later

#3058 @benisgold/widget regression fixes
  ios/PriceWidgetExtension.entitlements
  ios/Rainbow/Rainbow.entitlements
  ios/Rainbow/RainbowDebug.entitlements
  ios/Rainbow/RainbowRelease.entitlements
  ios/SelectTokenIntent/SelectTokenIntent.entitlements
  src/redux/settings.ts
Labels: needs dev review, merge when ready, nice for release

#3057 Revert audit-ci changes
  audit-ci.json
Labels: merge when ready

#3065 handle null images
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
Labels: needs dev review, blocker, merge when ready

#3062 sanitize expanded state description
  src/components/expanded-state/asset/ChartExpandedState.js
Labels: needs dev review, merge when ready

#3054 Update Android notification icons
  android/app/src/main/res/mipmap-hdpi/ic_state_ic_notification.png
  android/app/src/main/res/mipmap-ldpi/ic_state_ic_notification.png
  android/app/src/main/res/mipmap-mdpi/ic_state_ic_notification.png
  android/app/src/main/res/mipmap-xhdpi/ic_state_ic_notification.png
  android/app/src/main/res/mipmap-xxhdpi/ic_state_ic_notification.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_state_ic_notification.png
Labels: needs dev review, QA later

#3024 round last sale price
  src/components/expanded-state/UniqueTokenExpandedState.tsx
Labels: needs dev review, needs design review, merge when ready

#3071 the auditoooor
  audit-ci.json
Labels: needs dev review, merge when ready

#3070 Clean MMKV AspectRatio / dominant color
  src/model/migrations.ts
Labels: needs dev review, QA later

#3061 disable redundant expanded state haptics
  src/components/token-info/TokenInfoItem.js
Labels: needs dev review, needs QA, merge when ready

#3020 [RNBW-2749] Skeleton flashes
  package.json
  patches/@react-native-community+masked-view+0.1.10.patch
  src/components/buttons/rainbow-button/RainbowButton.js
  src/components/buttons/rainbow-button/RainbowButtonBackground.js
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/components/exchange/CurrencySelectionList.js
  src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.js
  src/components/numpad/NumpadValue.js
  src/components/skeleton/Skeleton.tsx
  src/components/text/GradientText.js
  src/navigation/onNavigationStateChange.js
  src/screens/WelcomeScreen.js
  yarn.lock
Labels: dependencies, QA later, merge when ready

#3076 Revert "round last sale price"
  src/components/expanded-state/UniqueTokenExpandedState.tsx
Labels: blocker

#3072 [RNBW-2458][RNBW-2140][RNBW-2873] UI is mixing up my wallet balances
  src/redux/data.ts
Labels: needs dev review, needs QA

#3080 fix bad default logic
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
Labels: needs dev review, blocker

#3083 @benisgold/create profile button
  src/hooks/useOnAvatarPress.ts
Labels: profiles

#3089 bump it + audit
  CHANGELOG.md
  android/app/build.gradle
  audit-ci.json
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#3082 Profiles: On-chain text records data warning
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ExplainSheet.js
Labels: profiles

#3073 Profiles: check enough eth for registration
  src/hooks/useENSRegistrationCosts.ts
  src/languages/_english.json
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3051 Profiles: e2e
  e2e/discoverSheetFlow.spec.js
  e2e/hardhatTransactionFlow.spec.js
  e2e/registerENSFlow.spec.js
  package.json
  src/components/animations/CheckmarkAnimation.js
  src/components/animations/HourglassAnimation.js
  src/components/animations/index.js
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/buttons/TintButton.tsx
  src/components/discover-sheet/RegisterENSSection.tsx
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
  src/components/ens-registration/TextRecordsForm/SelectableButton.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/hooks/useENSRegistrationActionHandler.ts
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  tsconfig.json
Labels: profiles

#3098 Fix plist and minimist
  package.json
  yarn.lock
Labels: needs dev review, QA later, merge when ready

#3092 update polygon allowlist
  src/references/polygon-allowlist.json
Labels: needs dev review, merge when ready

#3101 Bump react-native/ detox / react-native-firebase
  ios/Podfile.lock
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  patches/react-native+0.66.4.patch
  yarn.lock
Labels: QA later, merge when ready

#3067 Repeat hiding CloseBtn in WyreWebview
  src/screens/WyreWebview.js
Labels: needs dev review, QA later, android

#3068 Fix jelly selector on Android
  src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
  src/components/jelly-selector/JellySelector.js
Labels: QA later, android

#3100 Profiles: some bug fixes
  src/config/index.ts
  src/handlers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3066 Remove unused dependencies
  ios/Podfile.lock
  package.json
  patches/rn-dominant-color+1.7.0.patch
  yarn.lock
Labels: needs dev review, QA later, merge when ready

#3079 round last sale price
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/entities/uniqueAssets.ts
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
Labels: needs dev review, merge when ready

#3032 Tx arbitrum
  src/components/coin-row/TransactionCoinRow.js
  src/config/experimental.ts
  src/entities/transactions/zerionTransaction.ts
  src/parsers/newTransaction.ts
  src/parsers/transactions.ts
  src/redux/data.ts
  src/redux/explorer.js
Labels: needs dev review, QA later

#3102 add clear cache to user dev
  src/components/settings-menu/UserDevSection.js
Labels: needs dev review

#3108 Profiles: fix e2e
  e2e/registerENSFlow.spec.js
Labels: profiles

#3109 Set up codepush
  android/app/build.gradle
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/res/values/strings.xml
  audit-ci.json
  ios/Podfile.lock
  ios/Rainbow/AppDelegate.mm
  ios/Rainbow/Info.plist
  package.json
  scripts/postinstall.sh
  src/App.js
  src/components/AppVersionStamp.js
  src/components/settings-menu/DevSection.js
  src/hooks/useAppVersion.js
  src/hooks/useSendFeedback.js
  yarn.lock
Labels: QA later, merge when ready

#3112 Profiles: fix expanded state in name with strange characters
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Labels: profiles

#3119 Profiles: go to profile on avatar press android
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
Labels: profiles

#3114 Fix issue where zoomable wrapper wasn't respecting scroll position on Android
  src/components/sheet/SlackSheet.js
Labels: needs dev review, QA later

#3113 Profiles: 60 secs wait from COMMIT tx
  e2e/registerENSFlow.spec.js
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#3129 Add layer3 polygon NFT to allowlist
  src/references/polygon-allowlist.json
Labels: merge when ready

#3128 use slug instead of family
  src/utils/buildRainbowUrl.ts
Labels: needs dev review, merge when ready
