Repository rainbow-me/rainbow, pull requests merged in 2022-09, with the labels that each got.

#4052 Fix slow image loading
  src/components/send/SendAssetList.js
  src/helpers/buildWalletSections.tsx
Labels: team1

#4117 Version bump iOS v.1.7.4 & Android 144
  CHANGELOG.md
  android/app/build.gradle
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#3990 Remove long press on address in switching wallets
  src/components/change-wallet/AddressRow.js
  src/components/native-context-menu/contextMenu.android.js
Labels: android, merge when ready, team1, dev QA

#4012 backup PIN
  src/components/backup/RestoreCloudStep.js
  src/handlers/authentication.ts
  src/model/backup.ts
Labels: needs dev review, android

#4046 Profiles: use `name` text record instead of `me.rainbow.displayName`
  e2e/registerENSFlow.spec.js
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSRegistrationForm.ts
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles, team2

#4112 swaps: fix native input cursor color
  src/components/exchange/ExchangeInputField.js
  src/components/exchange/ExchangeNativeField.js
Labels: swap-aggregator, team2, dev QA

#4088 analytics: add tracking for screen dimensions + fix nav events on android
  src/App.js
  src/navigation/onNavigationStateChange.js
Labels: nice for release, analytics, team2

#4086 🏛 GraphQL Clients/Codegen Foundations
  .eslintignore
  .eslintrc.js
  .gitignore
  package.json
  src/graphql/.eslintrc.js
  src/graphql/README.md
  src/graphql/codegen.config.js
  src/graphql/config.js
  src/graphql/index.ts
  src/graphql/package.json
  src/graphql/queries/ens.graphql
  src/graphql/queries/metadata.graphql
  src/graphql/utils/getFetchRequester.ts
  src/graphql/yarn.lock
  yarn.lock
Labels: team1, team2, dev QA

#4067 Profiles: Support contenthash
  e2e/registerENSFlow.spec.js
  package.json
  shim.js
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/entities/ensRegistration.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSRecords.ts
  src/raps/actions/ens.ts
  src/raps/common.ts
  src/screens/ENSIntroSheet.tsx
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
  yarn.lock
Labels: profiles, team2

#4097 icons on android
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  package.json
  patches/react-native-change-icon+3.2.0.patch
  patches/react-native-change-icon+4.0.0.patch
  src/App.js
  src/components/settings-menu/SettingsSection.tsx
  src/languages/_english.json
  src/redux/settings.ts
  yarn.lock
Labels: needs design review, android, team1

#4132 Fix issue with Collectibles not showing if opensea doesn't return consideration
  src/parsers/uniqueTokens.js
Labels: team2, dev QA, rc-v1.7.4

#4126 [TEAM2-488] Disable wyre with remote config
  src/assets/theMerge.png
  src/assets/theMerge@2x.png
  src/assets/theMerge@3x.png
  src/components/AddFundsInterstitial.js
  src/components/profile/ProfileMasthead.js
  src/components/transaction-list/TransactionList.js
  src/languages/_english.json
  src/languages/_french.json
  src/model/config.ts
  src/screens/ExplainSheet.js
Labels: team2, dev QA, the-merge, rc-v1.7.4

#3699 Enable local storage caching on Android
  shim.js
  src/handlers/localstorage/mmkvStorageBackend.ts
  src/model/mmkv.ts
Labels: android, performance, team1

#4109 swaps: new networks available
  src/components/coin-icon/ChainBadge.js
  src/components/exchange/CurrencySelectModalHeader.tsx
  src/components/expanded-state/AvailableNetworks.js
  src/components/expanded-state/AvailableNetworksv2.tsx
  src/components/expanded-state/asset/ChartExpandedState.js
  src/entities/dispersion.ts
  src/hooks/useAdditionalAssetData.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: swap-aggregator, team2, dev QA

#4111 swaps: network switcher v2
  src/components/exchange/NetworkSwitcher.js
  src/components/exchange/NetworkSwitcherv2.tsx
  src/screens/CurrencySelectModal.js
Labels: swap-aggregator, team2, dev QA

#4134 fix the merge explainer height
  src/model/config.ts
  src/screens/ExplainSheet.js
Labels: dev QA, rc-v1.7.4

#4130 fix: Use new endpoint for discovering wallets
  src/model/wallet.ts
  src/utils/ethereumUtils.ts
Labels: critical path, team2, dev QA

#4093 fix clipped subheader on Backup sheets
  src/screens/SettingsSheet.tsx
Labels: notifications, team2, dev QA

#4141 add wyre degradation explainer to buy action buttons
  src/components/sheet/sheet-action-buttons/BuyActionButton.js
Labels: dev QA, rc-v1.7.4

#4146 Watch wallet backup scenario
  src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx
  src/components/settings-menu/BackupSection/NeedsBackupView.tsx
  src/screens/SettingsSheet.tsx
Labels: rc-v1.7.4

#4115 Fix stuck WalletProfileState
  src/components/expanded-state/WalletProfileState.js
  src/model/wallet.ts
  src/screens/ChangeWalletSheet.js
Labels: needs dev review, android, team1

#4147 Revert backup PIN
  src/components/backup/RestoreCloudStep.js
  src/handlers/authentication.ts
  src/model/backup.ts
Labels: rc-v1.7.4

#4110 fix: gas fee params + DS / TS migration of gas components
  src/components/asset-list/RecyclerAssetList/index.tsx
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesGweiInput.tsx
  src/components/expanded-state/custom-gas/FeesPanel.tsx
  src/components/expanded-state/custom-gas/FeesPanelTabs.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
  src/components/expanded-state/custom-gas/GweiInputPill.js
  src/components/expanded-state/custom-gas/GweiInputPill.tsx
  src/components/gas/GasSpeedButton.js
  src/entities/gas.ts
  src/handlers/opensea-api.ts
  src/helpers/buildWalletSections.tsx
  src/hooks/useGas.ts
  src/languages/_english.json
  src/languages/_french.json
  src/parsers/gas.ts
  src/raps/actions/depositCompound.ts
  src/raps/actions/ens.ts
  src/raps/actions/swap.ts
  src/raps/actions/unlock.ts
  src/raps/actions/withdrawCompound.ts
  src/redux/gas.ts
  src/screens/SpeedUpAndCancelSheet.js
Labels: critical path, team2, rc-v1.7.5

#4157 chore: run lint and Prettier on all branches in CI, apply fixes
  .github/workflows/macstadium-e2e.yml
  .prettierignore
  bitrise.yml
  package.json
  src/components/expanded-state/custom-gas/FeesPanel.tsx
  src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
  src/components/expanded-state/custom-gas/GweiInputPill.tsx
  src/graphql/README.md
  src/languages/_english.json
  src/languages/_french.json
Labels: dev QA

#4152 Fix default account selection
  src/redux/wallets.ts
Labels: merge when ready

#4161 fix: gas context menu max fee
  src/components/expanded-state/custom-gas/GweiInputPill.tsx
  src/components/gas/GasSpeedButton.js
Labels: team2, dev QA

#4014 Convert Swap Screen components to TS and new DS primitives
  src/campaigns/swapsPromoCampaign.ts
  src/components/exchange/AnimatedExchangeFloatingPanels.tsx
  src/components/exchange/DepositInfo.tsx
  src/components/exchange/ExchangeDetailsRow.tsx
  src/components/exchange/ExchangeField.tsx
  src/components/exchange/ExchangeFloatingPanels.js
  src/components/exchange/ExchangeFloatingPanels.tsx
  src/components/exchange/ExchangeHeader.js
  src/components/exchange/ExchangeHeader.tsx
  src/components/exchange/ExchangeInputField.tsx
  src/components/exchange/ExchangeMaxButton.js
  src/components/exchange/ExchangeMaxButton.tsx
  src/components/exchange/ExchangeNativeField.tsx
  src/components/exchange/ExchangeNotch.tsx
  src/components/exchange/ExchangeOutputField.tsx
  src/components/exchange/PriceImpactWarning.js
  src/components/exchange/PriceImpactWarning.tsx
  src/components/exchange/index.ts
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
  src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/components/floating-panels/FloatingPanel.js
  src/components/floating-panels/FloatingPanel.tsx
  src/components/icons/DoubleChevron.tsx
  src/components/layout/KeyboardFixedOpenLayout.js
  src/components/layout/KeyboardFixedOpenLayout.tsx
  src/components/promos/InfoRow.tsx
  src/components/promos/PromoSheet.tsx
  src/components/secret-display/SecretDisplayCard.tsx
  src/entities/index.ts
  src/entities/nativeCurrencyTypes.ts
  src/entities/tokens.ts
  src/entities/transactions/transaction.ts
  src/featuresToUnlock/unlockableAppIconCheck.ts
  src/hooks/useColorForAsset.ts
  src/hooks/useGas.ts
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapInputRefs.ts
  src/parsers/transactions.ts
  src/raps/common.ts
  src/redux/data.ts
  src/screens/ExchangeModal.tsx
  src/screens/SwapsPromoSheet.tsx
Labels: swap-aggregator, team2

#4169 Fix optimism dupe assets
  src/references/chain-assets.json
Labels: needs dev review, merge when ready, dev QA

#4173 Fix import wallet modal padding
  src/components/floating-panels/FloatingPanel.tsx
Labels: release, merge when ready, dev QA

#4174 Use SimpleHash's nft_url and marketplace_id fields instead of matching on marketplace name
  src/components/unique-token/Tag.js
  src/components/unique-token/UniqueTokenAttributes.tsx
  src/entities/uniqueAssets.ts
  src/handlers/ens.ts
  src/handlers/simplehash.ts
  src/navigation/useUntrustedUrlOpener.ts
  src/parsers/uniqueTokens.js
Labels: team2, dev QA

#4102 Notifications: edit wallet context menu
  e2e/registerENSFlow.spec.js
  src/components/change-wallet/AddressRow.js
  src/components/change-wallet/AddressRow.tsx
  src/components/change-wallet/WalletList.tsx
  src/components/change-wallet/WalletOption.tsx
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ChangeWalletSheet.tsx
Labels: notifications, team2, dev QA

#4170 Use same check for unique tokens on polygon as ETH mainnet
  src/parsers/uniqueTokens.js
Labels: team2, dev QA

#4183 Add extra USD amount calculation and add explicit check invalid values for analytics
  src/screens/ExchangeModal.tsx
Labels: analytics, team2, dev QA

#4181 gas: UI alignments and tweaks
  src/components/expanded-state/CustomGasState.js
  src/components/expanded-state/custom-gas/FeesGweiInput.tsx
  src/components/expanded-state/custom-gas/FeesPanel.tsx
  src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
  src/components/expanded-state/custom-gas/GweiInputPill.tsx
Labels: release, dev QA, rc-v1.7.7

#4180 🏛 Migrate `useENSAddress` to Async State RFC
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/handlers/ens.ts
  src/hooks/index.ts
  src/hooks/useENSProfile.ts
  src/resources/ens/ensAddressQuery.ts
  src/resources/transactions/firstTransactionTimestampQuery.ts
  src/screens/ProfileSheet.tsx
Labels: dev QA

#3917 Bump `react-native-safe-area-context`
  ios/Podfile.lock
  package.json
  src/components/asset-list/AssetList.js
  src/components/asset-list/EmptyAssetList.js
  src/components/asset-list/RecyclerAssetList2/core/useLayoutItemAnimator.ts
  src/components/discover-sheet/DiscoverSheet.android.js
  src/components/layout/KeyboardFixedOpenLayout.tsx
  src/components/layout/Page.js
  src/components/modal/Modal.js
  src/components/sheet/Sheet.js
  src/components/sheet/SlackSheet.js
  src/components/toasts/Toast.tsx
  src/components/walletconnect-list/WalletConnectList.js
  src/navigation/Routes.android.js
  src/screens/AddCashSheet.js
  src/screens/AddTokenSheet.js
  src/screens/ConnectedDappsSheet.js
  src/screens/ExpandedAssetSheet.js
  src/screens/ExplainSheet.js
  src/screens/ExternalLinkWarningSheet.tsx
  src/screens/ModalScreen.js
  src/screens/SavingsSheet.js
  src/screens/SendConfirmationSheet.tsx
  src/screens/SettingsSheet.tsx
  src/screens/WelcomeScreen.tsx
  yarn.lock
Labels: needs dev review, team1

#4098 Detox on Android
  .detoxrc.js
  .github/workflows/macstadium-android-e2e.yml
  android/app/src/main/res/xml/network_security_config.xml
  e2e/deeplinks.spec.js
  e2e/discoverSheetFlow.spec.js
  e2e/hardhatTransactionFlow.spec.js
  e2e/hardhatTransactionFlowSendAndWC.spec.js
  e2e/hardhatTransactionFlowSwaps.spec.js
  e2e/helpers.js
  e2e/hiddenTokensFlow.spec.js
  e2e/importPrivateKeyFlow.spec.js
  e2e/importPrivateKeyFlow0x.spec.js
  e2e/init.js
  e2e/jest.e2e.config.js
  e2e/newWalletFlow.spec.js
  e2e/registerENSFlow.spec.js
  e2e/sendSheetFlow.spec.js
  e2e/sendSheetFlowContacts.spec.js
  e2e/swapSheetFlow.spec.js
  e2e/swapSheetFlow1.spec.js
  e2e/swapSheetFlow2.spec.js
  e2e/walletAvatarOptions.spec.js
  e2e/watchAddressFlow.spec.js
  e2e/watchedWalletCollectionActionsFlow.spec.js
  src/App.js
  src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.tsx
  src/components/animations/ButtonPressAnimation/ScaleButtonZoomable.tsx
  src/components/animations/ShimmerAnimation.js
  src/components/coin-row/CoinRow.js
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/components/coin-row/TransactionCoinRow.js
  src/components/dev-buttons/DevButton.js
  src/components/discover-sheet/DiscoverSheet.android.js
  src/components/exchange/ExchangeSearch.tsx
  src/components/expanded-state/WalletProfileState.js
  src/components/native-context-menu/contextMenu.android.js
  src/components/profile/ProfileMasthead.js
  src/config/defaultDebug.ts
  src/helpers/RainbowContext.tsx
  src/helpers/alert.ts
  src/helpers/validators.ts
  src/redux/walletconnect.ts
  src/screens/ENSIntroSheet.tsx
  src/screens/ExchangeModal.tsx
  src/screens/ImportSeedPhraseSheet.js
  src/screens/SendSheet.js
  src/screens/TransactionConfirmationScreen.js
  src/screens/WelcomeScreen.tsx
Labels: needs dev review, android, merge when ready, dev QA

#4179 Make iPhone 14 layouts happy (& migrate away from deprecated inset packages)
  ios/Podfile.lock
  package.json
  patches/react-native-safe-area-view+0.11.0.patch
  src/components/expanded-state/CustomGasState.js
  src/components/header/Header.js
  src/navigation/effects.js
  src/screens/AddCashSheet.js
  src/screens/ProfileSheet.tsx
  src/screens/SendSheet.js
  src/utils/safeAreaInsetValues.ts
  yarn.lock
Labels: dev QA

#4186 dont update backup meta when restoring
  src/components/backup/RestoreCloudStep.js
  src/redux/wallets.ts
Labels: merge when ready

#4194 Version bump iOS v1.7.8 & android 148
  CHANGELOG.md
  android/app/build.gradle
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#4196 Rename surface colors, update usages
  src/App.js
  src/design-system/color/palettes.docs.tsx
  src/design-system/color/palettes.ts
  src/design-system/components/Box/Box.docs.tsx
  src/design-system/components/Box/Box.examples.tsx
  src/design-system/components/Separator/Separator.examples.tsx
  src/design-system/components/Text/Text.examples.tsx
  src/design-system/docs/.playroom/FrameComponent.js
  src/design-system/playground/BackgroundDemo.tsx
  src/screens/PairHardwareWalletIntroSheet.tsx
  src/screens/PairHardwareWalletSearchSheet.tsx
Labels: design system, dev QA

#4199 Avoid parallelizing tests
  .github/workflows/macstadium-android-e2e.yml
  e2e/jest.e2e.config.js
Labels: needs dev review, merge when ready

#4020 Fix Android Status Bar issues
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  package.json
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
  src/components/audio/AudioPlayer.js
  src/components/backup/BackupSheetKeyboardLayout.js
  src/components/discover-sheet/UniswapPoolsSection.js
  src/components/expanded-state/unique-token/UnderlyingAsset.js
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/investment-cards/UniswapInvestmentRow.js
  src/components/investment-cards/UniswapPoolListRow.js
  src/components/modal/Modal.js
  src/helpers/index.ts
  src/helpers/statusBarHelper.ts
  src/hooks/useHideSplashScreen.ts
  src/navigation/RegisterENSNavigator.tsx
  src/navigation/Routes.ios.js
  src/navigation/nativeStackConfig.js
  src/navigation/onNavigationStateChange.js
  src/screens/AddCashSheet.js
  src/screens/AddTokenSheet.js
  src/screens/BackupSheet.js
  src/screens/CurrencySelectModal.tsx
  src/screens/ExpandedAssetSheet.js
  src/screens/ExplainSheet.js
  src/screens/ExternalLinkWarningSheet.tsx
  src/screens/ImportSeedPhraseSheet.js
  src/screens/ProfileSheet.tsx
  src/screens/RestoreSheet.js
  src/screens/SavingsSheet.js
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
  src/screens/WalletDiagnosticsSheet.js
  src/screens/WyreWebview.js
  src/theme/ThemeContext.tsx
  src/utils/index.ts
  src/utils/statusBar.ts
  yarn.lock
Labels: android, team1, dev QA

#4114 Fix infinite loading when tapping outside of the select google account modal
  ios/Podfile.lock
  package.json
  patches/react-native-cloud-fs+2.4.0.patch
  yarn.lock
Labels: dependencies, needs dev review, team1

#4210 Fix wallet avatar bug
  src/components/change-wallet/AddressRow.tsx
Labels: merge when ready, dev QA

#4208 Fix settings header
  src/navigation/config.js
  src/screens/SettingsSheet.tsx
Labels: merge when ready, notifications, dev QA

#4216 audit - vm2
  package.json
  yarn.lock
Labels: blocker

#4218 Fix ripple on Android 13
  android/app/src/main/java/com/swmansion/gesturehandler/react/RNZoomableButtonManager.java
Labels: android, team1, dev QA

#4228 audit d3-color
  package.json
  yarn.lock
Labels: merge when ready
