Repository rainbow-me/rainbow, pull requests merged in 2022-11, with the labels that each got.

#4346 Fix backup flow keyboard height
  src/screens/RestoreSheet.js
Labels: release

#4359 rm stray log
  src/components/coin-divider/CoinDivider.js
Labels: merge when ready

#4369 i18n: add English no thanks key
  src/languages/_english.json
Labels: merge when ready

#4371 Revert to using updated react-native fork rebased from 0.68.1 to 0.68.5
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: merge when ready

#4376 Fix "hide NFT" icon
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Labels: merge when ready

#4355 Implement error and loading states for notification subscription settings
  src/components/Spinner.tsx
  src/components/settings-menu/NotificationLoadingIndicator.tsx
  src/components/settings-menu/NotificationsSection.tsx
  src/components/settings-menu/WalletNotificationsSettings.tsx
  src/components/settings-menu/components/MenuItem.tsx
  src/components/settings-menu/notificationAlerts.ts
  src/languages/_english.json
  src/languages/_french.json
  src/notifications/settings.ts
Labels: merge when ready

#4379 Tracking toggle in app settings
  src/analytics/__tests__/index.test.ts
  src/analytics/index.ts
  src/components/settings-menu/PrivacySection.tsx
  src/components/settings-menu/components/Menu.tsx
  src/languages/_english.json
  src/languages/_french.json
  src/logger/__tests__/logger.test.ts
  src/logger/index.ts
  src/styles/colors.ts
Labels: analytics

#4398 home: fix savings render logic
  src/helpers/buildWalletSections.tsx
Labels: merge when ready

#4400 Adjust coin row text
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/exchange/ExchangeTokenRow.tsx
Labels: merge when ready

#4395 Empty Wallet Home Screen
  e2e/newWalletFlow.spec.js
  src/components/asset-list/AssetList.js
  src/components/asset-list/RecyclerAssetList2/cards/CardRowWrapper.tsx
  src/components/asset-list/RecyclerAssetList2/core/DiscoverMoreButton.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/ViewDimensions.tsx
  src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
  src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
  src/components/cards/EthCard.tsx
  src/components/cards/GenericCard.tsx
  src/components/cards/LearnCard.tsx
  src/components/cards/ReceiveAssetsCard.tsx
  src/components/cards/RotatingLearnCard.tsx
  src/components/cards/reusables/IconOrb.tsx
  src/components/cards/utils/constants.ts
  src/components/cards/utils/types.ts
  src/components/exchange/CurrencySelectionList.tsx
  src/components/list/NoResults.tsx
  src/components/send/SendAssetList.js
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
  src/hooks/useAccountAccentColor.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/SendSheet.js
Labels: dev QA

#4414 fix: l2 speed options
  src/components/gas/GasSpeedButton.js
Labels: release

#4427 Fix swaps token symbol/balance color
  src/components/exchange/ExchangeTokenRow.tsx
Labels: release, merge when ready

#4425 fix: xc swap gas limit logic
  src/handlers/swap.ts
Labels: release

#4428 Zora App Icon
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-anydpi-v26/zora.xml
  android/app/src/main/res/mipmap-anydpi-v26/zora_round.xml
  android/app/src/main/res/mipmap-hdpi/zora.png
  android/app/src/main/res/mipmap-hdpi/zora_background.png
  android/app/src/main/res/mipmap-hdpi/zora_foreground.png
  android/app/src/main/res/mipmap-hdpi/zora_round.png
  android/app/src/main/res/mipmap-ldpi/zora.png
  android/app/src/main/res/mipmap-ldpi/zora_background.png
  android/app/src/main/res/mipmap-ldpi/zora_foreground.png
  android/app/src/main/res/mipmap-ldpi/zora_round.png
  android/app/src/main/res/mipmap-mdpi/zora.png
  android/app/src/main/res/mipmap-mdpi/zora_background.png
  android/app/src/main/res/mipmap-mdpi/zora_foreground.png
  android/app/src/main/res/mipmap-mdpi/zora_round.png
  android/app/src/main/res/mipmap-xhdpi/zora.png
  android/app/src/main/res/mipmap-xhdpi/zora_background.png
  android/app/src/main/res/mipmap-xhdpi/zora_foreground.png
  android/app/src/main/res/mipmap-xhdpi/zora_round.png
  android/app/src/main/res/mipmap-xxhdpi/zora.png
  android/app/src/main/res/mipmap-xxhdpi/zora_background.png
  android/app/src/main/res/mipmap-xxhdpi/zora_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/zora_round.png
  android/app/src/main/res/mipmap-xxxhdpi/zora.png
  android/app/src/main/res/mipmap-xxxhdpi/zora_background.png
  android/app/src/main/res/mipmap-xxxhdpi/zora_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/zora_round.png
  audit-ci.jsonc
  ios/AppIcons/zora@2x.png
  ios/AppIcons/zora@3x.png
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/Rainbow/Info.plist
  src/assets/appIconZora.png
  src/assets/appIconZora@2x.png
  src/assets/appIconZora@3x.png
  src/components/settings-menu/AppIconSection.tsx
  src/featuresToUnlock/featureUnlockChecks.ts
  src/featuresToUnlock/unlockableAppIcons.ts
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
  src/styles/colors.ts
Labels: release

#4431 fix: eth placeholder loading check
  src/helpers/assets.ts
  src/helpers/buildWalletSections.tsx
Labels: release

#4432 Icon unlock explainer fix
  src/screens/ExplainSheet.js
Labels: release

#4435 Android loading fix
  src/components/asset-list/AssetList.js
Labels: release
