Repository rainbow-me/rainbow, pull requests merged in 2022-05, with the labels that each got.

#3264 Profiles: autopopulate ens name and avatar when adding contact
  src/components/contacts/ContactRow.js
  src/components/contacts/SwipeableContactRow.js
  src/components/ens-profile/ActionButtons/ActionButtons.tsx
  src/components/ens-profile/ActionButtons/MoreButton.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/exchange/ExchangeAssetList.js
  src/components/expanded-state/ContactProfileState.js
  src/components/send/SendContactList.js
  src/components/send/SendHeader.js
  src/hooks/index.js
  src/redux/contacts.ts
  src/screens/SendSheet.js
Labels: profiles

#3164 [RNBW-3217] Separate Pending Transactions
  audit-ci.json
  src/handlers/localstorage/accountLocal.ts
  src/hooks/useAccountTransactions.js
  src/parsers/index.ts
  src/parsers/transactions.ts
  src/redux/data.ts
Labels: needs dev review

#3278 Profiles: more tweaks
  e2e/registerENSFlow.spec.js
  src/components/animations/HourglassAnimation.tsx
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/ConfigurationSection.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/components/images/ImagePreviewOverlay.tsx
  src/handlers/ens.ts
  src/hooks/useCollectible.js
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/navigation/config.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  src/screens/ExplainSheet.js
Labels: profiles

#3283 audit - cross-fetch
  package.json
  yarn.lock
Labels: needs dev review, merge when ready

#3254 check native currency before updating assets
  src/redux/data.ts
Labels: needs dev review

#3281 add first open event
  src/App.js
Labels: merge when ready, analytics

#3282 handle no nfts error for v2 OS API
  src/handlers/opensea-api.ts
Labels: needs dev review, nice for release

#3118 Fix: lookupAddress on wallet load
  src/redux/wallets.js
  src/utils/profileUtils.ts
Labels: needs dev review

#3180 Prevent assets loading in chunks
  src/redux/data.ts
  src/redux/store.ts
Labels: critical path

#3296 Profiles: Fix flickering keyboard between Intro & Search screens
  src/navigation/RegisterENSNavigator.js
Labels: profiles

#3284 bump react coin icon
  package.json
  yarn.lock
Labels: needs dev review, merge when ready

#3241 Can't create a new wallet with biometry
  src/components/expanded-state/WalletProfileState.js
Labels: needs dev review

#3287 Profiles: fix records updates lag
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/inputs/InlineField.tsx
  src/hooks/useENSRegistrationCosts.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: profiles

#3291 verify rainbowkit
  src/assets/dappLogos/rainbowkit.com.jpg
  src/helpers/dappNameHandler.js
Labels: merge when ready

#3302 Profiles: intro screen jump fix
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3285 align contact modal + import wallet modal
  src/components/contacts/ContactRow.js
  src/components/expanded-state/ContactProfileState.js
  src/components/expanded-state/WalletProfileState.js
  src/components/expanded-state/profile/ProfileAvatarButton.js
  src/components/expanded-state/profile/ProfileModal.tsx
  src/components/expanded-state/profile/ProfileModalContainer.js
  src/components/expanded-state/profile/index.js
  src/components/fields/AddressField.js
  src/components/send/SendHeader.js
  src/languages/_english.json
  src/redux/contacts.ts
  src/screens/SendSheet.js
Labels: profiles

#3290 Add performance utils
  CODEOWNERS
  src/performance/utils.tsx
  tsconfig.json
Labels: merge when ready, performance

#3292 [RNBW-2616] Cannot read property 'address_from' of undefined
  src/redux/data.ts
Labels: needs dev review

#3299 Improve GIF playback speed on ProMotion devices
  ios/Podfile.lock
  patches/react-native-fast-image+8.5.11.patch
Labels: needs dev review

#3306 expanded state available networks
  src/components/AvailableNetworks.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/hooks/useAdditionalAssetData.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: merge when ready, swap-aggregator

#3308 network switcher
  src/components/exchange/CurrencySelectModalHeader.js
  src/components/exchange/NetworkSwitcher.js
  src/hooks/useSwapCurrencyList.ts
  src/languages/_english.json
  src/languages/_french.json
  src/redux/swap.ts
  src/screens/CurrencySelectModal.js
  src/screens/ExchangeModal.js
  src/utils/ethereumUtils.ts
Labels: merge when ready, swap-aggregator

#3318 use uniqueId
  src/hooks/useSwapInputHandlers.ts
Labels: merge when ready, swap-aggregator

#3312 Profiles: Fix edit profile infinite loading state
  src/handlers/deeplinks.ts
  src/navigation/RegisterENSNavigator.js
  src/redux/ensRegistration.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSSearchSheet.js
  src/utils/branch.ts
Labels: profiles

#3220 Remove toChecksumAddress for assets urls
  src/utils/getUrlForTrustIconFallback.ts
Labels: performance

#3304 Update WC dapp display treatment
  src/screens/TransactionConfirmationScreen.js
  src/screens/WalletConnectApprovalSheet.js
Labels: merge when ready

#3317 swap - fix discover charts
  src/hooks/useSwapCurrencyList.ts
Labels: merge when ready, swap-aggregator

#3199 Segment Performance Events
  CODEOWNERS
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/java/me/rainbow/NativeModules/RNStartTime/RNStartTimeModule.java
  android/app/src/main/java/me/rainbow/NativeModules/RNStartTime/RNStartTimePackage.java
  index.js
  ios/RNStartTime.h
  ios/RNStartTime.m
  ios/Rainbow.xcodeproj/project.pbxproj
  src/App.js
  src/hooks/useHideSplashScreen.js
  src/performance/start-time/index.ts
  src/performance/tracking/index.ts
  src/performance/tracking/types/PerformanceMetricData.ts
  src/performance/tracking/types/PerformanceMetrics.ts
  src/performance/tracking/types/PerformanceTags.ts
Labels: needs dev review, performance, fedora won't work

#3314 Profiles: update analytics
  src/components/discover-sheet/DiscoverSearch.js
  src/components/ens-profile/RecordHyperlink/RecordHyperlink.tsx
  src/components/send/SendHeader.js
  src/handlers/deeplinks.ts
  src/hooks/useOnAvatarPress.ts
  src/hooks/useTrackENSProfile.ts
  src/raps/actions/ens.ts
  src/screens/ProfileSheet.tsx
Labels: profiles

#3320 Profiles: e2e passing in bitrise
  e2e/deeplinks.spec.js
  e2e/discoverSheetFlow.spec.js
  e2e/hardhatTransactionFlow.spec.js
  e2e/init.js
  e2e/registerENSFlow.spec.js
  e2e/sendSheetFlow.spec.js
  src/components/contacts/ContactRow.js
  src/components/contacts/SwipeableContactRow.js
  src/components/discover-sheet/DiscoverSheet.ios.js
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/expanded-state/profile/ProfileModal.tsx
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/fab/SearchFab.js
  src/components/fab/index.js
  src/components/send/SendHeader.js
  src/handlers/deeplinks.ts
  src/handlers/ens.ts
  src/screens/QRScannerScreen.js
  src/screens/SendSheet.js
Labels: profiles

#3328 reset swap inputs
  src/hooks/useSwapDerivedOutputs.ts
  src/screens/ExchangeModal.js
Labels: merge when ready, swap-aggregator

#3327 flashbots no l2
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/screens/ExchangeModal.js
Labels: merge when ready, swap-aggregator

#3294 Reuse rows of recycler list instead of remounting them (attempt 2)
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/images/ImgixImage.tsx
Labels: needs dev review, needs QA, performance

#3323 Remove unused SizedToggler component with Reanimated 1 usage
  src/components/animations/SizeToggler.js
  src/components/animations/index.js
Labels: needs dev review, performance

#3322 Remove RotationArrow component with Reanimated 1 usage
  src/components/animations/RotationArrow.js
  src/components/animations/index.js
Labels: needs dev review, performance

#3321 Remove unused RoundButtonSizeToggler component with Reanimated 1 usage
  src/components/animations/RoundButtonSizeToggler.js
  src/components/animations/index.js
Labels: needs dev review, performance

#3337 swap - review clean up
  src/components/expanded-state/swap-details/CurrencyTile.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/utils/ethereumUtils.ts
Labels: merge when ready, swap-aggregator

#3279 Android Back Up Input blurring
  src/components/backup/RestoreCloudStep.js
Labels: needs dev review, QA later

#3346 Profiles: Fix small device UI issues
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSIntroSheet.tsx
Labels: profiles

#3338 Profiles: Address phase 3 PR review comments
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/ConfirmContent/WaitCommitmentConfirmationContent.tsx
  src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
  src/components/large-countdown-clock/index.js
  src/components/step-indicator/index.js
  src/components/unique-token/Tag.js
  src/handlers/ens.ts
  src/hooks/index.js
  src/hooks/useAccountENSDomains.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileImages.ts
  src/hooks/useENSProfileRecords.ts
  src/hooks/useFetchUniqueTokens.ts
  src/hooks/useLoadAccountLateData.ts
  src/hooks/useLoadGlobalLateData.js
  src/languages/_french.json
  src/screens/WalletScreen.js
  src/utils/__tests__/ens.test.ts
  src/utils/ens.ts
  src/utils/getENSNFTAvatarUrl.ts
  src/utils/index.ts
  src/utils/isENSNFTRecord.ts
  src/utils/labelhash.ts
  src/utils/normalizeENS.ts
  src/utils/parseENSNFTRecord.ts
  src/utils/stringifyENSNFTRecord.ts
  src/utils/validateENS.ts
  types/content-hash.d.ts
  types/eth-contract-metadata.d.ts
  types/eth-ens-namehash.d.ts
Labels: profiles

#3341 Profiles: Convert ENS sheets to TypeScript
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/SearchInput/SearchInput.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/sheet/sheet-action-buttons/SheetActionButtonRow.js
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/navigation/RegisterENSNavigator.tsx
  src/screens/ENSAdditionalRecordsSheet.tsx
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/ENSSearchSheet.tsx
Labels: profiles

#3355 Profiles: small phones alignments fix
  src/components/ens-registration/ConfirmContent/CommitContent.tsx
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/ConfirmContent/WaitCommitmentConfirmationContent.tsx
  src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
  src/navigation/RegisterENSNavigator.tsx
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles

#3357 Profiles: android register crash + tweaks
  e2e/registerENSFlow.spec.js
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/components/step-indicator/StepIndicator.tsx
  src/navigation/Routes.android.js
  src/navigation/effects.js
  src/screens/ENSConfirmRegisterSheet.tsx
  src/screens/ENSIntroSheet.tsx
Labels: profiles

#3356 Profiles: send sheet fixes
  src/components/ens-profile/ActionButtons/SendButton.tsx
  src/components/fields/AddressField.js
  src/components/send/SendHeader.js
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
Labels: profiles

#3350 Make dot moving smoother in charts
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
Labels: needs dev review, QA later, merge when ready

#3334 Profiles: Fallback ENS avatar fetching to simplehash if OpenSea is down or collection is removed
  src/components/images/ImagePreviewOverlay.tsx
  src/ens-avatar/src/specs/erc721.ts
  src/handlers/simplehash.ts
Labels: profiles

#3245 Bump rn to the newest v
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/me/rainbow/MainApplication.java
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/Rainbow/AppDelegate.mm
  package.json
  patches/@rainbow-me+react-native-payments+1.1.5.patch
  patches/lottie-react-native+4.0.2.patch
  patches/react-native+0.68.1.patch
  patches/react-native-android-keyboard-adjust+1.2.0.patch
  patches/react-native-cloud-fs+2.4.0.patch
  patches/react-native-dark-mode+0.2.2.patch
  patches/react-native-keyboard-area+1.0.5.patch
  patches/react-native-minimizer+1.3.5.patch
  patches/react-native-mmkv+1.5.2.patch
  patches/react-native-mmkv+2.3.3.patch
  patches/react-native-radial-gradient+1.0.9.patch
  patches/react-native-tcp+3.3.2.patch
  patches/react-native-video-cache+2.0.5.patch
  src/hooks/usePersistentAspectRatio.ts
  yarn.lock
Labels: needs dev review

#3354 version bump
  CHANGELOG.md
  android/app/build.gradle
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
Labels: merge when ready

#3358 Profiles: assign record sheet fixes
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/handlers/ens.ts
Labels: profiles

#3364 Profiles: Fix intro sheet height for small devices
  src/navigation/RegisterENSNavigator.tsx
  src/screens/ENSIntroSheet.tsx
Labels: profiles

#3365 Profiles: More pixel pushing for small devices
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/images/ImagePreviewOverlay.tsx
  src/screens/ENSAssignRecordsSheet.tsx
  src/screens/ProfileSheet.tsx
Labels: profiles

#3361 Profiles: last qa fixes
  src/components/contacts/ContactRow.js
  src/components/expanded-state/ContactProfileState.js
  src/components/fields/AddressField.js
  src/components/send/SendHeader.js
  src/handlers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationForm.ts
  src/raps/actions/ens.ts
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles

#3366 Profiles: Omit `isPreview` flag for intro screen preview profiles
  src/navigation/Routes.android.js
Labels: profiles

#3371 Profiles: disable step indicator android
  src/components/step-indicator/StepIndicator.tsx
Labels: profiles

#3360 Add useInitializeWallet performance tracking
  src/hooks/useInitializeWallet.js
  src/performance/tracking/index.ts
Labels: performance

#3363 Profiles: last last qa fixes
  src/components/fields/AddressField.js
  src/components/send/SendContactList.js
  src/components/send/SendHeader.js
  src/screens/SendConfirmationSheet.js
  src/screens/SendSheet.js
Labels: profiles

#3375 Profiles: Increase ENS fallback time
  src/redux/uniqueTokens.ts
Labels: profiles

#3206 migration asset selectors from lodash
  src/helpers/assetSelectors.js
  src/parsers/accounts.js
  src/redux/topMovers.ts
Labels: needs dev review, javascript, performance

#3376 Profiles: add ENS NFT fallback to profile sheet & use `handleAndSignImages` in fallback
  src/handlers/ens.ts
  src/helpers/assets.js
  src/hooks/useFetchUniqueTokens.ts
  src/parsers/index.ts
  src/parsers/uniqueTokens.js
Labels: profiles

#3374 Profiles: handle set primary name different flows
  e2e/registerENSFlow.spec.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/ConfigurationSection.tsx
  src/handlers/ens.ts
  src/hooks/useAccountProfile.js
  src/hooks/useENSProfile.ts
  src/hooks/useImportingWallet.js
  src/hooks/useInitializeWallet.js
  src/hooks/useRefreshAccountData.js
  src/hooks/useWalletENSAvatar.ts
  src/redux/wallets.js
  src/screens/ChangeWalletSheet.js
  src/utils/profileUtils.ts
Labels: profiles

#3378 Profiles: more profiles
  src/apollo/queries.ts
  src/handlers/ens.ts
  src/hooks/useENSModifiedRegistration.ts
  src/parsers/poap.js
  src/redux/wallets.js
  src/screens/ENSConfirmRegisterSheet.tsx
Labels: profiles

#3369 Enable hermes transformer in metro rn babel preset
  package.json
  patches/metro-react-native-babel-preset+0.68.0.patch
  yarn.lock
Labels: dependencies, QA later, performance, fedora won't work

#3379 Profiles: records and gas fee panel updates
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/screens/ENSAssignRecordsSheet.tsx
Labels: profiles

#3383 Fix decimals in Synthetix in Optimism
  src/references/chain-assets.json
Labels: needs dev review, QA later, merge when ready

#3388 profiles: filter non owned ens
  src/apollo/queries.ts
  src/handlers/ens.ts
Labels: profiles

#3329 Push Notifications Dev Menu
  src/App.js
  src/components/settings-menu/DevNotificationsSection.tsx
  src/components/settings-menu/DevSection.js
  src/components/settings-menu/index.js
  src/helpers/isTestFlight.ts
  src/languages/_english.json
  src/screens/SettingsModal.js
Labels: needs dev review, merge when ready

#3396 bump ethers.js dependency
  package.json
  src/handlers/web3.ts
  yarn.lock
Labels: dependencies, merge when ready

#3391 Fix notifications dev menu not scrolling
  src/components/settings-menu/DevNotificationsSection.tsx
Labels: merge when ready

#3393 swap - fix derived values behavior
  src/components/exchange/ExchangeInputField.js
  src/hooks/useSwapDerivedOutputs.ts
  src/screens/ExchangeModal.js
Labels: merge when ready, swap-aggregator

#3203 ios 12 widget-related crash fix
  ios/Rainbow.xcodeproj/project.pbxproj
  src/components/settings-menu/CurrencySection.js
Labels: needs dev review

#3412 profiles set records estimations tweaks
  CODEOWNERS
  src/handlers/ens.ts
  src/hooks/useENSRegistrationCosts.ts
Labels: profiles

#3419 Fix incorrect aspect ratio calculating after MMKV bump
  src/hooks/usePersistentAspectRatio.ts
Labels: QA later

#3432 swap - available networks explainooor
  src/components/AvailableNetworks.js
  src/components/expanded-state/asset/ChartExpandedState.js
  src/languages/_english.json
  src/languages/_french.json
  src/screens/ExplainSheet.js
Labels: merge when ready, swap-aggregator

#3418 Profiles: Fix watch button issue
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/hooks/useImportingWallet.js
  src/hooks/useWatchWallet.ts
Labels: profiles

#3436 swap - disable l2 favs
  src/components/coin-row/CoinRowInfoButton.js
  src/components/coin-row/ExchangeCoinRow.js
  src/components/exchange/ExchangeAssetList.js
  src/hooks/useSwapCurrencyHandlers.js
  src/screens/CurrencySelectModal.js
Labels: merge when ready, swap-aggregator
