Repository rainbow-me/rainbow, pull requests merged in 2022-04, with the labels that each got.

#3133 Fix migrations 13 and 14
  src/model/migrations.ts
Labels: needs dev review, merge when ready, critical path

#3135 remove flow
  .flowconfig
  src/components/svg/SvgImage.js
Labels: needs dev review, merge when ready

#3125 Profiles: extend expiration date
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/ens-registration/ConfirmContent/CommitContent.tsx
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/ConfirmContent/WaitCommitmentConfirmationContent.tsx
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/ens-registration/index.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/components/token-info/TokenInfoItem.js
  src/entities/ensRegistration.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSRecordDisplayProperties.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useENSSearch.ts
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/navigation/RegisterENSNavigator.js
  src/raps/actions/ens.ts
  src/raps/common.ts
  src/raps/registerENS.ts
  src/redux/ensRegistration.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: profiles

#3134 deeplink route to profile sheet
  src/handlers/deeplinks.ts
Labels: profiles

#3124 Initial Codeowners file
  CODEOWNERS
Labels: merge when ready

#3136 Fix description crash
  src/components/expanded-state/asset/ChartExpandedState.js
Labels: needs dev review, QA later, merge when ready

#3146 Design system color edits
  src/design-system/color/palettes.ts
Labels: merge when ready, design system

#3126 @benisgold/profiles analytics
  src/components/discover-sheet/DiscoverSearch.js
  src/components/header/DiscoverHeaderButton.js
  src/hooks/index.js
  src/hooks/useOnAvatarPress.ts
  src/hooks/useTrackENSProfile.ts
  src/raps/actions/ens.ts
  src/screens/WalletScreen.js
Labels: profiles

#3141 Profiles: Fix incorrect "Confirm Registration" placeholder
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3142 Profiles: (Android) Fix issue when attempting to edit ENS profile
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/inputs/InlineField.tsx
  src/hooks/useENSRecordDisplayProperties.tsx
  src/hooks/useOnAvatarPress.ts
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3143 Profiles: Fix issue where ENS avatar was disappearing when updating profile
  src/hooks/useENSRegistrationForm.ts
Labels: profiles

#3144 Profiles: Fix issue where couldn't upload photos on android
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useSelectImageMenu.tsx
Labels: profiles

#3132 Refactor postinstall.sh to reduce code duplication and improve error handling
  scripts/postinstall.sh
Labels: needs dev review, merge when ready

#3150 Fix possibility to scroll with scroll indicator on unique asset image preview
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/sheet/SlackSheet.js
Labels: needs dev review

#3154 Profiles phase 2 minor review comments
  e2e/hardhatTransactionFlow.spec.js
  e2e/helpers.js
  e2e/registerENSFlow.spec.js
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
  src/hooks/useOnAvatarPress.ts
  src/languages/_english.json
  src/raps/actions/depositCompound.ts
  src/raps/actions/swap.ts
  src/raps/actions/unlock.ts
  src/raps/actions/withdrawCompound.ts
  src/raps/common.ts
Labels: profiles

#3153 Profiles: QA send user after editing
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3160 Remove smile emoji from label
  src/languages/_english.json
Labels: QA later

#3156 Profiles: Persist search value between ENS registration screens
  src/screens/ENSSearchSheet.js
Labels: profiles

#3159 Profiles: Fix inconsitent keyboard issues
  src/navigation/RegisterENSNavigator.js
Labels: profiles

#3168 Profiles: grab accent color from avatar in edit
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3115 Profiles: Add zoomable image preview to ENS cover photos
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/ens/ProfileInfoSection.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/images/ImagePreviewOverlay.tsx
  src/components/sheet/SlackSheet.js
  src/screens/ENSIntroSheet.tsx
Labels: profiles

#3155 Profiles: Add ability to remove ENS image records
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useSelectImageMenu.tsx
  src/languages/_english.json
Labels: profiles

#3137 Profiles: pending registrations
  src/apollo/queries.ts
  src/components/discover-sheet/DiscoverSearch.js
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/components/ens-registration/index.tsx
  src/components/exchange/ExchangeAssetList.js
  src/handlers/ens.ts
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useFetchUniqueTokens.ts
  src/languages/_english.json
  src/navigation/RegisterENSNavigator.js
  src/redux/ensRegistration.ts
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
  src/utils/getENSNFTAvatarUrl.ts
Labels: profiles

#3158 Countdown Timer Component for ENS registration
  CODEOWNERS
  package.json
  src/components/animations/CheckmarkAnimation.js
  src/components/animations/CheckmarkAnimation.tsx
  src/components/icons/svg/LargeCheckmarkIcon.tsx
  src/components/large-countdown-clock/LargeCountdownClock.tsx
  src/components/large-countdown-clock/SeparatorDots.tsx
  src/components/large-countdown-clock/index.js
  src/components/large-countdown-clock/useVariableFont.ts
  src/screens/ENSConfirmRegisterSheet.js
  yarn.lock
Labels: dependencies, needs dev review, profiles

#3157 Profiles: Enable long press on duration field
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/hooks/useInterval.ts
Labels: profiles

#3171 Profiles: Address Phase 2 PR comments
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
  src/components/header/DiscoverHeaderButton.js
Labels: profiles

#3173 Profiles: Log upload image errors
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#3176 Profiles: phase two final review comments
  e2e/registerENSFlow.spec.js
  src/components/buttons/TintButton.tsx
  src/handlers/localstorage/accountLocal.ts
  src/helpers/ens.ts
  src/languages/_english.json
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3170 Profiles: Only show ENS on-chain data warning once per user
  src/handlers/localstorage/ens.ts
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3178 Profiles: merge ens phase 2
  CODEOWNERS
  audit-ci.json
  e2e/registerENSFlow.spec.js
  package.json
  scripts/postinstall.sh
  src/components/animations/CheckmarkAnimation.js
  src/components/animations/CheckmarkAnimation.tsx
  src/components/animations/HourglassAnimation.tsx
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
  src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
  src/components/buttons/TintButton.tsx
  src/components/ens-registration/ConfirmContent/CommitContent.tsx
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/header/DiscoverHeaderButton.js
  src/components/icons/svg/LargeCheckmarkIcon.tsx
  src/components/images/ImagePreviewOverlay.tsx
  src/components/large-countdown-clock/LargeCountdownClock.tsx
  src/components/large-countdown-clock/SeparatorDots.tsx
  src/components/large-countdown-clock/index.js
  src/components/large-countdown-clock/useVariableFont.ts
  src/components/sheet/SlackSheet.js
  src/handlers/localstorage/accountLocal.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/languages/_english.json
  src/model/wallet.ts
  src/screens/ENSConfirmRegisterSheet.js
  yarn.lock
Labels: profiles

#3174 Profiles: Update profile header to new design spec
  src/components/ens-profile/ActionButtons/ActionButton.tsx
  src/components/ens-profile/ActionButtons/ActionButtons.tsx
  src/components/ens-profile/ActionButtons/EditButton.tsx
  src/components/ens-profile/ActionButtons/SendButton.tsx
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/components/ens-profile/GradientOutlineButton/GradientOutlineButton.tsx
  src/components/ens-profile/MoreButton/MoreButton.tsx
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/hooks/useENSRegistrationActionHandler.ts
Labels: profiles

#3165 update sendable check
  src/parsers/uniqueTokens.js
Labels: needs dev review, QA later

#3185 Add Fedora branch indicator
  src/components/AppVersionStamp.js
Labels: merge when ready

#3188 image handling fixes + refactor
  src/components/3d/SimpleModelView.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/unique-token/UniqueTokenCard.js
  src/components/unique-token/UniqueTokenImage.js
  src/components/video/SimpleVideo.tsx
  src/entities/uniqueAssets.ts
  src/handlers/imgix.ts
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/utils/getFullSizeUrl.ts
  src/utils/getLowResUrl.ts
Labels: needs dev review

#3193 Profiles: Misc fixes
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/helpers/ens.ts
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useSelectImageMenu.tsx
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/utils/getLowResUrl.ts
Labels: profiles

#3197 Profiles: Confirm sheet UI updates
  src/components/animations/HourglassAnimation.tsx
  src/components/ens-registration/ConfirmContent/CommitContent.tsx
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/components/ens-registration/ConfirmContent/RenewContent.tsx
  src/components/ens-registration/ConfirmContent/WaitCommitmentConfirmationContent.tsx
  src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
  src/components/ens-registration/index.tsx
  src/components/large-countdown-clock/LargeCountdownClock.tsx
  src/components/large-countdown-clock/SeparatorDots.tsx
  src/languages/_english.json
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ProfileSheet.tsx
Labels: profiles

#3172 Profiles: additional records sheet
  index.js
  package.json
  src/content-hash.d.ts
  src/handlers/ens.ts
  src/helpers/ens.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/languages/_english.json
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/routesNames.js
  src/references/ethereum-units.json
  src/screens/ENSAdditionalRecordsSheet.js
  src/screens/ENSAssignRecordsSheet.js
  src/utils/contenthash.ts
  src/utils/index.ts
  yarn.lock
Labels: profiles

#3167 remove expired incomplete ens registrations
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/hooks/useENSPendingRegistrations.tsx
  src/languages/_english.json
  src/redux/ensRegistration.ts
Labels: profiles

#3182 Profiles: separate data for incomplete profiles by ens name
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
Labels: profiles

#3208 Fix sky06 color (rgb → rgba)
  src/design-system/color/palettes.ts
Labels: merge when ready, design system

#3207 Do not remount rows of RecyclerListView
  src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
Labels: needs dev review, QA later, merge when ready

#3190 Profiles: several bug fixes
  src/apollo/queries.ts
  src/components/discover-sheet/DiscoverSearch.js
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/hooks/useENSRecordDisplayProperties.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationForm.ts
  src/languages/_english.json
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSIntroSheet.tsx
  src/screens/ProfileSheet.tsx
  src/utils/getENSNFTAvatarUrl.ts
Labels: profiles

#3205 Profiles: ens navigator horizontal swipe
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSSearchSheet.js
Labels: profiles

#3214 Update rebase
  .github/workflows/rebase.yml
Labels: needs dev review, QA later, merge when ready

#3183 Profiles: improve gas handling
  src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
  src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/redux/gas.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3216 Update rebase.yml
  .github/workflows/rebase.yml
Labels: needs dev review, QA later, merge when ready

#3211 Profiles: Drop metadata.ens.domains fallback in favour of The Graph + ImgixImage
  src/apollo/queries.ts
  src/handlers/ens.ts
Labels: profiles

#3191 Profiles: primary ens name explainer sheet
  src/components/ens-registration/ConfirmContent/RegisterContent.tsx
  src/languages/_english.json
  src/screens/ExplainSheet.js
Labels: profiles

#3184 ENS Profile zoomable images
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/unique-token/ZoomableWrapper.android.js
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/images/ImagePreviewOverlay.tsx
Labels: profiles

#3212 Profiles: Make ordering of action buttons match order of fields
  src/helpers/ens.ts
  src/screens/ENSAdditionalRecordsSheet.js
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3221 Profiles: Intro Screen polishhh
  src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
  src/navigation/Routes.ios.js
  src/navigation/config.js
Labels: profiles

#3223 Update audit-ci.json
  audit-ci.json
Labels: needs dev review, merge when ready

#3187 @tchayen/fix swap gesture on expanded asset
  src/screens/CurrencySelectModal.js
Labels: needs dev review, QA later

#3229 Ignore async vuln which was already patched
  audit-ci.json
Labels: QA later, merge when ready

#3225 Profiles polish
  src/components/discover-sheet/RegisterENSSection.tsx
  src/handlers/ens.ts
  src/screens/ExpandedAssetSheet.js
Labels: profiles

#3234 fix e2e - we got an ens
  e2e/sendSheetFlow.spec.js
Labels: merge when ready

#3231 Profiles: Fix zoomable images on intro screen
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/navigation/config.js
  src/screens/ProfileSheet.tsx
Labels: profiles

#3235 Revert "Do not remount rows of RecyclerListView (#3207)"
  e2e/sendSheetFlow.spec.js
Labels: needs dev review, merge when ready

#3232 Profiles: Choose NFT as cover photo
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/components/images/ImagePreviewOverlay.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useSelectImageMenu.tsx
  src/screens/ENSAssignRecordsSheet.js
  src/utils/getENSNFTAvatarUrl.ts
  src/utils/index.ts
  src/utils/isENSNFTAvatar.ts
  src/utils/isENSNFTRecord.ts
  src/utils/parseENSNFTAvatar.ts
  src/utils/parseENSNFTRecord.ts
  src/utils/stringifyENSNFTRecord.ts
Labels: profiles

#3239 Profiles: Various fixes
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSRegistrationForm.ts
  src/hooks/useSelectImageMenu.tsx
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3224 use MD5 through JSI with react-native-quick-md5
  ios/Podfile.lock
  package.json
  patches/imgix-core-js+2.3.2.patch
  yarn.lock
Labels: needs dev review, QA later, merge when ready, performance, fedora won't work

#3181 Finish Sentry Performance setup
  ios/Podfile.lock
  package.json
  src/App.js
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  yarn.lock
Labels: needs dev review, performance

#3240 Profiles: improve ens discovery
  src/apollo/queries.ts
Labels: profiles

#3213 Fix crash on details sheet
  src/react-native-cool-modals/ios/UIViewController+slack.swift
Labels: needs dev review, needs QA, merge when ready, fedora won't work

#3247 RC v1.6.10
  CHANGELOG.md
  CODEOWNERS
  android/app/build.gradle
  audit-ci.json
  ios/Rainbow.xcodeproj/project.pbxproj
  package.json
  patches/async+2.6.2.patch
  src/App.js
  src/components/3d/SimpleModelView.tsx
  src/components/AppVersionStamp.js
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/settings-menu/SettingsSection.js
  src/components/toasts/FedoraToast.tsx
  src/components/toasts/index.js
  src/components/unique-token/UniqueTokenCard.js
  src/components/unique-token/UniqueTokenImage.js
  src/components/video/SimpleVideo.tsx
  src/entities/uniqueAssets.ts
  src/handlers/deeplinks.ts
  src/handlers/fedora.ts
  src/handlers/imgix.ts
  src/hooks/usePersistentAspectRatio.ts
  src/hooks/usePersistentDominantColorFromImage.ts
  src/hooks/useScanner.js
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  src/redux/walletconnect.js
  src/utils/getFullSizeUrl.ts
  src/utils/getLowResUrl.ts
  yarn.lock
Labels: release

#3251 Pulsing checkmark when visible for more than 2s
  src/components/animations/CheckmarkAnimation.tsx
Labels: needs dev review, QA later, merge when ready, profiles

#3238 Profiles: improve costs hook
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/hooks/useENSRegistrationActionHandler.ts
  src/hooks/useENSRegistrationCosts.ts
  src/hooks/useENSSearch.ts
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSSearchSheet.js
Labels: profiles

#3252 Profiles: more fixes
  src/hooks/useENSSearch.ts
  src/raps/actions/ens.ts
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSIntroSheet.tsx
  src/screens/ENSSearchSheet.js
Labels: profiles

#3236 swap review updates
  src/components/Pill.js
  src/components/exchange/ConfirmExchangeButton.js
  src/components/exchange/ExchangeDetailsRow.js
  src/components/expanded-state/SwapDetailsState.js
  src/components/expanded-state/index.js
  src/components/expanded-state/swap-details/CurrencyTile.js
  src/components/expanded-state/swap-details/SwapDetailsContent.js
  src/components/expanded-state/swap-details/SwapDetailsContractRow.js
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
  src/components/expanded-state/swap-details/SwapDetailsMasthead.js
  src/components/expanded-state/swap-details/SwapDetailsPriceRow.js
  src/components/expanded-state/swap-details/SwapDetailsRow.js
  src/components/expanded-state/swap-details/SwapDetailsUniswapRow.js
  src/components/expanded-state/swap-details/index.js
  src/components/expanded-state/swap-settings/InputPill.js
  src/components/expanded-state/swap-settings/StepButtonInput.js
  src/components/expanded-state/swap-settings/SwapSettingsState.js
  src/components/icons/Icon.js
  src/components/icons/svg/DoubleChevronIcon.js
  src/handlers/localstorage/globalSettings.ts
  src/hooks/index.js
  src/hooks/useAccountSettings.js
  src/hooks/useRainbowFee.js
  src/hooks/useSwapAdjustedAmounts.ts
  src/hooks/useSwapDerivedOutputs.ts
  src/hooks/useSwapSlippage.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/Routes.ios.js
  src/navigation/routesNames.js
  src/redux/settings.ts
  src/redux/swap.ts
  src/screens/ExchangeModal.js
  src/screens/ExpandedAssetSheet.js
  src/screens/ExplainSheet.js
Labels: needs dev review, swap-aggregator

#3256 Profiles: Fix text record field state
  src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
Labels: profiles

#3244 Profiles: clear current registration name when RegisterENSNavigator unmounts
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3250 Profiles: tweak isLoading conditions in useENSRegistrationForm
  src/hooks/useENSRegistrationForm.ts
Labels: profiles

#3263 Profiles: performance improvements and stuff
  src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
  src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
  src/handlers/ens.ts
  src/handlers/localstorage/ens.ts
  src/hooks/index.js
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSProfile.ts
  src/hooks/useENSProfileRecords.ts
  src/hooks/useENSRegistration.ts
  src/hooks/useENSRegistrationForm.ts
  src/languages/_english.json
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
  src/screens/ENSIntroSheet.tsx
  src/screens/ENSSearchSheet.js
Labels: profiles

#3266 Profiles: fix NFTs recycler list scroll handler in profiles sheet
  src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
Labels: profiles

#3265 Profiles: Improve watch/unwatch flow
  src/components/ens-profile/ActionButtons/WatchButton.tsx
  src/helpers/walletLoadingStates.ts
  src/hooks/useImportingWallet.js
  src/hooks/useInitializeWallet.js
  src/hooks/useWatchWallet.ts
  src/languages/_english.json
  src/model/wallet.ts
Labels: profiles

#3268 swap exchange icons
  src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
  src/styles/colors.js
  src/utils/getExchangeIconUrl.ts
  src/utils/index.ts
Labels: merge when ready, swap-aggregator

#3270 swap - rm default eth
  src/components/fab/ExchangeFab.js
  src/hooks/useSwapCurrencyHandlers.js
Labels: merge when ready, swap-aggregator

#3274 Profiles: last bugs
  src/navigation/RegisterENSNavigator.js
  src/screens/ENSAssignRecordsSheet.js
  src/screens/ENSConfirmRegisterSheet.js
Labels: profiles

#3275 Profiles: polish merge tweak
  src/components/images/ImagePreviewOverlay.tsx
Labels: profiles

#3272 Profiles: ens profile go to NFTs from avatar / cover
  src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
  src/components/ens-profile/ProfileCover/ProfileCover.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/unique-token/ZoomableWrapper.js
  src/components/images/ImagePreviewOverlay.tsx
  src/components/unique-token/UniqueTokenImage.js
  src/screens/ENSAssignRecordsSheet.js
Labels: profiles

#3273 Profiles: reorder records and add coins to profile
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/ens-profile/RecordTags/RecordTags.tsx
  src/components/icons/Icon.js
  src/components/icons/svg/BTCIcon.js
  src/components/icons/svg/DOGEIcon.js
  src/components/icons/svg/LTCIcon.js
  src/helpers/ens.ts
  src/hooks/useENSRecordDisplayProperties.tsx
Labels: profiles

#3262 Profiles: UI fixes
  src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
  src/languages/_english.json
Labels: profiles
