Repository rainbow-me/rainbow, pull requests merged in 2023-03, with the labels that each got.

#4677 adjust staged data loading
  src/hooks/index.ts
  src/hooks/useInitializeDiscoverData.ts
  src/hooks/useLoadAccountData.ts
  src/hooks/useLoadAccountLateData.ts
  src/hooks/useLoadGlobalEarlyData.ts
  src/hooks/useLoadGlobalLateData.ts
  src/screens/WalletScreen/index.tsx
Labels: performance

#4689 changed it to be less wordy and fixed a double space
  src/languages/_english.json
  src/languages/_french.json
Labels: release

#4691 fix: asset colors for assets not in wallet
  src/components/buttons/TokenSelectionButton.js
  src/components/exchange/ExchangeField.tsx
  src/components/exchange/ExchangeInputField.tsx
  src/components/exchange/ExchangeMaxButton.tsx
  src/components/exchange/ExchangeNativeField.tsx
  src/components/exchange/ExchangeOutputField.tsx
  src/hooks/useColorForAsset.ts
  src/screens/ExchangeModal.tsx
Labels: release

#4665 fonts: rm monospace fonts
  ios/PriceWidget/Info.plist
  ios/Rainbow.xcodeproj/project.pbxproj
  ios/Rainbow/Info.plist
  src/components/text/ErrorText.js
  src/components/text/Monospace.js
  src/components/text/index.js
  src/components/unique-token/UniqueTokenImage.js
  src/styles/buildTextStyles.js
  src/styles/fonts.js
Labels: performance

#4667 chore: replace password checker
  package.json
  src/components/backup/BackupCloudStep.js
  yarn.lock
Labels: performance

#4727 update useLegacyNFTs
  src/resources/nfts/index.ts
Labels: nfts

#4743 NFT Refactor: remove ENS NFT revalidation
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/handlers/ens.ts
  src/hooks/useAsset.ts
  src/hooks/useCollectible.ts
  src/screens/ExpandedAssetSheet.js
Labels: nfts

#4742 NFT Refactor: finish migrating opensea -> simplehash
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/handlers/ens.ts
  src/handlers/opensea-api.ts
  src/handlers/poap.ts
  src/handlers/simplehash.ts
  src/hooks/useAsset.ts
  src/hooks/useCollectible.ts
  src/parsers/index.ts
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/screens/ExpandedAssetSheet.js
Labels: nfts

#4741 NFT Refactor: remove redux
  e2e/registerENSFlow.spec.js
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/handlers/ens.ts
  src/handlers/localstorage/accountLocal.ts
  src/handlers/opensea-api.ts
  src/handlers/poap.ts
  src/handlers/simplehash.ts
  src/hooks/useAsset.ts
  src/hooks/useCollectible.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useInitializeAccountData.ts
  src/hooks/useLoadAccountData.ts
  src/hooks/useRefreshAccountData.ts
  src/hooks/useResetAccountState.ts
  src/hooks/useSendableUniqueTokens.ts
  src/hooks/useWalletSectionsData.ts
  src/parsers/index.ts
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/redux/data.ts
  src/redux/reducers.ts
  src/redux/uniqueTokens.ts
  src/resources/nfts/simplehash/utils.ts
  src/screens/ExpandedAssetSheet.js
  src/screens/ShowcaseSheet.js
Labels: nfts

#4728 NFT Refactor: replace useFetchUniqueTokens w/ useLegacyNFTs
  e2e/registerENSFlow.spec.js
  src/components/asset-list/RecyclerAssetList2/WrappedNFT.tsx
  src/components/ens-profile/ProfileSheetHeader.tsx
  src/components/expanded-state/UniqueTokenExpandedState.tsx
  src/components/expanded-state/ens/InfoRow.tsx
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
  src/ens-avatar/src/specs/erc1155.ts
  src/ens-avatar/src/specs/erc721.ts
  src/entities/uniqueAssets.ts
  src/handlers/ens.ts
  src/handlers/localstorage/accountLocal.ts
  src/handlers/opensea-api.ts
  src/handlers/poap.ts
  src/handlers/simplehash.ts
  src/helpers/utilities.ts
  src/hooks/index.ts
  src/hooks/useAsset.ts
  src/hooks/useCollectible.ts
  src/hooks/useENSModifiedRegistration.ts
  src/hooks/useENSPendingRegistrations.tsx
  src/hooks/useExternalWalletSectionsData.ts
  src/hooks/useFetchUniqueTokens.ts
  src/hooks/useInitializeAccountData.ts
  src/hooks/useLoadAccountData.ts
  src/hooks/useRefreshAccountData.ts
  src/hooks/useResetAccountState.ts
  src/hooks/useSendableUniqueTokens.ts
  src/hooks/useWalletSectionsData.ts
  src/parsers/index.ts
  src/parsers/poap.js
  src/parsers/uniqueTokens.js
  src/redux/data.ts
  src/redux/reducers.ts
  src/redux/uniqueTokens.ts
  src/resources/nfts/index.ts
  src/resources/nfts/simplehash/index.ts
  src/resources/nfts/simplehash/utils.ts
  src/resources/nfts/types.ts
  src/screens/ExpandedAssetSheet.js
  src/screens/ProfileSheet.tsx
  src/screens/ShowcaseSheet.js
  src/utils/handleAndSignImages.ts
Labels: nfts

#4756 Release: Fix floor price bug
  src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
Labels: release

#4763 Release: Fix POAP NFT expanded state bug
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
Labels: release

#4761 Release: Fix SVG rendering bug
  src/components/svg/SvgImage.js
Labels: release
