Repository rainbow-me/rainbow, pull requests merged in 2023-01, with the labels that each got.

#4476 feat: wc v2 connected dapps, ui polish
  src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
  src/components/walletconnect-list/WalletConnectV2ListItem.tsx
  src/helpers/walletConnectNetworks.ts
  src/languages/_english.json
  src/languages/_french.json
  src/redux/walletconnect.ts
  src/screens/ConnectedDappsSheet.js
  src/screens/WalletConnectApprovalSheet.js
  src/utils/walletConnect.ts
Labels: dev QA

#4536 fix swaps: load the correct provider when loading wallet
  src/screens/ExchangeModal.tsx
Labels: release

#4523 rc v1.8.6 fixes
  e2e/swapSheetFlow1.spec.js
  e2e/swapSheetFlow2.spec.js
  src/components/change-wallet/WalletList.tsx
  src/hooks/useImportingWallet.ts
  src/screens/AddWalletSheet.tsx
  src/screens/ImportSeedPhraseSheet.tsx
Labels: release, merge when ready

#4351 feat: notifications promo sheet
  src/analytics/event.ts
  src/assets/notificationsPromoSheetBackground.png
  src/assets/notificationsPromoSheetBackground@2x.png
  src/assets/notificationsPromoSheetBackground@3x.png
  src/assets/notificationsPromoSheetHeaderAndroid.png
  src/assets/notificationsPromoSheetHeaderAndroid@2x.png
  src/assets/notificationsPromoSheetHeaderAndroid@3x.png
  src/assets/notificationsPromoSheetHeaderIOS.png
  src/assets/notificationsPromoSheetHeaderIOS@2x.png
  src/assets/notificationsPromoSheetHeaderIOS@3x.png
  src/campaigns/campaignChecks.ts
  src/campaigns/notificationsPromoCampaign.ts
  src/campaigns/swapsPromoCampaign.ts
  src/languages/_english.json
  src/languages/_french.json
  src/navigation/Routes.android.js
  src/navigation/Routes.ios.js
  src/navigation/config.js
  src/navigation/onNavigationStateChange.js
  src/navigation/routesNames.js
  src/screens/NotificationsPromoSheet/index.tsx
Labels: dev QA

#4552 ledger: connection hook
  src/handlers/web3.ts
  src/hooks/useLedgerConnect.ts
  src/languages/_english.json
  src/languages/_french.json
Labels: ledger-support

#4558 chore: clean up wrong alias
  src/model/wallet.ts
Labels: merge when ready

#4585 fix: bt permissions signTypeData
  src/model/wallet.ts
Labels: release
