Repository rainbow-me/rainbow, pull requests merged in 2024-02, with the labels that each got.

#5339 [APP-1092]: context menu overflowing off screen on android
  src/components/context-menu/ContextCircleButton.android.js
  src/components/context-menu/ContextCircleButton.js
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Labels: nice for release

#5338 fix week ends bug
  src/screens/points/content/console/view-weekly-earnings.tsx
Labels: release

#5362 Points: UI tweaks
  src/components/cards/remote-cards/RemoteCard.tsx
  src/languages/en_US.json
  src/screens/points/ConsoleSheet.tsx
  src/screens/points/components/AnimatedText.tsx
  src/screens/points/content/PointsContent.tsx
  src/screens/points/content/console/calculate.tsx
  src/screens/points/content/console/initialize.tsx
  src/screens/points/content/console/require-wallet-balance.tsx
  src/screens/points/content/console/review.tsx
  src/screens/points/content/console/share.tsx
  src/screens/points/content/console/view-weekly-earnings.tsx
  src/screens/points/contexts/PointsProfileContext.tsx
Labels: rainbow points

#5391 coin icon: pull out spacing
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinBadge.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/components/exchange/ExchangeTokenRow.tsx
Labels: release

#5392 Remote card icon fix
  src/components/cards/remote-cards/RemoteCard.tsx
Labels: release

#5411 txSim: price clean up
  src/screens/SignTransactionSheet.tsx
Labels: release

#5414 ENS display changes + css tweaks
  src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
Labels: backups v2

#5409 skylar did all this
  src/components/backup/AddWalletToCloudBackupStep.tsx
  src/components/backup/BackupCloudStep.tsx
  src/components/backup/useCreateBackup.ts
  src/components/backup/usePasswordValidation.ts
  src/components/buttons/rainbow-button/RainbowButton.tsx
  src/hooks/useCloudBackups.ts
  src/hooks/useWalletCloudBackup.ts
  src/languages/en_US.json
  src/model/backup.ts
  src/navigation/types.ts
  src/screens/ExplainSheet.js
  src/screens/SettingsSheet/components/Backups/ViewCloudBackups.tsx
  src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
  src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
  src/screens/SettingsSheet/useVisibleWallets.ts
  src/screens/SettingsSheet/utils.ts
Labels: backups v2

#5410 chore: migrate pinned + hidden tokens
  src/migrations/index.ts
  src/migrations/migrations/migratePinnedAndHiddenTokenUniqueIds.ts
  src/migrations/types.ts
Labels: release

#5420 backups: show back up state
  package.json
  src/components/backup/BackupCloudStep.tsx
  src/components/backup/useCreateBackup.ts
  src/components/floating-emojis/FloatingEmojis.js
  src/hooks/index.ts
  src/hooks/usePortfolios.ts
  src/hooks/useSwapInputHandlers.ts
  src/languages/en_US.json
  src/redux/data.ts
  src/redux/explorer.ts
  src/screens/SettingsSheet/components/Backups/BackUpMenuButton.tsx
  src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
  src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
  src/screens/SettingsSheet/components/MenuItem.tsx
  src/screens/SignTransactionSheet.tsx
  src/screens/WalletScreen/index.tsx
  yarn.lock
Labels: backups v2

#5369 transactions: refactor
  src/components/activity-list/ActivityList.js
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
  src/components/coin-icon/TwoCoinsIcon.tsx
  src/components/coin-row/FastTransactionCoinRow.tsx
  src/components/coin-row/FastTransactionStatusBadge.tsx
  src/entities/f2c.ts
  src/entities/index.ts
  src/entities/protocolTypes.ts
  src/entities/transactions/index.ts
  src/entities/transactions/transaction.ts
  src/entities/transactions/transactionType.ts
  src/entities/transactions/zerionTransaction.ts
  src/handlers/transactions.ts
  src/helpers/buildTransactionsSectionsSelector.tsx
  src/helpers/transactions.ts
  src/hooks/useAccountTransactions.ts
  src/hooks/useENSLocalTransactions.ts
  src/hooks/usePendingTransactionWatcher.ts
  src/hooks/usePendingTransactions.ts
  src/hooks/usePoll.ts
  src/hooks/useTransactionConfirmation.ts
  src/hooks/useWalletsWithBalancesAndNames.ts
  src/hooks/useWatchPendingTxs.ts
  src/languages/en_US.json
  src/notifications/NotificationsHandler.tsx
  src/notifications/mapTransactionsType.ts
  src/parsers/index.ts
  src/parsers/newTransaction.ts
  src/parsers/transactions.ts
  src/raps/actions/crosschainSwap.ts
  src/raps/actions/ens.ts
  src/raps/actions/swap.ts
  src/raps/actions/unlock.ts
  src/react-query/types.ts
  src/redux/data.ts
  src/resources/transactions/consolidatedTransactions.ts
  src/resources/transactions/transaction.ts
  src/screens/AddCash/components/ProviderCard.tsx
  src/screens/AddCash/index.tsx
  src/screens/AddCash/providers/Ratio/index.tsx
  src/screens/AddCash/providers/Ratio/utils.ts
  src/screens/NFTSingleOfferSheet/index.tsx
  src/screens/ProfileScreen.js
  src/screens/SendConfirmationSheet.tsx
  src/screens/SendSheet.js
  src/screens/SettingsSheet/components/DevSection.tsx
  src/screens/SignTransactionSheet.tsx
  src/screens/SpeedUpAndCancelSheet.js
  src/screens/mints/MintSheet.tsx
  src/screens/transaction-details/TransactionDetails.tsx
  src/screens/transaction-details/components/DoubleLineTransactionDetailsRow.tsx
  src/screens/transaction-details/components/TransactionDetailsStatusActionsAndTimestampSection.tsx
  src/screens/transaction-details/components/TransactionDetailsValueAndFeeSection.tsx
  src/screens/transaction-details/helpers/getIconColorAndGradientForTransactionStatus.ts
  src/state/nonces/index.test.ts
  src/state/pendingTransactions/index.ts
  src/storage/index.ts
  src/utils/abbreviations.ts
  src/utils/ethereumUtils.ts
  src/walletConnect/__tests__/index.test
Labels: release

#5421 move nft fetching logic to graphql worker
  src/graphql/queries/arc.graphql
  src/resources/nfts/index.ts
  src/resources/nfts/simplehash/utils.ts
  src/resources/nfts/types.ts
Labels: nfts

#5429 send: fix l2 disclaimer
  src/screens/SendConfirmationSheet.tsx
Labels: release
