Repository rainbow-me/rainbow, pull requests merged in 2025-01, with the labels that each got.

#6377 add imported check on backup prompt
  src/handlers/walletReadyEvents.ts
  src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
Labels: release

#6378 [APP-2235] Verify functionality of isSwappingToTrendingAsset flag
  src/resources/trendingTokens/trendingTokens.ts
Labels: release

#6379 Fix nft icon sheet present & prioritize backup sheet
  src/featuresToUnlock/unlockableAppIconCheck.ts
Labels: release

#6318 Wallet Switcher v2
  src/components/DropdownMenu.tsx
  src/components/SmoothPager/ListPanel.tsx
  src/components/animations/JiggleAnimation.tsx
  src/components/animations/animationConfigs.ts
  src/components/cards/MintsCard/Menu.tsx
  src/components/change-wallet/AddressRow.tsx
  src/components/change-wallet/WalletList.tsx
  src/components/change-wallet/WalletOption.tsx
  src/components/drag-and-drop/DndContext.ts
  src/components/drag-and-drop/DndProvider.tsx
  src/components/drag-and-drop/components/Draggable.tsx
  src/components/drag-and-drop/components/DraggableFlatList.tsx
  src/components/drag-and-drop/components/DraggableScrollView.tsx
  src/components/drag-and-drop/components/index.ts
  src/components/drag-and-drop/features/sort/components/DraggableGrid.tsx
  src/components/drag-and-drop/features/sort/components/DraggableStack.tsx
  src/components/drag-and-drop/features/sort/hooks/useDraggableGrid.ts
  src/components/drag-and-drop/features/sort/hooks/useDraggableScroll.ts
  src/components/drag-and-drop/features/sort/hooks/useDraggableSort.ts
  src/components/drag-and-drop/features/sort/hooks/useDraggableStack.ts
  src/components/drag-and-drop/hooks/index.ts
  src/components/drag-and-drop/hooks/useChildrenIds.ts
  src/components/drag-and-drop/hooks/useDraggable.ts
  src/components/drag-and-drop/utils/collision.ts
  src/components/drag-and-drop/utils/geometry.ts
  src/components/drag-and-drop/utils/index.ts
  src/components/icons/Icon.js
  src/components/icons/svg/DragHandlerIcon.tsx
  src/components/tooltips/FeatureHintTooltip.tsx
  src/helpers/__tests__/utilities.test.ts
  src/helpers/utilities.ts
  src/hooks/useWalletTransactionCounts.ts
  src/languages/en_US.json
  src/navigation/Routes.android.tsx
  src/navigation/Routes.ios.tsx
  src/navigation/types.ts
  src/resources/summary/summary.ts
  src/screens/ChangeWalletSheet.tsx
  src/screens/change-wallet/ChangeWalletSheet.tsx
  src/screens/change-wallet/components/AddressAvatar.tsx
  src/screens/change-wallet/components/AddressRow.tsx
  src/screens/change-wallet/components/PinnedWalletsGrid.tsx
  src/screens/change-wallet/components/SelectedAddressBadge.tsx
  src/screens/change-wallet/components/WalletList.tsx
  src/state/wallets/pinnedWalletsStore.ts
  src/walletConnect/sheets/AuthRequest.tsx
Labels: release

#6356 Fix NFT save
  android/app/src/main/AndroidManifest.xml
  src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
  src/components/expanded-state/unique-token/saveToCameraRoll.js
  src/components/expanded-state/unique-token/saveToCameraRoll.ts
  src/handlers/imgix.ts
  src/utils/buildRainbowUrl.ts
Labels: release

#6389 Fix redacted icon on Android
  android/app/src/main/AndroidManifest.xml
Labels: release

#6314 Wallet Groups
  src/assets/CreateNewWalletGroup.png
  src/languages/en_US.json
  src/navigation/AddWalletNavigator.tsx
  src/navigation/routesNames.ts
  src/screens/AddWalletSheet.tsx
  src/screens/ChooseWalletGroup.tsx
  src/utils/abbreviations.ts
Labels: release

#6385 Migrate dapps query to createQueryStore
  src/components/DappBrowser/Homepage.tsx
  src/components/DappBrowser/search/results/SearchResults.tsx
  src/resources/metadata/dapps.tsx
Labels: performance

#6325 Add createQueryStore
  package.json
  src/components/DappBrowser/Homepage.tsx
  src/components/DappBrowser/search/results/SearchResults.tsx
  src/resources/metadata/dapps.ts
  src/resources/metadata/dapps.tsx
  src/state/internal/createQueryStore.ts
  src/state/internal/createRainbowStore.ts
  src/state/internal/createStore.ts
  src/state/internal/signal.ts
  src/state/internal/tests/QueryStoreTest.tsx
  src/utils/index.ts
  src/utils/time.ts
  yarn.lock
Labels: release, merge when ready, performance

#6387 Initial charts cleanup
  src/components/expanded-state/asset/ChartExpandedState.js
  src/components/expanded-state/chart/ChartExpandedStateHeader.js
  src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.tsx
  src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.tsx
  src/components/expanded-state/chart/chart-data-labels/ChartHeaderSubtitle.js
  src/components/expanded-state/chart/chart-data-labels/ChartHeaderTitle.tsx
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
  src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.tsx
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
  src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.tsx
  src/components/expanded-state/chart/chart-data-labels/index.ts
  src/components/expanded-state/chart/chart-data-labels/useRatio.ts
  src/components/expanded-state/chart/index.ts
  src/components/value-chart/Chart.js
  src/components/value-chart/ExtremeLabels.tsx
  src/hooks/charts/useChartDataLabels.ts
  src/hooks/charts/useChartThrottledPoints.ts
  src/navigation/config.tsx
  src/react-native-animated-charts/src/charts/linear/ChartLabels.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
  src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
  src/react-native-animated-charts/src/helpers/ChartContext.ts
  src/react-native-animated-charts/src/helpers/useChartData.ts
  src/react-native-animated-charts/src/helpers/useReactiveSharedValue.ts
  src/react-native-animated-charts/tsconfig.json
Labels: release, merge when ready, performance

#6391 Fix long token symbol overflow
  src/components/Discover/TrendingTokens.tsx
Labels: release

#6392 Fix address copy crash (and floating emojis animation)
  src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
  src/components/floating-emojis/CopyFloatingEmojis.tsx
  src/components/floating-emojis/FloatingEmoji.tsx
  src/components/floating-emojis/FloatingEmojis.tsx
  src/components/floating-emojis/GravityEmoji.tsx
  src/components/text/Emoji.js
  src/components/text/Emoji.tsx
  src/helpers/RainbowContext.tsx
  src/screens/ExternalLinkWarningSheet.tsx
Labels: release, merge when ready

#6376 Performance improvements
  android/app/src/main/res/values/styles.xml
  e2e/helpers.ts
  e2e/init.js
  ios/Podfile.lock
  ios/Rainbow/AppDelegate.h
  ios/Rainbow/AppDelegate.mm
  package.json
  patches/react-native-reanimated+3.16.6.patch
  patches/react-native-screen-corner-radius+0.2.2.patch
  src/App.tsx
  src/__swaps__/screens/Swap/Swap.tsx
  src/__swaps__/screens/Swap/components/SwapSheetGestureBlocker.tsx
  src/__swaps__/screens/Swap/constants.ts
  src/__swaps__/utils/meteorology.ts
  src/components/DappBrowser/control-panel/ControlPanel.tsx
  src/components/DappBrowser/hooks/useAnimatedTab.ts
  src/components/DappBrowser/hooks/useBrowserScrollView.ts
  src/components/DappBrowser/hooks/useTabScreenshotProvider.ts
  src/components/DappBrowser/hooks/useTabSwitchGestures.ts
  src/components/DappBrowser/search-input/SearchInput.tsx
  src/components/DappBrowser/search/Search.tsx
  src/components/DappBrowser/search/results/SearchResult.tsx
  src/components/DappBrowser/search/results/SearchResults.tsx
  src/components/sheet/DecoyScrollView.tsx
  src/handlers/localstorage/theme.ts
  src/hooks/useHideSplashScreen.ts
  src/hooks/useWalletsHiddenBalances.ts
  src/hooks/useWalletsWithBalancesAndNames.ts
  src/navigation/SwipeNavigator.tsx
  src/react-query/queryClient.ts
  src/resources/favorites.ts
  src/resources/metadata/dapps.ts
  src/state/assets/userAssets.ts
  src/storage/legacy.ts
  src/utils/deviceUtils.ts
  src/utils/safeAreaInsetValues.ts
  yarn.lock
Labels: release, merge when ready, performance

#6403 Adjust default queryClient cacheTime
  src/react-query/queryClient.ts
Labels: release, performance

#6413 Query store optimizations
  src/state/internal/createQueryStore.ts
  src/state/internal/queryStore/classes/SubscriptionManager.ts
Labels: performance

#6421 Fix emoji size type causing crash for Android
  src/components/floating-emojis/FloatingEmoji.tsx
  src/components/floating-emojis/FloatingEmojis.tsx
  src/components/floating-emojis/GravityEmoji.tsx
  src/components/sheet/sheet-action-buttons/SheetActionButton.tsx
  src/components/text/Emoji.tsx
  src/components/text/types.ts
Labels: release

#6409 Optimize backendNetworks store
  src/App.tsx
  src/__swaps__/screens/Swap/components/AnimatedChainImage.android.tsx
  src/__swaps__/screens/Swap/components/AnimatedChainImage.ios.tsx
  src/__swaps__/screens/Swap/components/CoinRow.tsx
  src/__swaps__/screens/Swap/components/ReviewPanel.tsx
  src/__swaps__/screens/Swap/components/TokenList/ChainSelection.tsx
  src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx
  src/__swaps__/screens/Swap/hooks/useSwapOutputQuotesDisabled.ts
  src/__swaps__/screens/Swap/providers/swap-provider.tsx
  src/components/BackendNetworks.tsx
  src/resources/metadata/backendNetworks.ts
  src/screens/WalletScreen/index.tsx
  src/state/backendNetworks/backendNetworks.ts
  src/state/backendNetworks/utils.ts
Labels: release, performance

#6419 bump slippage from 2 to 5 (except mainnet, polygon and bsc)
  e2e/parallel/4_discoverSheetFlow.spec.ts
  src/__swaps__/utils/swaps.ts
  src/model/remoteConfig.ts
Labels: release

#6390 Make transaction request parameters less rigid
  src/components/Transactions/TransactionMessageCard.tsx
  src/helpers/buildTransaction.ts
  src/screens/SignTransactionSheet.tsx
  src/walletConnect/types.ts
Labels: release

#6423 fix bottom sheet stacking order
  src/handlers/walletReadyEvents.ts
Labels: release

#6435 Store creator and createQueryStore improvements
  src/components/DappBrowser/BrowserTab.tsx
  src/components/DappBrowser/hooks/useWebViewHandlers.ts
  src/state/browser/browserStore.ts
  src/state/internal/createQueryStore.ts
  src/state/internal/createRainbowStore.ts
Labels: performance
