Repository rainbow-me/rainbow, pull requests merged in 2025-02, with the labels that each got.

#6433 Claim Bridge Slippage Adjustment to Follow Config & Better Error Logging
  src/raps/actions/claimBridge.ts
Labels: release

#6434 Deps bump
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: release

#6449 Add performance tooling
  index.js
  src/components/debugging/LogSheet.tsx
  src/config/experimental.ts
  src/hooks/useHideSplashScreen.ts
  src/languages/en_US.json
  src/navigation/Routes.android.tsx
  src/navigation/Routes.ios.tsx
  src/navigation/routesNames.ts
  src/navigation/types.ts
  src/performance/tracking/PerformanceToast.tsx
  src/performance/tracking/index.ts
  src/react-query/reactQueryUtils.ts
  src/screens/SettingsSheet/components/DevSection.tsx
  src/screens/SettingsSheet/components/Menu.tsx
  src/styles/fonts.js
Labels: performance

#6450 Migrate userAssets to createQueryStore, fix favorites
  src/App.tsx
  src/__swaps__/screens/Swap/providers/SyncSwapStateAndSharedValues.tsx
  src/__swaps__/screens/Swap/resources/assets/index.ts
  src/__swaps__/screens/Swap/resources/assets/userAssets.ts
  src/__swaps__/screens/Swap/resources/assets/userAssetsByChain.ts
  src/__swaps__/types/refraction.ts
  src/components/asset-list/AssetListHeader.js
  src/components/remote-promo-sheet/check-fns/hasNonZeroTotalBalance.ts
  src/components/remote-promo-sheet/check-fns/index.ts
  src/components/toasts/OfflineToast.js
  src/components/toasts/TestnetToast.js
  src/helpers/RainbowContext.tsx
  src/helpers/buildWalletSections.tsx
  src/hooks/useAccountSettings.ts
  src/hooks/useAsset.ts
  src/hooks/useENSRegistrationStepHandler.tsx
  src/hooks/useRefreshAccountData.ts
  src/hooks/useWalletSectionsData.ts
  src/hooks/useWalletsWithBalancesAndNames.ts
  src/hooks/useWatchPendingTxs.ts
  src/model/migrations.ts
  src/rainbow-fetch/index.ts
  src/react-query/queryClient.ts
  src/resources/addys/claimables/query.ts
  src/resources/favorites.ts
  src/screens/SendSheet.tsx
  src/screens/SettingsSheet/components/CurrencySection.tsx
  src/screens/WalletScreen/index.tsx
  src/state/assets/createUserAssetsStore.ts
  src/state/assets/persistence.ts
  src/state/assets/types.ts
  src/state/assets/userAssets.ts
  src/state/assets/userAssetsStoreManager.ts
  src/state/assets/utils.ts
  src/state/internal/withSelectors.ts
  src/state/sync/UserAssetsSync.tsx
Labels: release, performance

#6451 chore: update swaps sdk to 0.32.0
  package.json
  yarn.lock
Labels: release

#6384 Swaps search optimizations
  .eslintrc.js
  src/__swaps__/screens/Swap/Swap.tsx
  src/__swaps__/screens/Swap/components/CoinRow.tsx
  src/__swaps__/screens/Swap/components/SearchInput.tsx
  src/__swaps__/screens/Swap/components/SearchInputButton.tsx
  src/__swaps__/screens/Swap/components/TokenList/ChainSelection.tsx
  src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx
  src/__swaps__/screens/Swap/components/TokenList/TokenToSellList.tsx
  src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts
  src/__swaps__/screens/Swap/navigateToSwaps.ts
  src/__swaps__/screens/Swap/providers/SyncSwapStateAndSharedValues.tsx
  src/__swaps__/screens/Swap/resources/search/discovery.ts
  src/__swaps__/screens/Swap/resources/search/index.ts
  src/__swaps__/screens/Swap/resources/search/search.ts
  src/__swaps__/screens/Swap/resources/search/searchV2.ts
  src/__swaps__/screens/Swap/resources/search/utils.ts
  src/__swaps__/types/search.ts
  src/components/ExchangeAssetList.tsx
  src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
  src/state/swaps/swapsStore.ts
Labels: performance

#6469 Default idfa check to false when network fails
  src/model/remoteConfig.ts
Labels: release

#6462 Fix: Majority of Android devices show as "none" in analytics events
  src/analytics/index.ts
Labels: release

#6473 Fix broken 'open in Rainbow' option in Safari share menu
  ios/OpenInRainbow/ActionViewController.swift
  ios/ShareWithRainbow/ShareViewController.swift
Labels: release

#6474 Ensure env vars are defined when instantiating http client
  src/handlers/dispersion.ts
  src/handlers/gasFees.ts
  src/resources/addys/client.ts
  src/resources/transactions/consolidatedTransactions.ts
Labels: release
